### ISSUE TITLE
High memory consumption during handler reload (tool installation)

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#10662]
This is how it looks for us:

![grafik](https://user-images.githubusercontent.com/469983/98546670-59fb9c80-2297-11eb-99fc-3d7f7e54be5e.png)

We do have OpenMS installed and the usage is much more than 20.05. My suspician is also that there is a leak somewhere. During installation of many tools (OpenMS updates installs 120 tools) a reload of the handlers or zerglings is increasing the memmory significantly every time. This makes tool installations without constant restarts impossible.

Is anyone seeing a similar behaviour? Or is it really OpenMS that makes this bug visible.

_Originally posted by @bgruening in https://github.com/galaxyproject/galaxy/issues/7752#issuecomment-724013589_

**Comment by bgruening** [comment]
I wanted to deactivate the tool reloading during tool installation but it seems `watch_tools = false` has no effect. Handlers are still reloading memory consumption is growing, handlers finally OOM.

**Comment by mvdbeek** [comment]
I've tried reproducing this with 1000 reloads with usegalaxy.org's toolbox mounted via cvmfs on my laptop. Otherwise it's a pretty standard setup (4 processes, 4 threads, no openms). The starting consumption is 1.2G RSS per process, after the first ~ 50 reloads this goes up to 2.2G, but then drops for the remaining reloads back to 1.3G (I assume the GC process has kicked in at this point). I'd say I haven't seen the classic memory leak pattern here.

So 3 caveats here:
 - I'm not using zergs, and I don't know if they do something funky with memory management.
 - I'm not loading the install database, so the tool shed repository cache might possibly still leak memory
 - I'm just triggering reloads via a hack to the API, I'm not actually installing tools

that's the hack, if anyone wants to play with this:
```diff
diff --git a/lib/galaxy/webapps/galaxy/api/tools.py b/lib/galaxy/webapps/galaxy/api/tools.py
index ee13fd4b85..6f69fb35ac 100644
--- a/lib/galaxy/webapps/galaxy/api/tools.py
+++ b/lib/galaxy/webapps/galaxy/api/tools.py
@@ -208,11 +208,7 @@ class ToolsController(BaseAPIController, UsesVisualizationMixin):
         GET /api/tools/{tool_id}/reload
         Reload specified tool.
         """
-        trans.app.queue_worker.send_control_task('reload_tool', noop_self=True, kwargs={'tool_id': id})
-        message, status = trans.app.toolbox.reload_tool_by_id(id)
-        if status == 'error':
-            raise exceptions.MessageException(message)
-        return {'message': message}
+        trans.app.queue_worker.send_control_task('reload_toolbox')
 
     @web.require_admin
     @expose_api

```

I will load up mains' sqlite to see if that changes anything. I can't quite imagine that the openms tools do anything that would leak memory, but I can also give that a shot.

**Comment by mvdbeek** [comment]
Same situation with the install database loaded, the baseline is higher (~1.9G), then increases slightly during reloads to go back even lower than the starting situation.

**Comment by mvdbeek** [comment]
@bgruening what you could do is have the zerglings and job handlers load from a config file that doesn't load the install database. I don't know what the starting situation is with regards to memory consumption, but if it comes from the repository cache that might be worth a try. If it does help we can make that the default, I don't think job/workflow handlers need to know anything about tool shed repositories.

**Comment by mvdbeek** [comment]
Curious to see how this will go on 21.01 with the disabled tool cache, let us know how it goes @bgruening!

**Comment by bgruening** [comment]
![grafik](https://user-images.githubusercontent.com/469983/111865058-085dcf80-8965-11eb-906e-1379d7975cc6.png)

It's a little bit unbelievable to be honest. The memory consumption dropped by nearly 2/3 and it is nearly as fast as before to start.

Awesome work @mvdbeek!
