### ISSUE TITLE
GTN integration hiccups on org/eu

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#10855]
With @bgruening we just discovered the following:

* When running Chrome Version 87.0.4280.88 (Official Build) (x86_64)
  - [x] When you scroll in the GTN overlay, close it, and then open it again it should remember the position of your scrollbar. It does not remember that on usegalaxy.eu. Works well on usegalaxy.org.
  - [x] When training overlay is open and you click the tool name, it should open the tool form of the exact tool. ~~It does not open the tool on usegalaxy.org and the button looks different.~~ This works on usegalaxy.eu. 
    * This does not work on .org because of a missing proxy (thanks @hexylena) see https://docs.galaxyproject.org/en/master/admin/special_topics/gtn.html

* On FF 83.0 everything works everywhere. 🤔

ping @hexylena

**Comment by hexylena** [comment]
There should be a link at the bottom of the frame on. Org. It explains why the buttons don't work. It's in the docs

**Comment by hexylena** [comment]
It's definitely because I test primarily in ff :sweat_smile:

Ok, on EU it looks like they're probably missing https://github.com/galaxyproject/galaxy/pull/10362 somehow. They've got the commit, but the behaviour is still pre-that commit behaviour where `d-none` was used instead of visibility hidden. Maybe just need to rebuild client? @bgruening @gmauro.

**Comment by martenson** [comment]
should be fixed by https://github.com/galaxyproject/galaxy/pull/11290
