### ISSUE TITLE
Schema and documentation for API routes

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#10888]
fastapi supports annotating API parameters and outputs using typed annotations, and validating incoming and outgoing data that way. I think it would be very important that we attempt to fully annotate new routes.

https://github.com/galaxyproject/galaxy/blob/14272c1e012a00e3c76a6011508f9027e2489463/lib/galaxy/webapps/galaxy/api/jobs.py#L79 is an example for a very simple response model.

A very short introduction into type annotations is [in the fastAPI docs](https://fastapi.tiangolo.com/python-types/), and documentation on how to leverage this in fastAPI starts in the [path params section of the tutorial](https://fastapi.tiangolo.com/tutorial/path-params/) section

**Comment by jmchilton** [comment]
In https://github.com/galaxyproject/galaxy/pull/11115, I've updated the API design guidelines to link some best practice examples of this annotation in the code base, link out the Pydantic docs, and mention parameters should have field definitions and be typed.

I've held back including a bunch of fastAPI stuff because I think Pydantic should be the focus until we have a hard requirement on fastAPI and we can require all new controllers to be the async variant.

**Comment by mvdbeek** [comment]
I think we're well on our way, no need for this issue anymore.
