### ISSUE TITLE
Tools with input type="data_column" fails for empty files

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#10918]
An empty file should be a valid input for a tool. Galaxy throws:
```
parameter 'column': an invalid option ('4') was selected (valid options: 1)
```
when the `toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/tp_sort_header_tool/1.1.1` tool is handed an empty file.

This is an issue with Galaxy rather than the tool as the error is thrown during input creation.

**Comment by kxk302** [comment]
I'll look into this tomorrow.

**Comment by kxk302** [comment]
Hi @innovate-invent 
I uploaded a file with 1 line (could not upload and empty file), removed the first line of the file (its empty then), and passed it to sort and it completed successfully with no error (so, I cannot re-produce the problem). Could you please provide more info on how to re-produce the issue? 
Thanks,
-Kaivan

**Comment by innovate-invent** [comment]
Did you refer to column 4 in the test? I am assuming that if you refer to column 1 it will not encounter the error as it considers an empty file to have 1 column

**Comment by kxk302** [comment]
> Did you refer to column 4 in the test? I am assuming that if you refer to column 1 it will not encounter the error as it considers an empty file to have 1 column

Thanks, yes, I managed to re-produce it.

**Comment by innovate-invent** [comment]
Any luck with this?

**Comment by kxk302** [comment]
Yes, I re-produced the issue, and came up with a fix, which I tested locally. I'll create a PR and will tag you there so you can comment. Thanks.

**Comment by mvdbeek** [comment]
> Any luck with this?
> 
> I had a quick look at the code and it looks like the following needs to be added here:
> 
> https://github.com/galaxyproject/galaxy/blob/f7bba746b1d33693c2f4f3f59d829b54756da2ba/lib/galaxy/tools/parameters/basic.py#L1339
> 
> ```python
> dataset = other_values.get(self.data_ref)
> if not dataset or is_empty(dataset): return None
> ```
> 
> I just need help defining the is_empty function

The parameter (`4`) won't be part of the legal values (which is `None` with your change). This only works for a very narrow set of tools (profile < 18.09 and `accept_default="true"`), and that only works because we didn't want to break legacy tools.

I am a worried about not failing when we should fail, thereby producing incorrect results. I could see a case where you'd have a tool where you can pick multiple columns and compare them for equality, and you did not anticipate the case that you might be comparing null with null. But maybe that's too hypothetical ?
I see those options:

- ignore problems, merge https://github.com/galaxyproject/galaxy/pull/10981
- https://github.com/galaxyproject/galaxy/pull/10981 + "allow_invalid_column_selection" parameter
- remove empty datasets (can do that with collection operation tool)
- replace column metadata with expected metadata (could do that with a custom tool)
- skip execution with conditional (that isn't 100% done yet)

I tend to think we could probably merge https://github.com/galaxyproject/galaxy/pull/10981, given that I don't really like any of those solutions.

**Comment by kxk302** [comment]
> Any luck with this?
> 
> I had a quick look at the code and it looks like the following needs to be added here:
> 
> https://github.com/galaxyproject/galaxy/blob/f7bba746b1d33693c2f4f3f59d829b54756da2ba/lib/galaxy/tools/parameters/basic.py#L1339
> 
> ```python
> dataset = other_values.get(self.data_ref)
> if not dataset or is_empty(dataset): return None
> ```
> 
> I just need help defining the is_empty function

I moved the logic to get column_list().

**Comment by kxk302** [comment]
The code change in PR fixes the reported problem. It's only applicable to ColumnListParameter, when dataset size is 0, and when an input has been specified. Still, my concern is any side effects this change might have. I guess we can rely on tests. Could also ask  @jmchilton take a look at it, for an extra pair of eyes.

**Comment by innovate-invent** [comment]
@mvdbeek get_legal_values returning None triggers: https://github.com/galaxyproject/galaxy/blob/f7bba746b1d33693c2f4f3f59d829b54756da2ba/lib/galaxy/tools/parameters/basic.py#L894

I suppose the issue with this is the return value of these functions are not documented. Given the way the code is written I assumed that get_legal_values returning None meant that all values are legal.

**Comment by mvdbeek** [comment]
That is only the case when scheduling a workflow and the input dataset is not produced yet, https://github.com/mvdbeek/galaxy/blob/aee371227d5104b42083234a5aced931628c5159/lib/galaxy/tools/parameters/basic.py#L917 is where this is handled if the dataset already exists.

**Comment by kxk302** [comment]
I made another revision (hopefully the last one) and moved the logic to get_legal_values().

**Comment by mvdbeek** [comment]
Should be resolved in https://github.com/galaxyproject/galaxy/pull/10981
