### ISSUE TITLE
Issue for linking history when a . in the public name

### ISSUE THREAD

**Issue by lecorguille** [galaxyproject/galaxy#11209]
Hi,

At usegalaxy.fr, we met this strange issue: 
https://community.france-bioinformatique.fr/t/galaxy-history-sharing-compromised/923/5 

It seems that a link generated for historie is buggy when the user have a `.` in his public name.

This issue appear with the 20.05 -> 20.09

**Comment by dannon** [comment]
So technically that's an invalid public name.  If you go to user preferences and try to set a name to one with a `.`, you see the error message:
```
Public name must contain only lowercase letters, numbers and "-". It also has to be shorter than 255 characters but longer than 2.
```

That said, it looks like when registering we don't validate publicname the same way, so it's still possible to create a new user as such.  That's a separate bug, though -- that we should enforce the same requirements everywhere.

Since URLs should be forever, I'll see what I can do about making this work with the existing `.`, though.

**Comment by lecorguille** [comment]
Thanks for the reply @dannon 

> Since URLs should be forever, I'll see what I can do about making this work with the existing ., though.

As you want but my user just changed her public name 👍

**Comment by nsoranzo** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/11260 .
