### ISSUE TITLE
auto-creation of inputs fails in workflow best practices

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#11562]
I was testing the ui for the release notes and hit this when attempting to auto-create inputs.

![2021-03-08_13-39](https://user-images.githubusercontent.com/458683/110322778-edf62e80-8013-11eb-9d3c-3d90780bfbc1.png)

it's a 1 step workflow so should be easy to reproduce, let me know if more details are needed. I'm on 6465b788361378ec71baa69cd3537ab07f5f8fe6 which is currently pointing to release_21.01

**Comment by mvdbeek** [comment]
I think that was fixed in https://github.com/galaxyproject/galaxy/pull/11527 ... which you should have if you're running on https://github.com/galaxyproject/galaxy/commit/6465b788361378ec71baa69cd3537ab07f5f8fe6. Any chance you can go to the latest 21.01,  rebuild the client and test again ? It does seem to work for me.

**Comment by hexylena** [comment]
Sure

**Comment by mvdbeek** [comment]
I'm gonna assume this is fixed.
