### ISSUE TITLE
HOME env var overwritten in GxIT

### ISSUE THREAD

**Issue by abretaud** [galaxyproject/galaxy#11573]
Hi,
Doing some tests on interactive tools with 21.01, and encountered a problem (which was already there in 20.09 in fact): the HOME env var is set to the value of the user running galaxy instead of keeping the value defined in the Docker image.
Depending on the GxIT it can be a problem:
- Jupyter wants HOME to be set to `/home/jovyan`, changed like this on usegalaxy.eu : https://github.com/usegalaxy-eu/infrastructure-playbook/blob/master/files/galaxy/dynamic_rules/usegalaxy/tool_destinations.yaml#L44
- Ethercalc wants HOME to be set to `/root`

(doing the same with or without PulsarEmbeddedJobRunner)

Is there a specific reason for galaxy to force the value of this env var?

**Comment by mvdbeek** [comment]
If images require a given HOME path they should probably set this in the tool.
Since the tools are tied to a container I don't think there's any harm setting the HOME explicitly in the command section.

> Is there a specific reason for galaxy to force the value of this env var?

This is the general behavior of Galaxy. We forward (actually we don't touch) HOME as it is set up in the surrounding environment for legacy profile version, and we set it to a directory in the job working directory when not using a legacy profile version. For containers we forward whatever HOME is set to in the container.

**Comment by abretaud** [comment]
Ok yep, I can make a PR to add this to the jupyter/ethercalc wrappers

**Comment by abretaud** [comment]
While I'm at it, I suspect this `cp` is not working in pulsar mode: https://github.com/galaxyproject/galaxy/blob/dev/tools/interactive/interactivetool_jupyter_notebook.xml#L33
Is it expected/workaroundable?

**Comment by mvdbeek** [comment]
Hmm, that would be a pulsar bug ... it usually does transfer `$__tool_directory__`, contents, but maybe that's based on a regex ??? @jmchilton ?
