### ISSUE TITLE
Show all running jobs on Admin -> jobs page

### ISSUE THREAD

**Issue by Slugger70** [galaxyproject/galaxy#11717]
Prior to 21.01 the Admin->Jobs page used to show all running/queued/new jobs in the top section and only jobs completed in the cutoff time in the bottom section. 
In 21.01 it now only shows jobs from the cutoff time for both sections.
I would much prefer the prior behaviour regardless of load times as now I have to think about how long the job might have been running for it to be displayed in the list. If it has been days then I also get days and days worth of completed jobs being displayed which really slows everything down.
Could we perhaps have a checkbox on the UI to revert back to the prior behaviour?

**Comment by dannon** [comment]
@Slugger70 Thanks for the feedback.  I actually changed this in https://github.com/galaxyproject/galaxy/pull/11205/files#diff-357416b9a283346372fe346895d08181dfbea522f797dfd88aa79ede6c45f34fL1531 because the prior behavior was confusing.  The top section was only showing jobs updated *less* frequently than the cutoff, so it wasn't showing stuff it should have been.

Instead of a checkbox to revert to that behavior, how about a checkbox to just not filter the top at all and show it all?

**Comment by Slugger70** [comment]
Hey @dannon. That sounds like a much better idea. Cheers mate.
