### ISSUE TITLE
consider bringing back data libraries back button functionality

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#11739]
Current implementation does not support browser "back" button when browsing folders in libraries. Instead of returning you to the last folder/view as is expected in similar interfaces it brings you back all the way to the list of libraries and you have to navigate back one by one (because the "forward" button also does not work as expected).

**Comment by OlegZharkov** [comment]
Hi @martenson,

browser "back" and "forward" buttons are fixed in https://github.com/galaxyproject/galaxy/pull/11614
The `parent folder` button isn't likely coming back as we disscused it in https://github.com/galaxyproject/galaxy/issues/10800https://github.com/galaxyproject/galaxy/issues/10800 and https://github.com/galaxyproject/galaxy/pull/11230

**Comment by martenson** [comment]
I seem to always be about two weeks behind you 🤣. Thanks a bunch @OlegZharkov! And sorry for the noise.

**Comment by OlegZharkov** [comment]
> Thanks a bunch @OlegZharkov! And sorry for the noise.

no worries, thanks for reporting ;)
