### ISSUE TITLE
release 20.09 possibly broke the ability to install tools

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#11746]
Both the actual release and the affected Galaxies are not exactly known, but at least 16.xx Galaxies seem to have this problem with TS 20.09 or later (possibly 21.01, I am not sure when was MTS updated to it).

based on https://help.galaxyproject.org/t/toolshed-not-working-anymore-with-old-galaxy/5302

I am not aware of any big framework-affecting changes so this might have been caused by something tiny that could be worth fixing.

If not worth fixing we should clearly state we broke this in the release notes.

**Comment by mvdbeek** [comment]
The last supported release is 20.01, which I verified works correctly. This was actually fixed with https://github.com/galaxyproject/galaxy/pull/8090.
We did not break anything, this is due to the stricter cross origin browser policies. And we state clearly we only support releases going back 1 year from the latest release. We unfortunately do not have resources to fix these old issues.

**Comment by martenson** [comment]
Oh, it's CORS, that's not a tiny thing then. I wonder why they started to see it just recently though.
