### ISSUE TITLE
Deprecate support posgresql < 10

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#11919]
The way https://github.com/galaxyproject/galaxy/pull/11914 is implemented it will only work for postgresql >= 10.
It's not impossible to support older postgresql, but I think we should just drop support at this point.

**Comment by hexylena** [comment]
- It looks like RHEL/CentOS 6 is around to end of 2021 ([1]), and that only supports 8.4.
- RHEL/CentOS 7 supports up to 10 ([2]), so perhaps after 2021 we could deprecate safely? (Safely meaning that their DBA could upgrade easily with system packages, but up to that galaxy admin to convince them probably.)

I'm not sure how much of the community is stuck on RHEL6 due to their uni/cluster admins, which should probably be the deciding factor. We'd essentially be telling them they can't upgrade despite potentially buggy older releases. And I guess the acceptability of that depends on what % of the community is on that older version. We could survey them, but not everyone is in the gitter channel. That said, RHEL6 is ancient. (That said, RHEL users don't upgrade often.)

[1]: https://en.wikipedia.org/wiki/Red_Hat_Enterprise_Linux#Version_history_and_timeline
[2]: https://www.postgresql.org/download/linux/redhat/

**Comment by bgruening** [comment]
According to this site you could get a newer postgresql even for RHEL-6: https://www.postgresql.org/download/linux/redhat/

I would be in favor of deprecating.

**Comment by dannon** [comment]
For what it's worth, postrgresql 9 is EOL November 11, 2021 according to https://www.postgresql.org/support/versioning/.  So we're a little ahead of the curve on deprecating it, but not really by that much.

**Comment by mvdbeek** [comment]
Moving it to 21.09, now that the draft PR also has row triggers.

**Comment by mvdbeek** [comment]
I guess there's no urgent need for this right now.

**Comment by dannon** [comment]
@mvdbeek I don't think there's anything to do other than make a statement in the release notes, right?  postgresql 9 is EOL, we should totally be in the clear to call it deprecated and use modern featuers.

**Comment by mvdbeek** [comment]
We should probably error out once we do use newer features, but we still test against 9.6. For now I don't think we need to deprecate.

**Comment by mvdbeek** [comment]
OK, let's deprecate in the release notes without erroring out on startup.

**Comment by dannon** [comment]
Deprecation notice added in #13377
