### ISSUE TITLE
Version query parameter not working for Dockstore/TRS import

### ISSUE THREAD

**Issue by coverbeck** [galaxyproject/galaxy#12017]
Dockstore is implementing a Launch with Galaxy button. When we specify the version, using the `trs_version` query parameter, the Galaxy UI shows an error, and you are prompted which version to select. The expected behavior is that Galaxy should import the specified version.

To reproduce, go to https://usegalaxy.org/workflows/trs_import?trs_server=dockstore.org&trs_id=%23workflow/github.com/jmchilton/galaxy-workflow-dockstore-example-1/mycoolworkflow&trs_version=master

![Screen Shot 2021-05-19 at 10 17 18 AM](https://user-images.githubusercontent.com/1049340/118856806-32137400-b88c-11eb-808f-d9da8f962cd0.png)

Also see [discussion on Dockstore issue](https://github.com/dockstore/dockstore/issues/3764#issuecomment-833843789).

**Tangential Issue**

Let me know if I should log this separately. We'd like to specify a different Dockstore server for testing purposes. We have our daily build and staging environments. When we specify `...?trs_server=dev.dockstore.net&...`, an error pops up briefly and Galaxy seems to read from dockstore.org. Is this supposed to work?

**Comment by mvdbeek** [comment]
> When we specify `...?trs_server=dev.dockstore.net&...`, an error pops up briefly and Galaxy seems to read from dockstore.org. Is this supposed to work?

It is, but we need to add `dev.dockstore.net` to the enabled and validated trs server list, I will make sure we enable this for usegalaxy.org / test.galaxyproject.org.

The version handling seems slightly off, I'll have a fix shortly.

**Comment by coverbeck** [comment]
> It is, but we need to add `dev.dockstore.net` to the enabled and validated trs server list, I will make sure we enable this for usegalaxy.org / test.galaxyproject.org.

Great! While you're doing that, could you please add our staging environment as well, staging.dockstore.org? So 3 total:

* dockstore.org
* staging.dockstore.org
* dev.dockstore.net

Thanks!

**Comment by mvdbeek** [comment]
OK, so this is a discrepancy between what workflowhub.eu defines as the "trs_version". For workflowhub.eu, this is what matches the `id` field, while for dockstore.org this matches the `name`. The `name` field looks better to me, since it actually contains the user-defined version of the workflow, but it would be great if this can be synced up (@bedroesb @bgruening you have workflowhub connections, right ?).

This is the workflowhub.eu:
<img width="635" alt="Screenshot 2021-05-19 at 21 49 10" src="https://user-images.githubusercontent.com/6804901/118875230-163fba80-b8ec-11eb-9654-2598c2747edc.png">
This is dockstore.org:
<img width="750" alt="Screenshot 2021-05-19 at 21 51 49" src="https://user-images.githubusercontent.com/6804901/118875546-759dca80-b8ec-11eb-950e-2dc80bb8a5f6.png">

I'm just gonna allow both for now, but this should really be resolved.

**Comment by bgruening** [comment]
This is just poorly defined in the spec and its not clear for the workfowhub people. @coverbeck this is the related issue: https://github.com/ga4gh/tool-registry-service-schemas/issues/153

On usegalaxy.eu we ship actually a patch to support both version.

**Comment by coverbeck** [comment]
Ah, right, thanks, I remember that ticket now @bgruening.

**Comment by bgruening** [comment]
Your welcome! Thanks for looking into it!

**Comment by mvdbeek** [comment]
Alright, https://github.com/galaxyproject/galaxy/pull/12021 fixed the query parameter, and I've enabled dev and staging servers on https://test.galaxyproject.org/. Thanks for the report @coverbeck!
