### ISSUE TITLE
Email subscription for new users does not appear to work for Mailman 3

### ISSUE THREAD

**Issue by tnabtaf** [galaxyproject/galaxy#12268]
Since we migrated Galaxy Project to Mailman 3 (from Mailman 2), membership in the galaxy-announce mailing list has been on a slow decline.  This was after years of growing by more than 1000 people a year.

The email  generated by  [`send_subscription_email(self, email)`](https://github.com/galaxyproject/galaxy/blob/296d48c53f096427b9a0f19a42a34089103c21e1/lib/galaxy/managers/users.py#L579) does not work with Mailman 3.  The [Mailman 3 doc](https://docs.mailman3.org/projects/mailman/en/latest/src/mailman/commands/docs/help.html) implies that a subject line of just "join" will work.  Testing with Mailman 3 indicates that a subject and body of "Join Mailing List" gets

```
- Results:
Ignoring non-text/plain MIME parts
join bad argument: mailing

- Unprocessed:
Join Mailing List

- Done.
```

Putting just "join" in the subject and body results in a confirmation email being sent to the sender.

I suspect that the subject and body should be made configurable so that Galaxy works with Mailman 2 and 3, and Sympa too.  Could put these items in config, or put mailing list software and version in configuration, and then handling in the code.

**Comment by natefoo** [comment]
So, I added configuration options for the admin to specify the subject and body. I set them to `join`, registered an account in my local Galaxy, and got the confirmation email from our Mailman server. Yay! :tada: 

Then, to make sure I had the defaults correct, I tried again with the options unset, so the message would be sent with the old `"Join Mailing List"` defaults, and... I got the confirmation email from Mailman again. Wat? :exploding_head:  

Turns out, Mailman 3 is apparently perfectly fine with `"Join Mailing List"`. The issue on usegalaxy.org is that `mailing_join_addr` is not set, and at some point (probably during the config overhaul) its default value became `null`, meaning that the option to register for the mailing list doesn't even show up on the registration page on Main. Go ahead, open an incognito window and head on over to see.

I will go ahead and PR the new config options just because they might be useful, and then I'll go set `mailing_join_addr` on Main...

**Comment by natefoo** [comment]
I have set `mailing_join_addr` on usegalaxy.org and registered a test user with the box checked and I received the subscription confirmation email as expected.

In unrelated news, the user `nate-subscribe-me-to-announce-test6` appears to be a duplicate account and we should ban them from Galaxy.

**Comment by assuntad23** [comment]
@natefoo Can we close this issue now?

**Comment by tnabtaf** [comment]
Galaxy Announce mailing membership has resumed it's upward climb.  So, this
appears to be working.

**Comment by natefoo** [comment]
Thank you for confirming from your new digs, @tnabtaf!
