### ISSUE TITLE
Tiny typo on UseGalaxy.org

### ISSUE THREAD

**Issue by melibleq** [galaxyproject/galaxy#12322]
Hi there, Galaxy. I've found a little typo (the word "Andvanced") on UseGalaxy.org > Miscellaneous Tools > Proteomics > Search GUI (Perform protein identification using various search engines and prepare results for input to Peptide Shaker):

![Captura de tela de 2021-07-07 16-49-35](https://user-images.githubusercontent.com/16723182/128244401-14ebf214-cd4f-4cf1-b515-e6c0b3781a29.png)

I've browsed several repos (GalaxyProject, useGalaxy.eu, [GalaxyP](https://github.com/galaxyproteomics), [Computational Omics](https://github.com/compomics)) to see if I could make a PR fixing the typo, but couldn't find a way to do it. It only came up in a section of the training material ([here](https://github.com/galaxyproject/training-material/blob/f30c1fed5c322e22a1397eb3ea75c3f9cedc67ed/topics/proteomics/tutorials/metaquantome-data-creation/tutorial.md)).

Please let me know if there's a way for me to fix it myself, since that is such a tiny issue. Thanks!

**Comment by bgruening** [comment]
@melibleq thanks a lot for reporting and spending time trying to fix this tool. The tool is part of the Galaxy Proteomics community and you can find it here: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/peptideshaker

Fortunately, this typo is already fixed in the most recent version. You can find the latest version here for example: https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/galaxyp/peptideshaker/search_gui/4.0.41+galaxy0

On usegalaxy.org we need to update the tool.

Thanks again, that information is really appreciated.

**Comment by melibleq** [comment]
Amazing! I'm glad it's fixed there! Thanks a lot for the ultrafast reply.

Should I keep this issue open for the usegalaxy.org update? I suppose this would be the right repo for that, but please correct me if not.

**Comment by bgruening** [comment]
We can close this here I think. This is about the main Galaxy code base, more technical. If you like you can open an issue here: https://github.com/galaxyproject/usegalaxy-tools which is about the subset of Galaxy tools that are installed on ORG.

**Comment by melibleq** [comment]
Alright, thanks a lot!
