### ISSUE TITLE
Dataset Collections marked as running even when not

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#1244]
NONE of the pre-requisite datasets are actually available, and the DCs are still marked as running.

![2015-12-04-152236_681x748_scrot](https://cloud.githubusercontent.com/assets/458683/11601778/2aef1266-9a9b-11e5-968e-06145093af4d.png)

Somewhat related to #983

**Comment by jmchilton** [comment]
Are they marked as running or simply as yellow.

This is similar to how most dataset collections will be marked as green even when the datasets are gray for instance. They are green because the structured is known - even if the datasets aren't ready, this is yellow because it is a dynamically discovered dataset collection so he structure is not yet known.

Not sure these are bugs - they are just unintuitive behaviors in need of someone to go in and refine them :smile:.

**Comment by hexylena** [comment]
They're yellow with a spinner. Yes, definitely related to #983 hence that note in the original post. Years of conditioning from galaxy have led me to expect `green = done` and `yellow with spinner = running`.

That's a very interesting rationale to hear, and yes, completely unintuitive from my perspective. How can we reconcile this? Would you be OK with DCs with unknown structure being grey, and those with not-yet-collected datasets being yellow? I guess it boils down to "is the fact that the DC's structure is or isn't known actually a useful piece of information to capture for _anyone_?"

**Comment by jmchilton** [comment]
It is useful in the sense that I added because @pvanheus spent all morning thinking his tool wasn't working when it was in fact fine - it just was green before the job was complete. If you made it gray instead (which I am fine with), then you would have the inverse problem - people thinking it is not running when it is.

I think in general I have avoided prescribing collections state - because coordinating hundreds of jobs into a unified state is inherently an expensive operation. Perhaps for these particular use cases (collections output from single jobs - as oppose to collections resulting from hundreds of jobs) we should just use the job state in the history panel.

Certainly the job state can be inferred all within in single query, so it might be an expensive join - but perhaps worth doing and just seeing if we bring down main :worried:. Maybe other optimizations (https://github.com/galaxyproject/galaxy/pull/1179) would save us a bunch of time we can spend on this instead. Perhaps also we could load all the dataset collections as blue or something and then check their state with less frequency than we check the datasets.

**Comment by jmchilton** [comment]
I guess I should reclarify that I am not trying to say this isn't problematic, it is. I'm just saying a lack of collection state is not a bug it is a missing feature - and someone needs to disappear to a mountain top for two months and figure this out and optimize this to an incredible degree.

**Comment by martenson** [comment]
Can we abandon showing state on collections? i.e. make them distinctively stateless instead of inconsistent with the original history items?

**Comment by jmchilton** [comment]
@martenson that would be a better stop gap then green, gray, and yellow - I'd love to see that.

**Comment by martenson** [comment]
what does @carlfeberhard think?

**Comment by hexylena** [comment]
> It is useful in the sense that I added because @pvanheus spent all morning thinking his tool wasn't working when it was in fact fine

yes, I've experienced that too

> it just was green before the job was complete. If you made it gray instead (which I am fine with), then you would have the inverse problem - people thinking it is not running when it is.

My personal expectations are:
- no sub-jobs running = grey
- at least one sub-jobs running = yellow
- all sub-jobs done = green

which handles the case that @pvanheus and I both experience (green before done) and the other oddities, and makes it behave like normal galaxy users expect.

> I think in general I have avoided prescribing collections state - because coordinating hundreds of jobs into a unified state is inherently an expensive operation. Perhaps for these particular use cases (collections output from single jobs - as oppose to collections resulting from hundreds of jobs) we should just use the job state in the history panel.

I'd be fine with that for that case, I really dislike all of my datasets turning green before every dataset has shown up in history, it's killing me due to the support emails I keep getting from users. Do you have an hourly rate for mount-top-thinking? ;)

Is a `count(*) where state="running" and collection_id="123"` really that expensive? :(

@martenson 

> Can we abandon showing state on collections? i.e. make them distinctively stateless instead of inconsistent with the original history items?

I (well, my users) would really like to know if (some part) of the collection is being worked on or not. I suppose that's an improvement from colouring that just feels completely incorrect.

**Comment by jmchilton** [comment]
@erasche This is before my time, but my understanding is we brought down main (or at least made it unusable) when polled histories for their contents on a loop. There are still open bugs because we don't do that anymore. I want to see the history panel load faster and handle more datasets and dataset collections, a join on a count on thousands of extra job rows seems a step backward on that count. A step forward on usability though obviously, it is a balancing act.

**Comment by hexylena** [comment]
@jmchilton completely understandable. I want it to load faster too (and I can think of quick optimisations just off the top of my head, like not requesting the ENTIRE history when I expand a single dataset item)

If I was more familiar with the code for this I'd try and get you some metrics and optimisations, but until then @martenson's hack sounds very workable and we can revisit this later.

**Comment by carlfeberhard** [comment]
@martenson I would guess users will infer a state even if we make it stateless. How were you thinking of doing it?

@erasche 

> like not requesting the ENTIRE history when I expand a single dataset item

I'm not sure it's doing that. How/where are you seeing this happen?

@jmchilton 
My plan on history performance was to:
- fill out the collections/hda/history/container api/managers to handle pagination (and filtering)
- paginate the histories implicitly by only loading the most recent 50-100 contents
- when the user scrolled to the bottom, load more
- I'd also like to poll the job state of a history. It's the most reliable way to get _all_ the datasets created from a job and I still think it's doable

There are certainly other things that can be done as I haven't had time to iterate over the history client/server stuff in a while. I'll squash another iteration into 16.01 if I can.

**Comment by martenson** [comment]
@carlfeberhard tough question, some ideas:
- giving it the same color as the panel background? (the galaxy purplish)
  - also maybe make it different by removing the click event and providing an 'eye' button to look inside - so the cursor won't change
- giving it another unique color
- provide a tooltip with the information

**Comment by hexylena** [comment]
@carlfeberhard 

> > like not requesting the ENTIRE history when I expand a single dataset item
> 
> I'm not sure it's doing that. How/where are you seeing this happen?

I feel like a crazy person.. I know I've been seeing this. Maybe I upgraded recently and that was fixed. Jeez. I'm awful sorry.

**Comment by carlfeberhard** [comment]
The plan from my (much) earlier list is mostly done.
- Is this still an issue after the changes in #1788? 
- If so, are visually stateless collections still the way people want to go forward with this?
