### ISSUE TITLE
Beta history: contents_near API endpoint fails on -infinity

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#12498]
Seen this in the tests (https://github.com/galaxyproject/galaxy/pull/12497/checks?check_run_id=3638939695):
```
ERROR    galaxy.web.framework.decorators:decorators.py:327 Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/web/framework/decorators.py", line 312, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/webapps/galaxy/api/history_contents.py", line 1780, in contents_near
    hid = int(hid)
ValueError: invalid literal for int() with base 10: '-Infinity'
```

It doesn't really make sense to request -infinity, the lowest hid is 1, so that is a fix we can use on the backend. Not sure where this is coming from on the frontend.

**Comment by davelopez** [comment]
That will be certainly easy to fix in the current legacy endpoint with a `try/catch` or similar, but when we move this endpoint to FastAPI, `hid: int = Path(default=1)` will fail the validation and return `Bad request` I guess... maybe we can create a custom dependency function that converts `Infinity` and `-Infinity` to a `min` or `max` value. But then, should we use this dependency for each possible `int` that we can get in a Path or Query parameter?
IMHO, if we get `Infinity` or a similar unexpected numeric value in the request it should be a `Bad Request` otherwise we may be hiding a bug in the client or adding complexity to recover from it. What do you think?

**Comment by mvdbeek** [comment]
I guess we also need to see where this is coming from in the client, this might as well be a bug. In which case a `Bad Request` would be correct.
