### ISSUE TITLE
New histories from workflow runs don't populate without a refresh

### ISSUE THREAD

**Issue by astrovsky01** [galaxyproject/galaxy#12596]
**Describe the bug**
When running a workflow and results are sent to a new history, if you switch to the new history from the modal's 'switch to that history' button, the history will not populate without reloading the page.

**Galaxy Version and/or server at which you observed the bug**
21.09 and 21.05

**To Reproduce**
1. Run a workflow and output to new history
2. Switch to new history with the given option
3. Observe history

**Expected behavior**
Datasets from workflow run should appear in the history as it is run.

**Comment by mvdbeek** [comment]
I'll push this to the 22.01 milestone, this should be relatively simple to fix in the new history (assuming it doesn't already work).
This happens because if you immediately switch to the new history there are no jobs in the new history yet (because the invocation isn't scheduled yet and no jobs or outputs exist) and the history then does not start listening for updates. If you wait a little longer until the invocation summary displays the first scheduled step the history does update.

**Comment by dannon** [comment]
Confirmed this is working fine in the new history now, which is what we're targeting.
