### ISSUE TITLE
Building list of dataset pairs broken (due to missing datasets, difficult to understand cause)

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#12593]
**Describe the bug**
The pairing of datasets in the Create a collection of paired datasets dialog seems weirdly broken.
It truncates certain names, which then causes duplicates to be reported.

Also, the topmost, forward dataset is forgotten in the unpaired section upon pairing.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.09

![Screenshot from 2021-09-29 17-58-13](https://user-images.githubusercontent.com/4742081/135305490-9edecddf-74da-4612-bee3-50ab9ccf912e.png)

The screenshot covers both issues. The reported duplicates aren't real, but are caused by the last digit being dropped from the names.

**Additional context**
Discovered during 21.09 release testing.

**Comment by wm75** [comment]
To reproduce: this occurred with the fastqsanger.gz files from the .org DL at: https://usegalaxy.org/libraries/folders/Fc3884862c15f7b8d

**Comment by assuntad23** [comment]
I'm not seeing this issue on dev or on usegalaxy, which is running 21.09
Here's my history: https://usegalaxy.org/u/assunta_desanto/h/unnamed-history-3 
Here's a short screen cast

https://user-images.githubusercontent.com/26912553/135668749-f5087919-4bab-42cc-9edf-ce1bd4a023f5.mp4

:


Can you give me some more details on how you paired the datasets? Did you allow them to auto-pair or did you pair them yourselves? Did you clear the filters before pairing? 

While I didn't see this issue, I did see the remove extensions toggle doesn't seem to be working, so I think that ought to get fixed.

**Comment by wm75** [comment]
Issue solved. Thanks to @assuntad23 !
Explanation will follow here shortly.

**Comment by wm75** [comment]
This turned out to be caused by https://github.com/galaxyproject/training-material/pull/2810.
I did not notice that there was a dataset missing, which broke the pairing. Thanks @assuntad23 for taking a more careful look than I did.

It seems somewhat unfortunate that mispairing causes the whole interface to break like this, but it's probably not easy to improve and certainly not worth to be a 21.09 miletsone.

**Comment by mvdbeek** [comment]
It seems difficult to find the cause, and the error message seems misleading. We should keep this as an open bug, although I agree that we don't need to attach this to the 21.09 milestone.

**Comment by assuntad23** [comment]
Just to preserve my findings for future reference: 

When I ran it on my machine, I added the missing dataset. I was copying them from the Library and hardly noticed the mismatched pair.

According to @wm75, the auto-pairing on start up works correctly, but if you unpair all and pair again, it pairs them differently. This means the problem is probably somewhere in the auto-pair function, but I'm not sure how it auto-pairs differently each time, since the function should be the same. If it does not auto-pair differently, and in fact, will fail on initial auto-pair as well (a possibility, since the error doesn't appear until you try to build the collection). This is totally and completely just a data/user problem, and does not need to be fixed, imo.
