### ISSUE TITLE
Folder import for remote files freeze selection modal or crashes Galaxy when too large

### ISSUE THREAD

**Issue by astrovsky01** [galaxyproject/galaxy#12635]
When retrieving remote data from the remote file page, selecting a large enough folder will cause the modal to freeze, and, if large enough, crash the client. This is also made more likely since a) clicking the name of the folder doesn't open it as might be expected and as it functions on the first page of the remote files, but selects it, and b) the size of a folder is not shown to the user.

Based on this PR: https://github.com/galaxyproject/galaxy/pull/12310

**Galaxy Version and/or server at which you observed the bug**
21.09 on org

**To Reproduce**
1. Go to upload data
2. Select remote files
3. Select a large folder to upload.

**Expected behavior**
Folder is selected, or at least the modal continues to allow other functions as the selection is ongoing.

**Comment by mvdbeek** [comment]
Maybe one quick "fix" would be to not select an item by clicking, but to require that a user sets a checkmark.
@OlegZharkov can you take a look at this ?

**Comment by OlegZharkov** [comment]
>  selecting a large enough folder will cause the modal to freeze

Can you give me some rough numbers please, how many files did you try? It probably awaits for the server to respond with the folder structure. I should add a spinner for that.

> a) clicking the name of the folder doesn't open it as might be expected 

Yeah, that's true. It was like that and I thought it's intentional feature. I can pretty much fix it.

> it functions on the first page of the remote files, but selects it,

It should not be able to select root folders, I have a test for that. If it does, it's a bug. I will investigate

> the size of a folder is not shown to the user.

not supported by backend yet

Thanks a lot for reporting @astrovsky01. I will address it

**Comment by astrovsky01** [comment]
@OlegZharkov I tried several folders, and have discovered that it can take a second to actually freeze/crash. The modal can look useable and be navigable for several seconds to a minute before any issues crop up. I was using the public remote data list on org.

The size of the folder comment was more so to say that a user would not know that they are selecting a prohibitively large folder
