### ISSUE TITLE
Default tools in local installation

### ISSUE THREAD

**Issue by AdySan** [galaxyproject/galaxy#1273]
I see a decent set of tools available by default on usegalaxy.org. 

Is there any quick way to get the same list of tools on a local installation without adding them manually one by one?

**Comment by martenson** [comment]
There is no user facing way to 'mirror Main toolset' yet even though we have made some progress towards.

Your current best option is to use ansible scripts and have them install tools into your Galaxy through API.

Have a look at https://github.com/afgane/galaxy-tools-playbook & https://github.com/galaxyproject/ansible-galaxy-tools

The problem is already being tracked here: https://github.com/galaxyproject/galaxy/issues/1115 so I will give you some time to respond and then close this issue.

**Comment by AdySan** [comment]
Thanks, that worked great!
