### ISSUE TITLE
[form parameter] select, data_column, genomebuild, group_tag: "_fieldSelect"

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#12872]
This is an issue for tracking/assigning conversion of the backbone form input (found here:  https://github.com/galaxyproject/galaxy/blob/dev/client/src/components/Form/Elements/parameters.js) into a vue component.

For more details see https://github.com/galaxyproject/galaxy/issues/11076

**Comment by neoformit** [comment]
Just leaving this here as a minor issue to resolve during Vuefication. This is how the "genome build" select displays on `22.05` with one available option (it looks empty):

![image](https://user-images.githubusercontent.com/42562517/210664956-3b96225b-6ecf-4f4e-8c39-eaf193b71ec9.png)

On click:

![image](https://user-images.githubusercontent.com/42562517/210665113-9d9935c4-0803-44f8-9073-981bfb375b47.png)

**Comment by hujambo-dunia** [comment]
From `@assuntad23`:

Hey Michelle -- trying to trace what happened to the _fieldSelect PR.
I'm looking through the issues assigned to me and came across it then remembered that you were wroking it, but I didn't see it merged. I'm gonna re-assign the issue to you, since it looks like you got it all together, but then wanted to break it up. Then you can reference the issue to mark it when it's all done. 
https://github.com/galaxyproject/galaxy/issues/12872
