### ISSUE TITLE
Allow dynamic reordering of <repeat> blocks

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#1311]
@shiltemann requested this at GCC2014, and I'm re-raising the issue now; it would be really nice to have re-orderable repeat blocks, especially through a mechanism like drag and drop.

One of my students implemented a Circos wrapper akin to my JBrowse where you can drop in a few files, however the order they're added in is used as the order to display them in. If you spend 5 minutes configuring low level details of one repeat block and decide that it would be better in a different ordering, you're forced to recreate the entire repeat's structure.

**Comment by shiltemann** [comment]
@erasche oh wow, good memory :)

And yes, this would be hugely helpful. Even just the ability to insert a new repeat item anywhere in the repeat list rather than only at the end would already be great (and drag n drop reorder would be amazing). 

I spend a lot of time making huge iReports for users' pipelines only for them to tell me they would like to have something inserted at the front, and I cry a little inside at the prospect of having to move the whole thing over by one ;P (actually lately I've taken to hacking the workflow export format and reimporting, which is slightly less painful but still no fun)  

P.S. @erasche Circos wrapper, awesome, that's going to make a lot of my users (and me) very happy :)

**Comment by blankenberg** [comment]
Came to make a new issue, but just a bump to indicate continued interest for this pretty significant UI/UX issue. 

Also, we are currently resorting to hacking workflow export/import, as noted above.

**Comment by hexylena** [comment]
@lldelisle reported this also with the pyGenomeTracks, during EGD 2022.
