### ISSUE TITLE
render bioconductor xref as part of the tool form

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#13266]
It would be nice if we can add Bioconductor xref into the tool form and link to https://bioconductor.org/packages/release/bioc/html/amplican.html

Since it is a real DOI we could reuse the DOI code in Galaxy and also the DOI cache. In addition, we can maybe include a BioC logo?

`<xref type="bioconductor">10.18129/B9.bioc.amplican</xref>`

xref: https://github.com/galaxyproject/tools-iuc/pull/4358/

**Comment by csoneson** [comment]
If explicitly specifying the link target, the safest would be to link to https://bioconductor.org/packages/amplican/ rather than to the release landing page - I think this link should automatically point to the "right" version of a package (release if possible, devel if not yet in release, list of removed packages if deprecated).

**Comment by bgruening** [comment]
and already done, :-)

Danke @jmchilton
