### ISSUE TITLE
Explicit docker image caching

### ISSUE THREAD

**Issue by astrovsky01** [galaxyproject/galaxy#13327]
When using an explicit docker image in a tool, the default is currently to convert to singluarity with every run, no matter the size of the image. There is a mechanism for caching these containers, but it is off by default.

https://github.com/guerler/galaxy/blob/1833daf4d94d526787dbf57d3e48c8f7929b0f92/lib/galaxy/tool_util/deps/container_resolvers/explicit.py#L59

Would it be best to switch to on by default, or is there another mechanism that would work better to avoid the repeat copying of large files?

**Comment by bernt-matthias** [comment]
Hi @astrovsky .. in the current implementation the `explicit_singularity` and `cached_explicit_singularity` resolvers exclude each other. 

With the following config only `explicit_singularity` would be used

```
- type: explicit_singularity
- type: cached_explicit_singularity
```

and if ordered the other way round only `cached_explicit_singularity` would be used

```
- type: cached_explicit_singularity
- type: explicit_singularity
```

So having both in the default config makes no sense and we have to decide for one.

Since `cached_explicit_singularity` only works on systems where the compute node and the galaxy node share a file system the `explicit_singularity` resolver seems the more decent choice because should always work. 

How that admins will have less problems to configure this once we have a little bit better docs: https://github.com/galaxyproject/galaxy/pull/15614 .. 

Please reopen if you disagree :)
