### ISSUE TITLE
History search tips overlay unintuitive to clear

### ISSUE THREAD

**Issue by afgane** [galaxyproject/galaxy#13350]
**Describe the bug**
Clicking on the `?` icon in the history search bar opens a help box but the only way to close it is to click on the same `?` icon again.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.01 rc1
usegalaxy.org

**To Reproduce**
1. Click on the `?` icon in history search bar
2. Click anywhere else on the page, or hit Esc key but the help box does not clear

**Expected behavior**
The help box should clear more ways than using the `?` icon as a toggle. It's not intuitive and is slow to aim at the icon again.

**Screenshots**

https://user-images.githubusercontent.com/338642/153435880-1c100415-b56e-4e88-9383-6bf4e3fa20e1.mov

**Comment by davelopez** [comment]
Hi, this popup behavior was intentionally introduced as a *fix* for another issue, see details on https://github.com/galaxyproject/galaxy/pull/13058#issuecomment-993310069

I anticipated that this may be confusing for some users, but I couldn't find a better solution with my limited knowledge, and I consider the other issue even more annoying or frustrating since you cannot click the link inside the popup.

On the other hand, I think this old code will be replaced by the new history really soon™

**Comment by davelopez** [comment]
> Close as wontfix?

I don't know, maybe other fellow devs know a really quick fix for both issues? otherwise, it may not be worth the time :shrug:

**Comment by mvdbeek** [comment]
With https://github.com/galaxyproject/galaxy/pull/13390 I'm moving this to 22.05, we should then just make sure that this works correctly in the new history.

**Comment by guerler** [comment]
The new history shows the advanced filter panel instead of explaining the available options in a popup.
