### ISSUE TITLE
Workflow : Renaming datasets with input variable work with some tools but not others: 

### ISSUE THREAD

**Issue by Delphine-L** [galaxyproject/galaxy#13362]
**Describe the bug**
I am trying to rename outputs of a workflow by using input variables (see screenshots). I rename the output of `gfa to fasta` to "Hifiasm Primary Assembly" (A). Then in `Quast` and `Busco`, among others, I rename the datasets using the variable `#{in.inputs}` and `#{input}` respectively (screenshots B and C).  But when I run the workflow, it works for some like `Busco` (D)  but not for others like `Quast` (E).  

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: both usegalaxy.eu and usegalaxy.org (on 22.01)

**To Reproduce**
1. Run workflow :  https://usegalaxy.eu/u/delphine-l/w/trio-assembly-with-hifiasm 
2. On test data : https://usegalaxy.eu/u/delphine-l/h/test-dataset-renaming

**Expected behavior**
Maybe I am missing something I am doing wrong but I can't see why it doesn't work for some tools. 

**Screenshots**

![image](https://user-images.githubusercontent.com/11195061/153660391-62bb8844-cea0-45e3-95a8-ce112ecc9f05.png)

**Comment by mvdbeek** [comment]
I think the proper variable for quast is this:

<img width="342" alt="Screenshot 2023-05-30 at 12 50 23" src="https://github.com/galaxyproject/galaxy/assets/6804901/a08e627d-944a-4e22-9ac8-b0ec315045b1">

I suppose that's probably been fixed in a recent release (22.05 / 23.0) in the user interface ?
There's an additional backend issue that will be fixed in https://github.com/galaxyproject/galaxy/pull/15978

**Comment by mvdbeek** [comment]
Pretty sure that's fixed in https://github.com/galaxyproject/galaxy/pull/15978
