### ISSUE TITLE
Rule-based uploader continuity after clicking away

### ISSUE THREAD

**Issue by astrovsky01** [galaxyproject/galaxy#13382]
When using the uploader, clicking outside the modal will close it. With file upload, this is fine, but with rule-based uploading, this causes all progress made and rules set to be lost. Clicking away and reopening this will return the user to the pasted data, and require the user to 'build' and set the rules again. This should only close the modal, and not undo the rules, which should be cancelled via the 'cancel' button on the modal itself, otherwise someone could have many rules set, accidentally click away, and then have all of that work undone.

**Comment by dannon** [comment]
If keeping the state of that modal persistent is a significantly more involved issue, maybe a quick workaround would be to catch the exit and say "Are you sure you want to discard this plan" or something.

**Comment by astrovsky01** [comment]
I'd agree -- as long as there is some way to prevent the unintentional deletion from happening, I'd think it'd be fine

**Comment by assuntad23** [comment]
Fixed with #14076

Future work: when updating the modals to Vue, we could add a confirm dialog (instead of disallowing any clicks outside of hte modal) OR to permeate the rules even after clicking outside of the modal, we could put them in local storage (but if we're going to do that, we should move the SavedRuleSelector into the Database, instead of having both saved rules and started rules in local storage)

ShouldI leave this open or close it?

**Comment by dannon** [comment]
We'll leave it open but the current fix is fine for the release, just bumping milestone.

**Comment by dannon** [comment]
With the basic fix in place, let's just close this issue out with upload being rebuilt in the next few cycles.
