### ISSUE TITLE
[22.01] Problem with empty text parameters

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#13516]
**Describe the bug**

An empty text parameter gives an error/warning if left empty:

https://matrix-client.matrix.org/_matrix/media/r0/thumbnail/matrix.org/2022-03-10_CfNMCIaEMTcITlot?width=100&height=100&method=scale

This is cutadapt 3.5+galaxy1 on usegalaxy.org

Filling and emptying the parameter is a workaround.

Does not happen on usegalaxy.eu

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: probably 22.01 (guess usegalaxy.org already upgraded)

**To Reproduce**

1. Open cutadapt on usegalaxy.org
2. Choose a fastq 
3. Execute
4. Maybe the Read Modification section needs to be unfolded 

**Expected behavior**

No error or warning should appear.

**Comment by mvdbeek** [comment]
For some context:
> There's an interesting interplay of attributes for text params [Cristóbal Gallardo]() [mvdbeek (Marius van den Beek)]() and me been starting to discuss over in the release testing channel: https://matrix.to/#/!cHIlGjZMbOkigZioIQ:gitter.im/$ROmeQxDaWaUJpmDZ2rN0qu2pXiomagJYGoe51EI-6ZU?via=matrix.org&via=gitter.im
[You're invited to talk on Matrix](https://matrix.to/#/!cHIlGjZMbOkigZioIQ:gitter.im/$ROmeQxDaWaUJpmDZ2rN0qu2pXiomagJYGoe51EI-6ZU?via=matrix.org&via=gitter.im)[](https://matrix.to/#/!JLyNgmIlYnnCOwcFAQ:gitter.im/$PG-qRNWlIAiD45K7ilupxlhzqmN8oVAqoxJAZY1frBY?via=gitter.im&via=matrix.org)
You're invited to talk on Matrix
Essentially, the default for text params (like for other params) is non-optional, but only 22.01 enforces that. So if you want an optional text param you have to say optional="true".
An alternative, currently, is to provide a default value for the param. Since even after deleting that default value, their will still be "" left as the value this will de facto act as if optional was specified.
We might want to standardize this a bit?

**Comment by bernt-matthias** [comment]
OK. But why isn't the tool test picking this up?

**Comment by mvdbeek** [comment]
It's a client-side change, https://github.com/galaxyproject/galaxy/pull/13285

**Comment by bernt-matthias** [comment]
IUC has 956 parameter with `<param type="text" value="">` in 152 tools (>10% of the tools)...

**Comment by mvdbeek** [comment]
Is it really a problem ? You can

**Comment by bernt-matthias** [comment]
> Is it really a problem ? 

Unfortunately I think so. And the cutadapt example proves it since it still runs on usegalaxy.eu and fails on usegalaxy.org (also the workaround: entering something and then cleaning it again is quite odd .. because for the user nothing changed in the UI).

**Comment by nsoranzo** [comment]
On the other hand, we have loads of tools that had to use `<validator type="empty_field" />` because `optional="false"` (i.e. the default) for `text` parameters was not enforced.

**Comment by mvdbeek** [comment]
I think we'd still need the empty_field validator, since that also applies to `""`, which is a valid input (as opposed to `null`). Anyway, I will revert https://github.com/galaxyproject/galaxy/pull/13285 for now, it seems this is turning into a bigger issue.

**Comment by mvdbeek** [comment]
The cutadapt parameter in question is
`<param argument="--strip-suffix" label="Strip suffix" type="text" help="Remove this suffix from read names if present."/>`. If we did use `<param type="text" value="">` it would actually work "correctly", since we'd set `""` as the default value.

I don't know what the long-term fix should be, this seems like a big problem IMO.

**Comment by bernt-matthias** [comment]
> this seems like a big problem IMO

Indeed, this deserves a proper fix.

I think that a better error message and a visual distinction of no value and empty string in the UI might help.

Also handling of such parameters in tools tests should be handled the same way and the tools should be "fixed".

Maybe you can open a PR with the reverted commits, just to not forget about it.
