### ISSUE TITLE
configfile using filename results in bad placeholder value

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#13586]
When using `filename`, the configfile is placed within the root of the `working` directory as expected. But when attempting to use the `name`d placeholder, the path provided is under` job_directory/configs/filename` which does not exist. 

for e.g.:
`<configfile name="staging_script" filename="staging_script.py">`

`job_directory/working/staging_script.py` exists, but the value provided by `${staging_script}` (`job_directory/configs/staging_script.py`) does not exist.

This was found in release_22.01, but older releases may also be impacted.

**Comment by bernt-matthias** [comment]
My fix (https://github.com/galaxyproject/galaxy/pull/13602) would be to create the config file always as `job_directory/configs/TMPNAME` and let the cheetah variable point to it. If a filename is given an additional symlink pointing to `job_directory/configs/TMPNAME`  is created in workdir. 

Guess this was "broken" since at least 8 years.
