### ISSUE TITLE
Uploader can get stuck when uploading multiple files

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#13589]
**Describe the bug**
When uploading a lot of files e.g. 50, the queue can get stuck and throws a console error (see below). This is a new bug and possibly related to recent changes of the upload module.

**Galaxy Version and/or server at which you observed the bug**
In dev and on main.

**Screenshots**
![image](https://user-images.githubusercontent.com/2105447/159370517-819d03e6-2f5e-4fe3-8f48-876e0e8b1c1e.png)

**Comment by mvdbeek** [comment]
Please don't set this to released milestones @guerler. What commit are you on, I don't have anything that could cause this error on line 26 of uploadbox.js. The error also says that you lost network connectivity, so that is probably the reason, and we only need to improve the error handling for the upload modal.

It works fine on dev and usegalaxy.org for me. Anything else you can add so that we an reproduce this ?

**Comment by mvdbeek** [comment]
Still working for me. Do you always see the network error that you have in your screenshot above ? What browser is this ?

**Comment by guerler** [comment]
It's possible that this only occurs when using `sqlite`. Nevertheless I added a small fix which ensures that the server error contains details before passing it to the callback function.
