### ISSUE TITLE
Highlight inputs and outputs of a given dataset/collection in the history

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#13632]
Highlight inputs and outputs of a given dataset/collection (immediate neighbors in the invocation chain need to be highlighted). For example, if I mouse over #16 (see image below), #15 is highlighted as an input and #31 as output. It is possible that either inputs or outputs are out of the view in a large history. We need ideas on how to deal with this situation. One idea is to have “show inputs/outputs” button, that would shrink the entire history to those datasets only.

![image](https://user-images.githubusercontent.com/155398/160624599-ca068ea6-0693-47a5-b7ee-f8e48efdab19.png)

**Comment by bgruening** [comment]
Can we work here with advanced inputs? Long key-press (deep press down) will "pin" the dataset and hide all unrelated datasets behind an indicator (accordion style) and displays in and potentially outputs?

**Comment by dannon** [comment]
@bgruening That's a cool idea that'd be fun to try.  It looks super straightforward with something like https://www.npmjs.com/package/vue-directive-long-press

**Comment by bgruening** [comment]
Not sure if this image makes anything more clear, haha - but here it goes.

![IMG_20220403_202031](https://user-images.githubusercontent.com/469983/161442732-e4c7e5fd-5700-4dc2-b87d-50263f7dbd5a.jpg)

**Comment by bgruening** [comment]
@dannon https://github.com/galaxyproject/galaxy/issues/13663 could be an additional or alternative way to "pin" a dataset.

**Comment by mvdbeek** [comment]
I don't know how I got assigned to this. I did make another suggestion, which was to separate datasets visually by their job id / job summary id. That should be relatively straightforward, and maybe that can be done for the next release, but I have a lot of other things that are higher priority. If someone wants to work on this I could give some hints on the API portion of this.

**Comment by dannon** [comment]
@mvdbeek I thought you had expressed interest when we talked about this a while back, no worries -- we can figure out who can take this on at the weekly meeting.

**Comment by ahmedhamidawan** [comment]
The idea I have as a first step is to add a `DatasetActions` button i.e.: `Show Inputs/Outputs`. Upon clicking that, the history will show inputs and outputs (highlighted differently) for the specific dataset/collection. This functions as (sort of) a filter for now. You can see what the button would look like below:

https://user-images.githubusercontent.com/78516064/161844675-4733093f-d0a7-40dc-89f3-838729abf3ca.mov

For now, all the button does is just show the dataset with the exact same name. This is just to temporarily demonstrate how the button triggers a filter.

**Comment by ahmedhamidawan** [comment]
> I don't know how I got assigned to this. I did make another suggestion, which was to separate datasets visually by their job id / job summary id. That should be relatively straightforward, and maybe that can be done for the next release, but I have a lot of other things that are higher priority. If someone wants to work on this I could give some hints on the API portion of this.
> 
> It's a really cool idea though, so I'm unassigning myself in the hopes of finding someone motivated that wants to take a crack at this.

Hello @mvdbeek, I have currently set it up so that once I press a button for the dataset, it toggles to an input/output view, where for now only the selected dataset is highlighted but eventually, the inputs/outputs for the dataset will be highlighted in different colors:
![out](https://user-images.githubusercontent.com/78516064/163261068-bffe861f-ad06-4c41-8c09-4e29311d184d.gif)
I was wondering if you could help me identify the variable that actually indicates which dataset has the current dataset been derived from. For instance, for the dataset below:
![image](https://user-images.githubusercontent.com/78516064/163261311-d68e818d-2365-4474-9312-b2ebf1a0541b.png)
Would it be something like the `Job API ID` or one of the other variables or would it be something like the variables highlighted below?:
![Screen Shot 2022-04-13 at 4 07 52 PM](https://user-images.githubusercontent.com/78516064/163262173-f96dcd04-ae3f-44ae-8304-634c34f904a3.png)

**Comment by dannon** [comment]
@ahmedhamidawan Absolutely; which branch should I play with?

**Comment by ahmedhamidawan** [comment]
> @ahmedhamidawan Absolutely; which branch should I play with?

Oh my bad, I haven't pushed yet, I have a lot of experimental changes that affect other files because I have been trying to figure out how to get the inputs/outputs for a dataset. I was just talking about the screencast I posted in the comment above and whether I had the right idea there. I'll also be making a draft PR where you'd be able to access the branch.

**Comment by dannon** [comment]
@ahmedhamidawan No worries.  So for the screencast -- yeah, as a vehicle for testing and displaying inputs/outputs I think a separate view like that is useful as a first step and maybe even useful beyond.  I do think we want to make sure whatever gets implemented for this can be integrated into the primary history list as an on-hover highlight (so, not requiring any clicks/expansion at all), but I think that could come as a second pass once you sort out how to get all the data you need.

**Comment by ahmedhamidawan** [comment]
i have added functionality for identifying Inputs, will be working on Outputs
https://user-images.githubusercontent.com/78516064/163477044-ebc09684-b686-4174-8e9c-845e1f56fa8b.mov

**Comment by mvdbeek** [comment]
> Would it be something like the `Job API ID` or one of the other variables or would it be something like the variables highlighted below?:

That's the id of the job that currently ran, and the job does contain the inputs and outputs.
I guess the best way to handle this  (currently, but we can work on this!) wouldbe a GET to /api/jobs/${this.jobId}/parameters_display, which would give you:
```
{"parameters": [{"text": "Concatenate Dataset", "depth": 1, "value": [{"src": "hda", "id": "3e2765013396bd8f", "hid": 2, "name": "Pasted Entry"}]}], "has_parameter_errors": false, "outputs": {"out_file1": [{"label": "Concatenate datasets", "value": {"src": "hda", "id": "dfbbe99baaf101de"}}]}}
```

The issue here is that this only works with job ids, which only works with simple datasets. I think that's OK for a start though, we can augment the API to also work with the equivalent for mapped over collection jobs. The shape of the API response is also not ideal, you'd basically have to descend into into each parameter to get the input datasets. It's easier for the outputs though.

**Comment by guerler** [comment]
Question, can we instead expand the history contents filter so that entering e.g. `job=...` into the filter text will show all input datasets of that job?

**Comment by mvdbeek** [comment]
it's a good suggestion too, we'd have to play with this and see what is mor useful. i could imagine that it might be nice to see the other datasets that aren't selected as well, but the search means you don't have to manage scrolling to items that might not be loaded yet.

**Comment by ahmedhamidawan** [comment]
> Question, can we instead expand the history contents filter so that entering e.g. `job=...` into the filter text will show all input datasets of that job?

Yes I can definitely work on doing that too, I actually started by using a history filter instead of highlighting the datasets.

**Comment by guerler** [comment]
With the most recent changes to #13740 it seems that instant highlighting works promising. I don't think, we'll need to add an actual job filter for now, and can instead focus on the instant highlighting strategy only.

**Comment by bernt-matthias** [comment]
Was just thinking that it might be nice to indicate which dataset is currently shown .. maybe also by some kind of hightlight?

**Comment by bernt-matthias** [comment]
> Was just thinking that it might be nice to indicate which dataset is currently shown .. maybe also by some kind of hightlight?

Ahh. actually it is .. in a slightly darker green
