### ISSUE TITLE
Remove build artifacts from repo and auto-build in deployments 

### ISSUE THREAD

**Issue by carlfeberhard** [galaxyproject/galaxy#1371]
- [ ] remove build artifacts
  - [ ] static/scripts (and bundled)
  - [ ] static/maps
  - [ ] static/style (no rush here I think)
- [ ] create `make client` also call a `client-clean` subtask that removes the above directories
- [ ] ~~auto-build in deployments~~

**Comment by martenson** [comment]
implying Galaxy dependency on node/npm, right?

**Comment by carlfeberhard** [comment]
Yep - via wheels, nodeenv, whatever-thingamabob.

**Comment by jmchilton** [comment]
Yes, this is going to be disruptive but I think it really needs to happen. @natefoo had mentioned nightly builds of Galaxy available via pip, that would help. As would perhaps a nightly build of docker-galaxy-stable.

**Comment by natefoo** [comment]
Yeah, I'm in favor of this. We'll figure out how to provide npm (if necessary).

**Comment by carlfeberhard** [comment]
Some possibilities:
http://ekalinin.github.io/nodeenv/
http://www.jayway.com/2013/05/19/auto-install-node-js-and-npm-from-makefile/ and https://github.com/hugojosefson/find-node-or-install

**Comment by nsoranzo** [comment]
:+1:

**Comment by carlfeberhard** [comment]
Also a possibility:
(keeping) https://github.com/creationix/nvm/blob/master/install.sh (in our repo)

@natefoo what's the best way forward for me to begin working on this without damaging any solutions that may be better for you and deployers? IOW, if you're planning wheels, is there anything I should avoid or include to make that possible in the longer term?

**Comment by natefoo** [comment]
How close are you to committing anything that would require npm for anyone running dev?

**Comment by carlfeberhard** [comment]
Still exploring - just trying to coordinate before hand.

**Comment by natefoo** [comment]
Okay. I am not sure what the best way to provide node will be (if we do it at all or just provide guidance on how to do it in more traditional ways), but I don't think there'd be anything you would do that would make any particular method more difficult. As long as the built artifacts can be housed outside the galaxy root directory via config options, we should be good.

**Comment by carlfeberhard** [comment]
I'm also going to ask something that I think has been implicitly skipped: Is there a reason to make installation of node/npm automatic? Can't we simply state that it's a dependency for installing and running Galaxy?

I'm not saying I'm against auto-installing it - it's just that I have not seen many other sites that need to do this and it feels like another odd thing about Galaxy.

EDIT: didn't see your reply when writing the above, Nate

**Comment by natefoo** [comment]
I think the answer is not necessarily "yes, we need to automatically install it." That said, there are a few reasons why historically Galaxy has done this sort of thing:
1. Some of our python dependencies (e.g. numpy) take a long time to compile and others will outright fail to compile without having non-default packages installed on your OS.
2. Galaxy has a history of making "installation" as foolproof as possible since we have always wanted to make it (hopefully) trivial for non-technical (or command line-adverse) people to run Galaxy. This is especially important for people who simply want to develop a tool wrapper but don't intend to work on the framework at all.
3. Not all deployers have root access or sysadmins amenable to installing arbitrary dependencies for scientific applications, and for these we typically try to make unprivileged installation easy too.

For seasoned developers, a dependency on npm/node is probably not a problem and we want to make sure any automated installation stuff doesn't get in the way (as eggs often did). Likewise, deployers of production servers may well prefer to have their own (or installed from apt/yum) node/npm installs.

The answer for those less advanced tool developers or deployers may well be providing automated nightly and release tarballs and packages that include all the built artifacts, rather than bootstrapping node/npm for them or depending on it.

**Comment by jmchilton** [comment]
I definitely think we should just install npm if it is not there - it is so easy to do and so convenient. We have a common_startup shell script that does a bunch of stuff - it can check for npm and install it if it is not there, same for grunt, etc....

That said - two of the primary use cases that drove Galaxy to want dead simple to use source code are 1) serving tool developers and 2) serving bioinformaticians running personal instances. In 2016 - (1) is better served by `brew install planemo` and (2) is better served by Kitematic -> galaxy-docker-stable. People who should be obtaining the "dev" branch of Galaxy is probably restricted just to developers of the core code base.

**Comment by natefoo** [comment]
npm is easy, node is not nearly as easy, is it?

The other solutions you list have additional dependencies. Want to install planemo? Ok, first install XCode, then brew. Want to run a local stable server? Download kitematic or setup docker on your linux box, interact via docker rather than a local process. While these are not difficult, it's still not the "clone and start" we had before and both require administrative privileges.

**Comment by carlfeberhard** [comment]
> npm is easy, node is not nearly as easy, is it?

In my (very limited*) experience, it is not crippling and nvm has (for me) mitigated a lot of the pain of versions, etc. It may also be that reports of difficulties are due to the recent re-combination of the nodejs project and the splinter iojs. I would think things will get more stable from here out.

*edit: IOW, I have not attempted installs across many systems

That said, it (node/npm installation) seems like something more apt to put in the makefile since we're using that, rather than `common_startup.sh`? I'm not sure why we'd try to do it there?

**Comment by jmchilton** [comment]
I'll admit for something like `make client` to just work - it makes more sense in the `Makefile` and certainly it is easier to implement there. But if we want `run.sh` and `run_tests.sh` to "just work" out of the box, I'd move it into common_startup.sh. I don't feel strongly about this though. Also, with planemo and pulsar - the `Makefile` is the documented and encouraged way to run tests - so that is possibility to - we can have a target or two for `run.sh` and 40 targets for `run_tests.sh` - I'd be totally fine with that.

**Comment by natefoo** [comment]
I'm not fond of `run.sh`, perfectly happy with moving this to make.

**Comment by jmchilton** [comment]
Also... @natefoo regardless of how easy or not they are to get going - people running local instances should be using docker and people building tools should be using planemo. People shouldn't be using -dev for these things. Also all you need for planemo is pip - brew is not required. I think it is easier to get going with planemo on pip then galaxy-central on hg :).

**Comment by jxtx** [comment]
Feels like this should wait until we have actual galaxy packages and can do the build at packaging time. Folks actually hacking on galaxy itself can use dev and install npm, etc themseleves.

**Comment by jxtx** [comment]
> people running local instances should be using docker

This is just not realistic. Many people run local instances on systems where they can't run docker (old kernel, not privileged access). It will be years before we can really say docker only.

**Comment by natefoo** [comment]
Many, many sysadmins are also opposed to docker. We can push it all we want but it cannot be the only deployment method. Many (most?) deployers are likely to prefer packages.

**Comment by carlfeberhard** [comment]
Ok, well - it appears as though the two subtasks in this issue's titles are starting to become clearer and diverge. I certainly didn't mean to push any of this onto your plate, Nate.

@natefoo @jxtx Let me know what you decide in terms of auto-building or if I'm needed on that at all.

For the 'remove build artifacts from repo', I've updated the checklist of the issue.

**Comment by carlfeberhard** [comment]
@natefoo Anything I can do on this to help?

**Comment by natefoo** [comment]
Packages should be done by the GCC.

**Comment by martenson** [comment]
all the tasks (except of `static/style` I think) have been done and we have a clear path for 18.05 how to handle this
