### ISSUE TITLE
Beta history: when unselecting an item which not rendered before selecting all, new rendered items unexpectedly will be unselected

### ISSUE THREAD

**Issue by itisAliRH** [galaxyproject/galaxy#13736]
**Describe the bug**
By unselecting an item which not rendered before selecting all, new rendered items unexpectedly will be unselected, and selected counts will change by unselecting any item.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: `22.05`
Commit: 06a041fa0670d007f9ad3e8ab22b13bd7a95cc8a

**To Reproduce**
1. Watch the video below

**Expected behavior**
Should not unselect others by unselecting one item.

**Screenshots**

https://user-images.githubusercontent.com/8046843/163676903-ac53db3f-e216-48af-93ba-b6eb1f2753de.mp4

**Comment by davelopez** [comment]
Hi @itisAliRH, this behavior is by design, see https://github.com/galaxyproject/galaxy/pull/13555#issuecomment-1085966806 and the following comment for details.

I agree that, unfortunately, it may be confusing for the user, but there is no easy way to overcome this since you will need to keep track of 'negative selection' when you have a query selection in place.

This same behavior is what Gmail does when you select *all* emails in your inbox and there are more than the page size.
But if someone has a nice idea or way around this it will be awesome :)

**Comment by itisAliRH** [comment]
@davelopez Hi :) Thanks for the comment. Gmail shows only 50 emails per page, and in my opinion, users can understand that every page has its own selection status even if the page changes and when selecting all, it asks for select in all emails on all pages (current query) or only this page. But we don't have pages here, and users are confused about what happened when scrolling down. My suggestion is that when using select all, only select shown items, then show the same prompt as Gmail does to the user and ask them if they want select everything or not.

**Comment by davelopez** [comment]
> My suggestion is that when using select all, only select shown items, then show the same prompt as Gmail does to the user and ask them if they want select everything or not.

That was kind of the original solution, but event selecting the `shown items` is something relative :sweat_smile: it could mean only the items currently visible for the user or the items loaded in the cache? that's why we simplified to `Select all` means query selection.

But this is a good one for a bit of discussion in the meeting :wink:

**Comment by davelopez** [comment]
Is this a good candidate for using `popper.js` like in the new Tours https://github.com/galaxyproject/galaxy/pull/13778 but for making the user aware of how the selection changed from *all* to *just what is already loaded*?

Or maybe this https://atomiks.github.io/tippyjs/ which is based on `popper.js`?

**Comment by dannon** [comment]
Maybe something less intrusive, like an info ribbon that pops out at the top -- something like this?
![image](https://user-images.githubusercontent.com/155398/165807786-a8f41652-fa5e-496c-bcbb-f51693ec5f1d.png)

Or, maybe, we lean on toasts more?

**Comment by davelopez** [comment]
Thanks! Yeah I think that is good enough and way less intrusive, I just got excited with the cool Tours :laughing:

**Comment by davelopez** [comment]
After a couple of tries, I finally went the `Toast` route with this in #13850
Adding a new alert inside the History panel seemed a bit more intrusive (from the code perspective). 
I'm happy to try alternatives if this is not looking good enough :)

**Comment by mvdbeek** [comment]
A slot for custom content in the history panel shouldn't be considered intrusive but a necessity IMO. I think that'd be a much nicer experience than toast

**Comment by dannon** [comment]
Agreed; maybe the ribbon I proposed before just needs an animation to make it feel better?

**Comment by davelopez** [comment]
Thanks! I'll try an auto-dismissible alert using slots :+1:

**Comment by davelopez** [comment]
Is this something more desirable?
![notify-query-break-2](https://user-images.githubusercontent.com/46503462/166489379-a3e4a0aa-c1f2-4cbb-bce3-5e58c4ffb5fd.gif)
