### ISSUE TITLE
Beta History: filter applied on summary counts doesn't take into account multiple dataset states

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#13866]
Reported by @guerler

> While testing I noticed that the history can become corrupted after a bulk operation. For this I executed a large bulk op and then clicked on the filter selection, while the processing was ongoing:

https://user-images.githubusercontent.com/2105447/166716715-e3c7e674-6756-4b7c-83c5-3a682722ce3e.mov

**Comment by davelopez** [comment]
Ok, I've reproduced this with just one dataset.

It seems to be unrelated to the bulk operations, looks more like an incoherence in the filtering and the dataset status.

![filter-issue](https://user-images.githubusercontent.com/46503462/166901837-5b971c16-4979-429e-b222-e007b8c34740.gif)

So, if we `delete` **and** `hide` a dataset the filter applied when clicking the summary counts icons simply does not match the state of the dataset.

I guess we just need to apply a *smarter* filter query.

**Comment by davelopez** [comment]
@ahmedhamidawan do you want to take a look at it? otherwise, I can :)

Or we can discuss in the next UI/UX meeting what's the best approach to deal with multiple dataset states for those counts.

**Comment by dannon** [comment]
Backing up a step; I love how the new counts look but how widely used are hidden datasets and when is it actually useful to 1) have that information presented as separate counts, and 2) click the counter to see `only-hidden` vs `only-deleted`?  Maybe we just combine those two icons to one `inactive` (hidden or deleted) icon for the counters?

Users could still use the advanced filtering to find only hidden, only deleted, etc.

**Comment by ahmedhamidawan** [comment]
> Another thought, and I seem to recall this from years ago discussing when to hide/delete/purge, is that maybe `deleted` just supersedes hidden for the purposes of that count. So, you'd have three numbers -- active, deleted, and hidden-but-not-deleted.

I think this might be the best option at least when it comes to the filtering summary count buttons:
- active: `deleted=false visible=true` (no `filterText`)
- deleted: `deleted=true visible=true`
- hidden-but-not-deleted: `deleted=false visible=false`

This way, we don't account for `deleted=true visible=false`, but for that: 
- Do we make a further change to items so that whenever you deleted something, it was always set to `visible=true`, and the user was denied the option to ever hide a deleted item? (i.e.: `deleted=true visible=false` is never allowed)
- Or do we just not do anything for the summary count buttons and leave it up for the user to find such a case (`deleted=true visible=false`) through the `filterText` or advanced options themselves?

**Comment by ahmedhamidawan** [comment]
> I think deleted should be just `deleted=true` (i.e. `visible` any). Not sure if that makes things easier or harder :)

So, leave it (the `deleted` summary count) as is? i.e.: `deleted=true` but that assumes `visible=true`. I don't think we have an option to do `visible=true || visible=false`
