### ISSUE TITLE
storage cant be cleaned totally

### ISSUE THREAD

**Issue by Naibin** [galaxyproject/galaxy#13942]
**storage can't be cleaned totally**

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version:{"version_major":"22.05","version_minor":"dev0"}
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**To Reproduce**
1. Go to '/storage'
2. Click on 'free up storage.'
4. See  'No items to clear' but still 482M data occupied.

**Expected behavior**
expected there will be no spaces in use 
**Screenshots**

![image](https://user-images.githubusercontent.com/7318522/169433722-fbb126c7-2c40-4c8e-8219-c6aca550d155.png)

**Additional context**

**Comment by davelopez** [comment]
Hi @Naibin! 
The `Deleted datasets` box will show those datasets that you already marked as *deleted* and are ready to be *permanently deleted*, please note that just deleting datasets is like moving them to the 'recycle bin' so you can recover them if needed, that's why they still take space in your account. To free the space you need to permanently delete them and that is was this utility is about.

Can you try to delete datasets that you don't want in any of your histories and then use this tool to see if those datasets show up for *permanently deletion* in that box?

**Comment by Naibin** [comment]
> Hi @Naibin! The `Deleted datasets` box will show those datasets that you already marked as _deleted_ and are ready to be _permanently deleted_, please note that just deleting datasets is like moving them to the 'recycle bin' so you can recover them if needed, that's why they still take space in your account. To free the space you need to permanently delete them and that is what this utility is about.
> 
> Can you try to delete datasets that you don't want in any of your histories and then use this tool to see if those datasets show up for _permanently deletion_ in that box?

Hi David,
As you can see, I set up my own Galaxy(the latest platform using gunicorn).

To find the right answer, I logged in as a general user and tried to set up 2 histories of dataset.   I entered to  /histories/list, showing as in the picture:

![1352f96b8e0f87bc821fb6ac6111ae0](https://user-images.githubusercontent.com/7318522/169968422-2ec1beab-78d1-4c9c-965d-44cfa47fcc33.png)

So everything is ok now.
The main reason the dataset looks like cant be deleted permenately (some spaces still be occupied), is probably  because I forget to delete another  unamed-history(together with the dataset ).  
I am totally new to the Galaxy project.  Your advice reaally help me a lot to find the reason why.
I appreciate for your kind help,
Best

**Comment by bgruening** [comment]
Thanks a lot for your feedback @Naibin! Keep the questions coming! Also feel free to join us at Matrix: https://matrix.to/#/#galaxyproject:matrix.org
