### ISSUE TITLE
[release-testing] Glitch with switching histories in the new history

### ISSUE THREAD

**Issue by simonbray** [galaxyproject/galaxy#14097]
If I switch from history 1 to history 2, then refresh the page, history 1 seems to be loaded first and is displayed for a few seconds, before disappearing; then history 2 is loaded, as expected.

I cannot reproduce this every time, but I've seen it on multiple refreshes. @natefoo also reported something very similar: 

> On Main, I just (while logged in and on a non-empty history) created a new history with the + button, clicked the pencil to rename it, clicked into the name box to start typing, and then just before I typed anything, the history was replaced by the previous history.

**Comment by guerler** [comment]
Thank you for reporting this. Can you try to capture it in a screencast?

It might be related to: https://github.com/galaxyproject/galaxy/blob/dev/client/src/store/historyStore/historyStore.js#L157 but I cannot reproduce the issue locally yet, maybe because the race conditions are met in local tests.

**Comment by simonbray** [comment]
Hi @guerler, see below. I switch from history 2 to 1, wait for history 1 to finish loading, then refresh. This was recorded on ORG in Firefox.
https://user-images.githubusercontent.com/32272674/174435797-6c94c024-38fe-4d2f-b468-57be5877ddd7.mp4
