### ISSUE TITLE
On Dataset Libraries Page, Search feature frozen on zero results

### ISSUE THREAD

**Issue by hujambo-dunia** [galaxyproject/galaxy#14180]
**Describe the bug**
On the "Shared Data" >> "Dataset Libraries" Page, the Search input field results in "Loading..." icon spinning for 30+ seconds.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.05 on https://usegalaxy.org/libraries

**To Reproduce**
1. Go to https://usegalaxy.org/libraries
2. Click on "2019_nCoV" (first item in list for US-version) >> "Sequencing datasets" >> "ILLUMINA"
3. In Search input field, type: sff
4. See "Loading..." for 30+ seconds

**Expected behavior**
I would expect that if there were no results returned, it would stop the "Loading..." from appearing and just saying something simple like "no results"

**Screenshots**
![Greenshot 2022-06-23 13 35 14](https://user-images.githubusercontent.com/3672779/175361501-42eb88df-6673-4fbb-9a8c-fd8c91f4ad9c.png)

**Comment by dannon** [comment]
Okay, I spent more time debugging and, while it's very slow (1.2 minutes), it does eventually finish and update correctly for me.  The stacktrace you have in your screenshot is because, I think, you clicked on "Libraries" while that request was still loading, leaving the component in a state of uncertainty.  Is that correct?

**Comment by davelopez** [comment]
I'm going to investigate why the request takes so long...

**Comment by dannon** [comment]
@davelopez Thank you!
