### ISSUE TITLE
Tagging component in history panel difficult to use

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#14273]
**Describe the bug**
Took me several minutes to find out that the "Save" button doesn't save your currently entered tag, neither does the check mark. The solution is to press enter **and** then save... maybe it's just me, but I found this difficult to figure out.

**Galaxy Version and/or server at which you observed the bug**
22.05

**Expected behavior**
Pending tags should be saved when clicking on Save

**Screenshots**
![Screenshot 2022-07-06 at 17 16 59](https://user-images.githubusercontent.com/6804901/177585185-aa437a13-a57e-4e10-94e5-3ab3a406e2fe.png)

**Additional context**

**Comment by wm75** [comment]
Yes, I was struggling with this, too.

To add to this, I think the whole history metadata editing could use some simplification/unification. Currently when you press the history pencil icon:

- the box for entering the new history name is prefilled with the old name even if that name is Unnamed History so you have to delete it first
- the box for entering annotations, in contrast, displays instructions text that disappears on typing
- to save a new name for the history hitting enter is enough, to save annotations you need to press Save, and for tags @mvdbeek described the procedure.

**Comment by dannon** [comment]
@wm75 Thanks for the extra feedback here.  I tweaked some of this in https://github.com/galaxyproject/galaxy/pull/14171/, but maybe there's another iteration I can do.

The reason for the placeholder in one spot and not the other is simply that histories do not have an annotation by default, but they do always have a name (if a poor one).  One possible idea is to, if the name is "Unnamed History", preselect the text so you can just go right ahead typing?  Or, do you think if it's "Unnamed History", we should display that as a placeholder instead?  That option feels a bit wrong to me since the value *is* set, though.

History names can only be a single line, and since this is the most common edit here I added save-on-enter-key.  We can't really do save-on-enter (without a confusing shift+enter to newline, etc) for the multiline box here.

I'm definitely fixing the tag handling.  It should block save if invalid, and should save a valid entered tag on parent interface save too.

**Comment by dannon** [comment]
@ElectronicBlueberry is making a pass swapping this to a new component that'll handle this all much more gracefully.
