### ISSUE TITLE
small tool form improvements 

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#14453]
The typical tool form looks like that:

![grafik](https://user-images.githubusercontent.com/469983/184608882-e0052f84-83ce-4143-8b03-3f008312be74.png)

Some small enhancements that we could discuss:

* [ ] the separation between the tool parameters and the additional parameters is not clear, e.g. add a line before the "email notification"; keep in mind that we also have optionally the [job_resources](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/config/sample/job_resource_params_conf.xml.sample)
* [ ] move/copy the execution button to the top; Especially in large tools and when you rerun a tool it will enhance the UI if the button is easier accessible
* [ ] Make the top bar of the tool form (tool name, version) etc stick on the page and scroll the tool form below the bar; in combination with the second point, this would mean the execute button is always visible and accessible
* [ ] https://github.com/galaxyproject/galaxy/issues/14460#issuecomment-1216350630

**Comment by bgruening** [comment]
also adding https://github.com/galaxyproject/galaxy/issues/14460#issuecomment-1216350630

**Comment by ElectronicBlueberry** [comment]
I've modified to tool form to address some of these issues, and would like some feedback on these changes.
This is what the tool form currently looks like in my branch:

![Screen Shot 2022-08-23 at 13 11 21](https://user-images.githubusercontent.com/44241786/186146818-fb69ec88-fdef-4ca4-8c69-2ff620ce49a4.png)

## Sticky Title-Bar and Execute Button

Both the title-bar and the `Execute` button are sticky, meaning they follow the scroll when not in view, and otherwise take up space like normal elements.
I moved the `Execute` button to the bottom, instead of the top, as I couldn't find a good place for it in the top bar.

To make these elements more visible when scrolling through the form, I gave them both a slight shadow. I am unsure about this, as there is currently nothing visually similar in galaxy that I'm aware of.

| Title-Bar when scrolling |
| ------------------------------- |
| ![Screen Shot 2022-08-23 at 13 13 02](https://user-images.githubusercontent.com/44241786/186150516-0308facb-4a7b-4bee-b5f8-02e8e53ff81b.png) |

## Sections

To separate the tool parameters and additional parameters I added titled sections. These sections also use semantic tags, which makes them more accessible.

| Semantic Heading Elements |
| ---------------- |
| ![semantic_tags](https://user-images.githubusercontent.com/44241786/186151234-3ee33ea4-3249-4eb8-a6f7-8e7619ffb609.png) |

## Priority Break-Points

I've added priority break points to the three text sections of the title bar (Title, Description, Version Info). This makes it easier to read when any of these texts get too long.

| Break Points marked in Red | 
| ----- |
| ![priority_break_points](https://user-images.githubusercontent.com/44241786/186152149-a9817c6c-c82f-4349-8d43-951a47766b90.png) |

| Before | After |
| --------- | -------|
| ![Screen Shot 2022-08-23 at 13 14 45](https://user-images.githubusercontent.com/44241786/186152298-ae5aec34-ca47-4277-b03d-4d5fe76ddb44.png) | ![Screen Shot 2022-08-23 at 13 13 46](https://user-images.githubusercontent.com/44241786/186152328-b7f8efb8-7d4c-48ed-b9e2-d504855fe59b.png) |

**Comment by bgruening** [comment]
Some small ideas that we could try.

* does centering the "tool parameter" and "additional options" work better
* if the form scrolls under the header, can we make the form really disapeear under the header? Currently, you can still the form above the header which looks confusing and distracting.
* I don't think the execute button needs to be at the button, we could also make it on top - or in addition on top.

Looking at my Desktop, we could try something like that maybe?

![grafik](https://user-images.githubusercontent.com/469983/186272468-0d391534-9686-4bc7-9c9c-b52b82f86198.png)

**Comment by dannon** [comment]
I like the section and break point changes; this looks great.  I think they're fine left-aligned, too, as opposed to centered -- that's going to look weird on wider screens.

I think floating the execute at the bottom right is problematic.   It's going to be on top of parameters, or, like in your example down below the help text after someone would expect to find it.  If we really do want to take it out of the flow of the page (which I'm still not sure is a great idea), then pushing this into the title bar would be preferable.

As you point out, I don't think any of this needs shadows  -- it's not a design tool we've used anywhere else in the application and I think it looks out of place here.   I don't think we'll need it to convey how the form works, either, especially if we redesign the tool form header to use the full width instead of this padded portal view.

**Comment by guerler** [comment]
I have similar concerns regarding the shadow, as of right now we do not use shadows anywhere in the UI except for the tour and window manager boxes. I would suggest to try to avoid them by using maybe borders e.g. as done in the workflow run form.

**Comment by ElectronicBlueberry** [comment]
This is what I have so far:

[Screencast from 08-25-2022 02:58:59 PM.webm](https://user-images.githubusercontent.com/44241786/186673678-ba4c8167-1260-4330-abfc-e9f0a615a94d.webm)

I removed the shadow, hid the elements above the bar, moved the button back to below the tool form, and added a second button to the bar. I also removed the button morphing.

I also played around with changing the buttons text, so it can be shortened in the bar. I'm thinking this is likely not a change we can keep, as the buttons name might be too established.
However "Execute" dosen't fit in the bar on non-fullscreen windows. I've also tried adding a icon-only button, but the checkmark is not very telling of the buttons functionality, and might be confusing. I would appreciate some suggestions on this issue.

**Comment by nsoranzo** [comment]
LGTM! I'd suggest to replace the checkmark icon with the play one, which we also use to run workflows in `/workflows/list`

**Comment by guerler** [comment]
Yes, having a button at the top looks good to me too and it seems to be minimally invasive. Both buttons should have the same title and icon. Why has the morphing of buttons been removed?

**Comment by ElectronicBlueberry** [comment]
The morphing was removed because the text change made the button grow wider by quite a bit, pushing other elements around.

I also don't feel like the morphing conveys much new information in addition to the loading icon and title card.

**Comment by guerler** [comment]
It conveys the information that the request has been send, and instructs the user to `please wait` (the button color change to info is also helpful, also the button is at that stage blocked, this is helpful since some job submissions might take quite awhile and this is the only ui change the user sees until the server responds.

Regarding the second run button at the top maybe we could just use the 'play' icon.

**Comment by ElectronicBlueberry** [comment]
The video didn't show it clearly, but the "please wait" text, the color change, and the button being disabled are all still present. I only changed the buttons text morphing.

I made another video with a break-point set in the back-end:

[Screencast from 08-25-2022 06:12:18 PM.webm](https://user-images.githubusercontent.com/44241786/186716662-eaf15dc6-1cc2-45c1-b6cc-780636cbd346.webm)

(unfortunately recording my mouse position does not seem to work)

**Comment by guerler** [comment]
Using tooltip for this looks a little bit strange to me, I don't think we do it anywhere else in the UI. I would suggest to just change the pre click label of the bottom button maybe to "Run Tool" and leave the rest as is for now. We should focus on the top-bar which I think looks good.

**Comment by jennaj** [comment]
If this is done, we will lose the last place where the displayed full tool name and version can be copied as text out of the UI.

We lost the direct-copy-name functionality out of the tool menu a few years ago. 

Could we add to the Options menu? Capture exactly what is displayed so help users can match things up visually. Tool IDs and tool links are too cryptic IMO for many communications -- and point to a specific server. I copy/paste out tool versions into tags constantly. The GTN uses unlinked tool names in tutorials. 

1. Copy tool name
2. Copy tool version

This isn't the only Gui-fied text has been or might be. There is major practical utility in having access to just copy/paste from anywhere (admin panel is full of those and have known pain points). Until we have a larger solution for that (add a "copy label" to associated menus?) -- losing the ability to copy/paste out the tool name + version would be _immediately_ painful. Maybe we can break that out?
