### ISSUE TITLE
History Dataset operations hover styles are inconsistent

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#14487]
**Describe the bug**
When hovering over dataset operations such as to display or edit dataset attributes the button is not highlighted properly. However when hovering over the delete operation the button highlights correctly.

**Galaxy Version and/or server at which you observed the bug**
In current dev.

**To Reproduce**
1. Hover over the delete operation for history datasets
2. Notice how the button is highlighted
3. Hover over other operations such as view or edit
4. Notice how the button is not highlighted

**Expected behavior**
Assuming that all buttons should highlight consistently.

**Screenshots**
![image](https://user-images.githubusercontent.com/2105447/185646833-4c8fc111-b24e-40ee-82ec-9156b3d35b1f.png)

**Comment by ElectronicBlueberry** [comment]
This is caused by the `href` attributes, which some of the buttons have. Bootstrap Vue buttons with href attributes are rendered as links, rather than buttons.
I can't find any apparent reason for these attributes, and removing them does not seem to have any impact. I'm guessing accessibility reasons, but would like someone to confirm.

If they are required, a css override would also do the trick.

**Comment by mvdbeek** [comment]
I think they were added to support copying links with a right-click (https://github.com/galaxyproject/galaxy/pull/14325). I think we could just backport https://github.com/galaxyproject/galaxy/pull/14222

**Comment by guerler** [comment]
Thank you, #14495, looks nice and works well on chrome and ff. Only Safari still shows a grey background when hovering e.g. over the delete option. It might be due to style differences between button&anchor elements.
