### ISSUE TITLE
No batch mode available for <param type="data_collection" />

### ISSUE THREAD

**Issue by yhoogstrate** [galaxyproject/galaxy#1466]
It is not possible to select multiple pairs (e.g. pairs of fastqfiles) for running a batch mode analysis:
![screenshot from 2016-01-11 11-38-51](https://cloud.githubusercontent.com/assets/2264697/12231663/8e66fc9c-b859-11e5-82a1-5c7e04dcd2e8.png)

**Comment by jmchilton** [comment]
Yes - this was an intentional decision by @guerler with the new tool form. Lets imagine you have a `<param type="data_collection" collection_type="paired"...` - previously paired datasets and lists of paired datasets would be in different drop downs to indicate one is going to do a mapping operation and one is going to just run a normal job. They all just appear in the same drop down now.

Are you asking about mapping like this - or do you really have a bunch or lists or pairs and you would like to select a bunch of them. This operation was never available and it seemed to me like in most cases if people were using collections they'd have nested collections instead of multiple collections.

**Comment by yhoogstrate** [comment]
```
do you really have a bunch or lists or pairs and you would like to select a bunch of them
```

I have done RNA-Seq and DNA-Seq analysis before where we have 100 and 150 paired and samples, but most often just 6 - 10. All the used tools have now the ability to use pairs for paired end data, so I was trying to port these workflows to using pairs instead. Then I realized this functionality was not available, though it is a very intuitive way of doing it.

```
in most cases if people were using collections they'd have nested collections
```

That was what I have been thinking of as well, but this feels to me as an over complicated step and doesn't feel intuitive, especially for rather small data sets with 6 to 10 pairs.

```
previously paired datasets and lists of paired datasets would be in different drop downs to indicate one is going to do a mapping operation and one is going to just run a normal job. They all just appear in the same drop down now.
```

I am not far enough into all this code to understand this entirely, but it sounds like a quite complicated feature I am asking due to the generalization of lists and pairs, correct? It is definitely not that an important feature.
