### ISSUE TITLE
Font sizes off?

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#14799]
**Describe the bug**

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/2105447/195962659-0db769b9-5955-4ce1-8afb-200f6c911092.png">

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: (check <galaxy_url>/api/version if you don't know)
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ElectronicBlueberry** [comment]
Please provide additional information explaining what the issue is and how to reproduce it

**Comment by ElectronicBlueberry** [comment]
@davelopez just caught me up on the issue.

This is something I've been targeting for the heading refactor.
Adjusting the font-sizes of the help text would hide the issue, but not solve the underlying heading level problem of h1 elements being used here.

Since we can't rework all tool help texts, the only solution I see is to modify the heading levels of tool help texts at some point, either in the back-end or in the front-end, and push them down by two levels.
