### ISSUE TITLE
tour navigation flow improvements

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#1492]
- if you move too fast in the tour (e.g. you already know how to upload and want to skip that part) you will end up like this 
  ![screenshot 2016-01-13 13 12 40](https://cloud.githubusercontent.com/assets/1814954/12303284/839f00e4-b9f7-11e5-8bad-0125ef9003a0.png)
- if you want to move back in the tour it won't properly trigger the events (e.g. because the targets do not exist anymore  - upload modal)

**Comment by dannon** [comment]
Regarding moving too fast, it's because the click actions fire regardless on enter/exit (pre/postclick) of the state.  I've thought about this and similar 'oops, the user did something we didn't expect' problems in tours quite a bit and talked with @guerler about it, and I don't know that it's worth the additional complexity to add more sophisticated triggers here -- it seems to be a rabbit hole you never get to the bottom of, eventually ending up with a fully 'on-rails' tour.  For now, I think it'd probably be best if these actions were simply used very sparingly in tours that are expected to be 'interactive' at all.

One option we've discussed is to define any step having 'actions' as being by definition on rails, preventing any other sort of action using an overlay or some other mechanism -- but that could be equally or even more frustrating for users and I'm not sure it's a good plan either.

I guess my mental compromise was to focus on two distinctly different sorts of tours -- one which is expected to be totally on rails and perhaps even has step timers and basically runs itself, expecting the user to click/enter _nothing_ other than 'next', and the other that's expected to be truly interactive but which, of course, the user can break.  Resolving the latter's breakage really comes down to being able to push a particular state to the Galaxy client, which isn't easy.

**Comment by martenson** [comment]
I think this is mostly fine. You still cannot go too fast and you have to have panels shown etc.  but those are tiny not so important cases. Closing. Thanks @dannon @bgruening
