### ISSUE TITLE
Options to build collections missing if all datasets of a history are selected

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#14967]
**Describe the bug**

If I select all datasets of a history using `Select All` then there is no option to build a collection of these datasets. 

https://user-images.githubusercontent.com/25689525/201123066-cf7ab70a-728f-4935-a591-0bc46cf42837.mp4

If I unselect and reselect a dataset / if I manually select all datasets, then the options to build collections are shown 

Also observe the inconsistencies in the counts of the selected datasets.

**Galaxy Version and/or server at which you observed the bug**

Galaxy Version: 22.05
Commit: https://github.com/galaxyproject/galaxy/commit/b709a19c5edbb1015145aa7aad074ee17cd9724b

**To Reproduce**

See video

**Expected behavior**

Options to build collections should always be visible in the dropdown.

**Comment by itisAliRH** [comment]
This happens because it's query selection using `Select All`, and when you manually select/deselect datasets, it's not `query select` anymore and works normally.

**Comment by bernt-matthias** [comment]
> This happens because it's query selection using `Select All`, and when you manually select/deselect datasets, it's not `query select` anymore and works normally.

Thanks for the explanation. Still a bug, isn't it?

**Comment by davelopez** [comment]
More than a bug is a limitation of the current selection system.
So the thing here is, that when you `select all` the client can't know if there are other collections in your selection or load every potential dataset in the collection builder UI, since the effective selection will be made on the server based on the current search query.

There is a workaround if you have a reasonable number of datasets in your history though, if you scroll to the very bottom eventually you will have every dataset loaded, and in that case (assuming you don't have other collections selected) you will be able to create a collection out of the entire history.

**Comment by bernt-matthias** [comment]
>  if you scroll to the very bottom 

Btw. is the new history paginated? If yes, what does `Select all` mean in this case?

**Comment by davelopez** [comment]
So, instead of the old pagination in the history, now the contents are retrieved from the server as you scroll (the first 100 or so are requested in the first load). That is what makes the history UI snappy otherwise loading potentially thousands of datasets can be extremely slow or even not feasible.

About selection, this dynamic loading has its consequences, so the `select` functionality works like this:
- If you manually select individual items (with the checkboxes) those will be sent directly to the server for processing (delete, hide, etc.)
- If you `select all` the behavior depends on the number of total items in the history and the number of items loaded.
  - if `total number of items in history` == `number of loaded items` all items will be sent to the server (similar to the manual selection case).
  - if `total number of items in history` > `number of loaded items` then the **`query`** mode is used, meaning instead of sending the items to the server, the search query that would have returned those items is sent to the server for processing.
    - if you manually unselect individual items while in `query mode` then you "break" the query selection since now "not all items" are selected and a message is displayed informing you of that.

Hope is more clear now, but I understand is kind of complex right now... :sweat_smile:

**Comment by assuntad23** [comment]
Per UI/UX meeting conversation: only allow simple list building, do not populate collection creator. Only ask user to provide list name. Also, filter out collections

@dannon @mvdbeek @martenson @davelopez   Is this in line with what we discussed? ^

**Comment by jmchilton** [comment]
Assunta and I talked about this and she is going to add an API endpoint that would allow doing this without transferring data back to the client. I think this fine but the rule builder can process hundreds of thousands of entries and keep the UI responsive and we could use the version of the API that just pulls down fixed attributes to fetch the name and ID - this would allow all our existing validation to work and would allow creating paired list, multiple grouped collections, etc.. from this setup. It would also serve as a test bed for a simpler version of the rule builder that we could place users into by default in this configuration. I don't think we're going to go that way but I wanted to register my... long term plan... and what I would do if I were going to tackle this.

**Comment by assuntad23** [comment]
Follow-up plan from backend meeting on March 7:
Fetch the names and ids of all datasets in the history
Put them into the ListCollectionCreator

**Comment by assuntad23** [comment]
closed with #15947
