### ISSUE TITLE
Workflows: tags are not rendered correctly in editor

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#15212]
**Describe the bug**
Tags assigned to a workflow render correctly in a workflow listing but not in the workflow editor.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: UseGalaxy.eu {"version_major":"22.05","version_minor":"1"}
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**To Reproduce**
1. Import a workflow that has tags
2. Open it in the editor
3. Notice the number of tags is correct but they don't have original content in the editor but do in the workflow listing
4. Adding a new tag is rendered correctly (without hash in the test)
5. Not tested (yet) at other servers or with new/native workflows with existing tags
6. Not sure if the `#` is the problem or not yet. If it is, maybe we should ignore the hash?

**Expected behavior**
Tags that are persistently and correctly rendered in all views (or, at least in these two)

**Screenshots**
<img width="573" alt="Screen Shot 2022-12-13 at 6 49 28 PM" src="https://user-images.githubusercontent.com/8999735/207494377-0a9ca795-f4fe-4412-881a-9eeb6a558cc5.png">

<img width="339" alt="Screen Shot 2022-12-13 at 6 49 47 PM" src="https://user-images.githubusercontent.com/8999735/207494392-0a08bc35-462c-4864-898b-c05deb017a53.png">

<img width="288" alt="Screen Shot 2022-12-13 at 7 01 54 PM" src="https://user-images.githubusercontent.com/8999735/207494830-eddc3736-e223-40b6-a2fd-0764e73e4c07.png">

**Additional context**
If whoever picks this up wants me to do more testing for scope, please ping.

**Comment by hujambo-dunia** [comment]
@guerler, @mvdbeek, @jmchilton, @dannon,

I believe [this bug ticket](https://github.com/galaxyproject/galaxy/issues/15212) is caused because the `workflows/editor` route is incorrectly formatting workflow Tags (it fails to handle the `#` hash character which appears to being used as a type of reserved word). The result is you see the word "name" instead of the Tag Name when a user starts a Tag Name with a hash character (ie. "#myTag" vs. "myTag"). This bug occurs on both `release_22.05` branch and `dev` branch (my latest pull was Dec 14, 2022).

Comparatively, both the `api/workflows` route and the `api/users` route correctly format workflow Tags - they are able to handle the "#" character and display the Tag Name correctly. It is easy to see the routes failing to format the "#" properly simply by going to: your Workflow Edit Page's >> in the DevConsole "Network" tab to see the `workflows/editor` route output. However, I'll include a screenshot here too:

![screenshot_Workflow_Tags_Incorrect_Routing_Format](https://user-images.githubusercontent.com/3672779/207968035-0a9e069b-40f9-47aa-88b9-49601fdc8787.png)

My question is this: is there a way to modify the existing back-end `workflows/editor` route's outputted elements to include another element which: formats Tags similar to the `api/workflows` route or the `api/users` route? Potentially, (1) the same methods/functions used to get Tags in those other two routes can be called/referenced into the `workflows/editor` route --that should work (2) provided the new element also includes a "Workflow ID" identifier so Tags can be displayed for a single workflow.

Specifically, I am thinking about about a new element named `tags_used_workflows` which [could appear here](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/managers/users.py#L631-L632) (ie. underneath the `tags_used` element) but instead of an array listing all Tags across all workflows, it would include Tags associations with Workflow ID. That would enable me to easily link it to the front-end Editor component in `WorkflowEditor.vue` [file here](https://github.com/galaxyproject/galaxy/blob/dev/client/src/entry/analysis/modules/WorkflowEditor.vue#L8).

Thoughts? :)

**Comment by dannon** [comment]
@hujambo-dunia Thanks for taking a look.  I'm not sure I follow the `tags_used_workflows` bit, but check this tweak out:

https://github.com/galaxyproject/galaxy/commit/0f724929a48e403588f4e0b22411974e14a9933f

That might do it?  It looks like we were building our own tags list there, and it was unintentionally dropping the values.

This could definitely still use updating to the new tags component, if you'd like to build on that commit.

**Comment by hujambo-dunia** [comment]
@dannon Perfect - thanks! I'll build on your commit.

**Comment by davelopez** [comment]
Fixed!
