### ISSUE TITLE
Support sqla / database backend for beaker

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#15216]
Should help with https://github.com/galaxyproject/galaxy-helm/issues/399#issue-1498235975

**Comment by claudiofr** [comment]
This would be my first contribution to galaxyproject. I made the code changes locally and wrote a unit test for it, but I don't believe that it will help with #399 above because the beaker docs say that the lock_dir cache parameter is required independent of the cache type. This suggests that it uses the file system for locking even if it uses the database for the cache. I'm also relatively new to github and I'm about to do my first github pull request. I presume you need to assign it to me as I see no way to assign the issue to myself. Can you please do so?

**Comment by jdavcs** [comment]
> I presume you need to assign it to me as I see no way to assign the issue to myself. Can you please do so?

Done.

**Comment by claudiofr** [comment]
I created a pull request for this. Will someone be automatically notified of this and take action on it or do I need to explicitly notify someone?

**Comment by nsoranzo** [comment]
@claudiofr Thanks, all the repository reviewers received a notification from GitHub.
