### ISSUE TITLE
Workflow Editor Step Loading Indicator improvements

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#15323]
> Can we make an addition to reduce the frequency of the loading spinner in the steps (suggesting to show it only once on creation and inside the step box instead of the header), currently it appears frequently e.g. when changing any form value etc? I also notice that double clicking can happen accidentally which then leads to zooming instead of e.g. checking the output box.

_Originally posted by @guerler in https://github.com/galaxyproject/galaxy/issues/15291#issuecomment-1377972745_

**Comment by martenson** [comment]
We tracked the loading indicator part of this with @guerler. The underlying issue is most likely connected to the update requests that are supposed to not trigger the whole cascade of reactivity updates if nothing changes after the response is received...but they always do. Hence so much loading whenever anything is clicked, filled, or changed.
