### ISSUE TITLE
Workflow invocations state for successful invocations and embedded

### ISSUE THREAD

**Issue by itisAliRH** [galaxyproject/galaxy#15428]
**Describe the bug**
1. All successful workflow invocations have `scheduled` state  
![image](https://user-images.githubusercontent.com/8046843/215086905-207c6a8c-1f8d-4fac-aa28-e7c7c47bf1b7.png)
2. Embedded workflow invocations state are `unknown` when parent workflow is `scheduled`, `cancelled` or `failed`. 
![image](https://user-images.githubusercontent.com/8046843/215087399-0caf197d-a8ea-41c2-bac2-b14880583fe0.png)
3. Invocation state in the table shows the initial state when the list loaded not the last one
![image](https://user-images.githubusercontent.com/8046843/215088710-74a8bfef-7185-4236-b375-a4b03e0a464a.png)

**Galaxy Version and/or server at which you observed the bug**
usegalaxy.org (v23.0.rc1)

**To Reproduce**
1. Go to `Workflow Invocations` from the `User` menu
2. See successful/cancelled/failed invocations state

**Expected behavior**
Show `successful` for successful invocations and show the state of embedded workflow invocations based on their parent state and show the last state of each in the table

**Comment by mvdbeek** [comment]
> 1. All successful workflow invocations have `scheduled` state

I don't think that's a bug, they are scheduled. That has nothing to do with job states, so that is the only thing that really makes sense there. You can easily have failed jobs in a "successful" invocation. 

> 2\. Embedded workflow invocations state are `unknown` when parent workflow is `scheduled`, `cancelled` or `failed`.

Can you elaborate what you've done to reach that state ?

> 3\. Invocation state in the table shows the initial state when the list loaded not the last one

Yes, the data is not polling for updates. Possibly the reason for 2 ?

**Comment by itisAliRH** [comment]
> > 1. All successful workflow invocations have `scheduled` state
> 
> I don't think that's a bug, they are scheduled. That has nothing to do with job states, so that is the only thing that really makes sense there. You can easily have failed jobs in a "successful" invocation. Are you maybe looking for an additional count of how many jobs are ok/paused/errored etc ?
> 
I thought The "scheduled" state refers to an invocation that has not yet run and is waiting to run, and it would be appropriate to have another final state, such as "completed" or "finished," to indicate that the invocation has been completed regardless of the result.
> > 2. Embedded workflow invocations state are `unknown` when parent workflow is `scheduled`, `cancelled` or `failed`.
> 
> Can you elaborate what you've done to reach that state ?
> 
One of the failed invocations failed for an unknown reason and the other one failed due to it having wrong dependencies (each image shows a workflow and the workflow embedded in it):
![image](https://user-images.githubusercontent.com/8046843/215108526-ed3b1d90-f205-460c-b0fe-0bd2ca61c6e3.png)
![image](https://user-images.githubusercontent.com/8046843/215108695-39167c97-b02c-4823-a7ab-60fd6495ddc6.png)
I have cancelled an invocation just after running it by clicking on the `x` button
![image](https://user-images.githubusercontent.com/8046843/215108890-47ac902e-d9c9-4c52-96fc-6d491fa5fa36.png)

> > 3. Invocation state in the table shows the initial state when the list loaded not the last one
> 
> Yes, there is no polling for updates. Possibly the reason for 2 ?

I think yes

**Comment by mvdbeek** [comment]
Scheduled means the invocation has been scheduled successfully, that means all steps have been created in the database. If jobs for all steps can be scheduled ahead of time it's often fairly quick / immediate, but it can happen that we can't create jobs yet because no reference to intermediate datasets exist, in that case the scheduler is waiting until that is the case. 

You've seen the other cases, an invocation can be cancelled (on user request or be deleting the history) and it can fail (for a variety of reasons, like output datasets that are never going to be produced, or if jobs fail that are required in order to proceed scheduling more jobs).

**Comment by mvdbeek** [comment]
We should probably explain ^^ in a glossary or tooltip or something like that

**Comment by mvdbeek** [comment]
That actually happened
![Screenshot 2024-07-20 at 09 06 42](https://github.com/user-attachments/assets/39563b41-06bf-49b3-a481-63ef99b9b214) and there's https://github.com/galaxyproject/galaxy/pull/17708 to make the two states easier to see.
