### ISSUE TITLE
Misc. tool search issues

### ISSUE THREAD

**Issue by jdavcs** [galaxyproject/galaxy#15448]
Related to #15382 

1. Cannot find tool when searching for full description as displayed in toolbox (i.e., name + description). Affects basic search, but not advanced.

    1.1. Reproduce: copy a line from the toolbox ("FastQC Read Quality reports"), paste into search box, hit Enter: observe no results
    1.2. Toggle advanced search, then hit Search: observe results (this is the expected behavior)
    1.3. Remove tool description ("FastQC"), repeat basic search: observe result
    1.4. Remove tool name ("Read Quality reports"), repeat basic search: observe result 

    Expected behavior: if my search query contains the tool name and description, I expect that tool to be included in the results.
(Maybe we should check for verbatim matches of name/description/name+description - i.e., what a user might see in the tool bar - and if there is a match, return it at the top of the list unconditionally?)

2. If the first text box in advanced search is expected to behave identically to the text box in basic search (i.e., "search by name"), then item 1 should not happen: searching for "foo" should produce the same results under basic and advanced search.

3. The first search box in advanced search searches by name *and description*, yet its label says "search by name". Might be misleading?

4. Surrounding white space affects search in basic search.
To reproduce: search for a tool by name "fastqc": observe results. Then add white space (prepend and/or append): observe no results. Advanced search is not affected.
Solution: trim

**Comment by ahmedhamidawan** [comment]
Hello @jdavcs! Thank you for testing this out!
1. This should be fixed in https://github.com/galaxyproject/galaxy/pull/15434. (You could try it out on main now!)
2. I would reckon https://github.com/galaxyproject/galaxy/pull/15434 solves this as well.
3. We thought _`search by name`_ covers `name+description` as maybe users might be confused by what `description` actually is here? Note that tools do not show up with the **name** in bold and description not in bold (e.g.: We don't have **`Select`** `lines that match an expression` anymore in this release, it is just `Select lines that match an expression` in the Tool Panel)
4. Now this is something I can put up a bug fix for: Trim query for `ToolSearch`

So, if all else works as I described above, this only action item here would be `4`?

**Comment by jdavcs** [comment]
@ahmedhamidawan Thanks, sounds good to me!

**Comment by ahmedhamidawan** [comment]
Can be closed as part of #15485

**Comment by jdavcs** [comment]
Fixed in #15485
