### ISSUE TITLE
Shared histories page starts sorting on clicking non-sortable columns

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#15476]
**Describe the bug**
The list of published histories can be sorted by Name or Last Updated.
When freshly loaded however clicking on the non-sortable column names 

Annotation | Owner | Community Tags

also starts sorting by some criteria.
This only happens once.

**Galaxy Version and/or server at which you observed the bug**
usegalaxy.org at 23.0rc1

**To Reproduce**
1. Go to https://usegalaxy.org/histories/list_published
2. The list should be sorted by Last Updated
3. Click on any of the above column names

**Expected behavior**
Clicking on non-sortable columns should have no effect.

**Comment by itisAliRH** [comment]
The behaviour of clearing sorting when clicking on a non-sortable is a [bootstrap-vue feature](https://bootstrap-vue.org/docs/components/table#sorting) that can be disabled. By default, When clicking on a non-sortable column will clear the sorting. This issue/feature is visible in other components including the installed tools list in the admin panel `/admin/toolshed`.
What to do? Disable or keep it? @dannon

**Comment by dannon** [comment]
@itisAliRH Thanks for tracking that down -- my first inclination is to disable it with `no-sort-reset`, but I'm happy to hear other opinions.  It just seems like extra confusion (as seen in the issue here) that a non-sortable column *looks* clickable and seemingly arbitrarily changes the display without a clear indication of what's going on.

**Comment by dannon** [comment]
In addition to this set the default sort order to match the state of the initial data in published histories.
