### ISSUE TITLE
Workflow Hub Queries not working?

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#15532]
**Describe the bug**

@gallardoalba @bgruening I'm trying to turn the VGP/WFH query into a snippet and I was going to file a tangential issue but now I see this, is this expected? I think

![image](https://user-images.githubusercontent.com/458683/217476775-03592c72-5c26-479f-92d9-fa0dd0df339c.png)

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.05, UseGalaxy.eu

**To Reproduce**
1. Go to workflows
2. Click on import from WFH
3. Enter ANY query

**Expected behavior**
it lists the WFs.

**Comment by wm75** [comment]
You're in the wrong dialog I think!

![image](https://user-images.githubusercontent.com/4742081/217479917-037f3354-5aae-413a-9e2e-507478d13315.png)

It's the search form link, not the TRS ID one.

We know it's confusing and the links are hard to discover in the first place - that's why @mvdbeek (I believe?) reworked the whole import interface in 23.0. Looks so much better on usegalaxy.org now :-)

**Comment by hexylena** [comment]
Pffft. Those two clickable links really run together, wow. Ok, yeah new interface is indeed improved in some aspects but I find the GA4GH branding really confusing, I don't think anyone knows what a GA4GH compatible endpoint is, they're looking for names they recognise like WFH or Dockstore?

But ok this issue is solved, I'll open a new one with those complaints.
