### ISSUE TITLE
Remote files: Export to Remote Files: Should be disabled if none available/configured

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#15552]
We should probably disable the export icon in this case.

I encountered this on main when I was looking to export my BCO, I was given the option of selecting a remote location

![image](https://user-images.githubusercontent.com/458683/218118938-d9a0579c-6fa6-4b3c-a95d-8c3ce0773745.png)

But when I went to select a directory, there were no options:

![image](https://user-images.githubusercontent.com/458683/218119102-252e574a-e1cf-433c-bb54-50fff764c378.png)

**Comment by mvdbeek** [comment]
I suppose a history would also be a neat little remote data target. Maybe silly, but at least that's available on each Galaxy server. How bad does that sound @jmchilton @davelopez ?

**Comment by hexylena** [comment]
Ah yes my other suggestion from the ui-ux chat. Yes, that would be the ideal fallback. Always available, can do async, I can manually check back later for the files.

**Comment by davelopez** [comment]
Histories as remote file sources sound cool! I don't know how well they'll fit into a file source, but it may be worth exploring :)

As for this issue in particular, I'm afraid I will need to completely disable the export when celery is not enabled in the server since the actual export and packaging of the invocations happens in a celery task :grimacing:

**Comment by davelopez** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/15556
