### ISSUE TITLE
Importing from a workflow shared URL fails

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#15658]
**Describe the bug**
Share links are rejected. Because these lack a **.ga** extension?

**Galaxy Version and/or server at which you observed the bug**
ORG Galaxy version 23.0.rc1, commit [f84508f303086b8604deec24dd259d0a8d2ad967](https://github.com/galaxyproject/galaxy/commit/f84508f303086b8604deec24dd259d0a8d2ad967)
EU `22.05`

**To Reproduce**
1. Create a "Share or Publish" link for a workflow
2. Go to a different public Galaxy server and attempt to import the workflow
3. Fails the validation checks
4. Slightly different messages for ORG -> EU or EU -> ORG but both trigger a similar warning
5. Test WF share links
  * https://usegalaxy.org/u/jen-galaxyproject/w/mothurthruuniqueseqs
  * https://usegalaxy.eu/u/jenj/w/training-16s-rrna-sequencing-with-mothur-main-tutorial-imported-from-url-1

**Expected behavior**
Allow generation of workflow share links, and have those accepted for import at a different server

**Screenshots**

**EU -> ORG**

<img width="1146" alt="Screen Shot 2023-02-27 at 12 21 40 PM" src="https://user-images.githubusercontent.com/8999735/221678050-d0278dba-d632-460c-9c20-d844e809c8eb.png">

**ORG -> EU**

<img width="1105" alt="Screen Shot 2023-02-27 at 12 19 24 PM" src="https://user-images.githubusercontent.com/8999735/221678243-5059fca3-1afb-4bba-8155-4c35ca243b14.png">

**Additional context**

**Comment by jennaj** [comment]
**Updated**: The problem is likely with the format of the share link. 

**Usage impact**: In order to share a workflow, it needs to be published not just shared. This is a major change from prior functionality. A lot of even our publication links will be impacted. 

**Examples**: Both links are for the same workflow.

**Works** -> URL from published view https://usegalaxy.org/workflow/export_to_file?id=b2f3d7e4cd4d0f11
<img width="654" alt="Screen Shot 2023-02-27 at 4 50 45 PM" src="https://user-images.githubusercontent.com/8999735/221724280-f11288e4-8de0-4790-a73b-1660a8071254.png">

**Fails** -> URL from "Share or Publish" view. These always have a custom name and defaults to the workflow name. https://usegalaxy.org/u/jen-galaxyproject/w/mothurthruuniqueseqs
<img width="718" alt="Screen Shot 2023-02-27 at 4 53 36 PM" src="https://user-images.githubusercontent.com/8999735/221724236-d93d7463-afff-43a9-af31-8558bd414edb.png">

**Comment by dannon** [comment]
Xref slack, but:  That "Share or Publish" url isn't the one used for importing.  We want the url from the "Export" workflow interface, which will be the same slugified url with `/json` appended, something like `https://test.galaxyproject.org/u/dannonbaker/w/unnamed-workflow-1/json` instead of `https://test.galaxyproject.org/u/dannonbaker/w/unnamed-workflow-1`.

We can do a few things here.

1) Make the import machinery detect the invalid route and append a `/json` automatically when it matches the understood `/u/blah/w/blah` schema

2) Add more help text.

**Comment by hexylena** [comment]
What there's a `/json`? Oh my gosh that's so useful. That makes some things in ptdk easier I think (ping @bebatut) We could just ask users to 'share workflow via link' and that's way easier than explaining workflow ID. It'd eliminate a whole button

**Comment by hexylena** [comment]
Undiscussed option 3 I guess @dannon @ElectronicBlueberry would be listening to content-type headers. If the request is for `text/html`, then render the workflow page. If the request comes with `-H Accept: application/json`, we could return the galaxy workflow? (or using a vendor prefix like github does if you prefer.) I know other people do that for e.g. accessing the API, if the request is a browser requesting text/html, then they redirect and show the OpenAPI schema docs. Otherwise, just the actual API is returned. It would be a more general solution and maybe nicer as a machine to interact with Galaxy that we could use the same URLs.

(#15903 also works great as a workaround for this one URL.)
