### ISSUE TITLE
Link in pop-up window after Data Library to History import does not work

### ISSUE THREAD

**Issue by lldelisle** [galaxyproject/galaxy#15848]
**Describe the bug**
When you import a dataset from data library to history a green rectangle appear but when you click on it it does not work

**Galaxy Version and/or server at which you observed the bug**
usegalaxy.eu and usegalaxy.org

**To Reproduce**
1. Go to Data Library
2. Select a dataset
3. Click to import into history
4. Try to click on the green rectangle, nothing happens.

**Expected behavior**
I expect that when you click on the box it brings you to the history.

**Screenshots**
![image](https://user-images.githubusercontent.com/30404086/227916158-baa9376b-be31-4def-8220-cf34d85640f3.png)

**Comment by hujambo-dunia** [comment]
Hi @ElectronicBlueberry, it appears that a change made in this commit replacing the "toaster" feature reference `ui/toast` with a new JS library called `composables/toast` is the cause of the issue because the new JS library is missing a Promise feature where an on-click event could reside. Perhaps there was a security issue with the prior JS library's promise feature which is why it was removed...? What are your thoughts?

**Option 1)** Shall I go ahead and add a Promise feature to the `composables/toast` class? @dannon Do we want clickable "toaster" feature?

**Option 2)** Alternatively, replacing this line (with either below optional modules) fixes the issue but fundamentally changes the UI/design (but design is a straightforward change).
Either of the below work [in place of this line](https://github.com/galaxyproject/galaxy/blob/dev/client/src/components/Libraries/LibraryFolder/TopToolbar/import-to-history/import-dataset.js#L2) allowing the "toaster" feature to be clickable:
`import { Toast } from "ui/toast"`
`import * as Toast from "toastr"` 
![Greenshot 2023-04-26 07 49 03](https://user-images.githubusercontent.com/3672779/234570617-93607855-33fc-4855-85d7-abdb89fd777d.png)

**Comment by dannon** [comment]
We don't want to swap back to the old toast, the modernized composable is the way to go.  The old library was `toastr`, but the new composable uses a (more native for us, at least) bootstrap-vue based toast.

The contents just need to be clickable.  You want https://bootstrap-vue.org/docs/components/toast#links

**Comment by hujambo-dunia** [comment]
@dannon Thanks for the URL! Our code has a pass-through component where the `href` parameter got dropped, so [my PR](https://github.com/galaxyproject/galaxy/pull/16008) (which is ready for review) adds the param back and references it in the code.

**Comment by dannon** [comment]
Fixed in #16008
