### ISSUE TITLE
BAM iobio does not load on Test

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#1588]
![screenshot 2016-01-26 13 01 00](https://cloud.githubusercontent.com/assets/1814954/12589682/01b9766e-c42d-11e5-967c-9d2f7d6cde0c.png)

**Comment by bgruening** [comment]
@natefoo we don't have a sshfs shared filesystem right?
This IE mounts in BAM file into the container, because we do not want to copy it.
Just checked and it's working in galaxy-stable.

**Comment by natefoo** [comment]
We do not, no. =(

**Comment by bgruening** [comment]
Than it's good to not activate it. I don't think it's worth the effort to copy BAM files.

**Comment by martenson** [comment]
@natefoo @bgruening so this will never run on Main/Test?

**Comment by bgruening** [comment]
At least until we could figure out a way howto share a filesystem between the Dockerhost and Galaxy.
I could implement file copying, as we do in Jupyter ... but since BAM files are usually large you always copy a BAM file between Galaxy and the Dockerhost, just for visualisation. I guess this is to much.

**Comment by natefoo** [comment]
I had an sshfs mount set up for Test before @bgruening removed the need for it from the IPython IE. We could potentially set it back up, but I wonder if we ought to figure how we might provide alternatives to shared filesystems to all IEs in a general way that doesn't require a full copy of the dataset.

**Comment by martenson** [comment]
I do not understand the underlying filesystem issue, but it makes me sad that we are so close to have this awesomeness but still so far.

**Comment by bgruening** [comment]
@natefoo with a shared FS you don't need to copy. We mounting the file into Docker in readonly mode. No copying. We just need to have a path accessible from the Dockerhost to the actual data.

**Comment by bgruening** [comment]
@natefoo this links the data into the container. The path needs to be accessible from the Dockerhost. Any suggestions welcome.
https://github.com/galaxyproject/galaxy/blob/dev/config/plugins/interactive_environments/bam_iobio/templates/bam_iobio.mako#L12

**Comment by martenson** [comment]
@bgruening can bam iobio do file range requests? We could make it work with nginx to prevent fetching the whole file.
Even if you go to the original http://bam.iobio.io/ running it on large files is either using the range requests or fetching the whole thing right?

**Comment by yiq** [comment]
Hey Guys

  I was just trying to see if bam.iobio is up on usegalaxy.org and stumbled upon this thread. Here are a few pieces of information that I thought might be useful

@martenson bam.iobio does indeed work via requesting several small slices of a file, instead of fetching the whole thing. However, it does so indirectly via samtools. When a list of sampling regions are generated, bam.iobio client (the javascript code) creates a URL that represents the following stream:

samtools view -h `http-url-to-bam-file` `region1` `region2` ... --pipe into-> bamstatsalive

To facilitate samtools accessing the bam file via http, an nginx instance is actually running inside the docker container that, in addition to act as a reverse proxy for all the iobio services, also serve file from a particular directory, which happens to be where the bam file is linked into the container. Because samtools service and nginx runs in the same container, the file can simply be accessed via http://localhost/tmp/bamfile.bam. Note that the 'localhost' here is in respect to the docker container. There are also access controls in place to prevent access to the file from outside of the container, just to ensure some rudimentary security.

This method is suitable for visualizing bam files that can be accessed via a regular UNIX path on the host docker is running, which can either be locally stored or network mounts. If the file can be exposed via any other http link (e.g. http://bam_repository.example.org/upload/user1/testfile.bam), that link can also be used directly.

Hope it helps~

**Comment by martenson** [comment]
@yiq 

> If the file can be exposed via any other http link (e.g. http://bam_repository.example.org/upload/user1/testfile.bam), that link can also be used directly.

Do I understand it correctly that if we pass a url outside of container then samtools will fetch several slices of the file without requesting a full download?

**Comment by yiq** [comment]
@martenson You are right. That's how exactly the production site works. The 'outside url' is just https links to the 1000genome dataset on amazon

**Comment by martenson** [comment]
ping @bgruening

**Comment by bgruening** [comment]
As in theory this would be possible if we could provide an accessible dataset link to a different host, as we do it with IGV or UCSC, this is not easy to setup and will not work for every IE.
I just fear the extra routing and accessibility problems with this approach.

@natefoo do you have anything in mind how such a mechanism should look like for IEs in general?

**Comment by martenson** [comment]
User could 'share' the dataset with the IE?

**Comment by jmchilton** [comment]
Maybe I am mistaken - but external data sources have certain concerns (like reserving the ability restricting access, worrying about leaking secrets) that IEs don't. We give the IEs user API keys - these keys should be able to access dataset contents via a URL - we could just formalize this a bit?

**Comment by bgruening** [comment]
@jmchilton I guess we are talking here about publicly available links to datasets. At least public to the docker host. Not sure how the API key fits in here.
What we are doing for IE's with rather small datasets, we are copying them via bioblend into the Dockerhost, but this I would like to avaoid for BAM files and the :ro mount mount of Docker is so convenient for it.

**Comment by natefoo** [comment]
If the container has the user's API key, then we can make range requests on the dataset without needing to have that dataset be "publicly" accessible to the docker host.

**Comment by bgruening** [comment]
@natefoo how to do so? I mean bam.io does not know about API keys, it just takes a URL afaik.

**Comment by jmchilton** [comment]
@bgruening - @natefoo is saying what I was trying to say - we should be able to supply the bam URL as http://localhost:8080/api/histories/f597429621d6eb2b/contents/datasets/4b187121143038ff/display?key=mygalaxyapikey right?

**Comment by natefoo** [comment]
That is my thinking as well.

**Comment by martenson** [comment]
bam.iobio is now provided as a display application on both Test and Main.

If interested in IE implementation of this please open a new issue.
