### ISSUE TITLE
Use of URL Split to mask Database Password conflicts with valid DB passwords

### ISSUE THREAD

**Issue by cpollard0** [galaxyproject/galaxy#16083]
**Describe the bug**

A valid DB password can have a the characters `[` and `]`. However, Galaxy can't parse these passwords when it does mask on the below line due to the use of urllib urlparse, which interprets this as an IPv6 address. 

https://github.com/galaxyproject/galaxy/blob/f98794d8cdd39d167ec91a2cacde93506a76a480/lib/galaxy/util/__init__.py#L766

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: (check <galaxy_url>/api/version if you don't know)
Commit: a4266b86a398f6cc50b7acd687825c65a6a621f0

**To Reproduce**
1. Create a database with a user with the `]` character in the password. 
2. Update galaxy.yml to use this database/user in the connection string
3. Start galaxy

**Expected behavior**

Galaxy handles valid DB passwords

**Comment by jdavcs** [comment]
@cpollard0 thank you for reporting the bug and identifying the root cause - this is very helpful!

In addition to causing an immediate error on startup in Galaxy's `util` module, this will also lead to a kombu error, once the password masking function is fixed (in a default setup):
```
galaxy.queue_worker INFO 2023-05-24 21:59:29,618 [pN:main,p:1425297,tN:MainThread] Queuing async task rebuild_toolbox_search_index for main.
...
  File "/.../.venv/lib/python3.9/site-packages/kombu/utils/url.py", line 59, in url_to_parts
    scheme = urlparse(url).scheme
  File "/usr/lib64/python3.9/urllib/parse.py", line 393, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
  File "/usr/lib64/python3.9/urllib/parse.py", line 484, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL
```

Furthermore, this issue extends beyond bracket characters. Characters `#/?`, occurring anywhere in the password, will interfere with the parsing of the URI, as a result of which the password will be displayed in the log message verbatim:
```
... Initializing main Galaxy Queue Worker on sqlalchemy+postgresql://myuser:my#secret@myhost/mydb
```

A programmatic solution is more complicated than it appears to be. Replacing characters would only solve the password masking issue for the logging message, but not the kombu error. Percent-encoding (as per [postgresql docs](https://www.postgresql.org/docs/15/libpq-connect.html#LIBPQ-CONNSTRING)) via  `urllib.parse.quote(password)` will solve the issue; however, for that to work, `password` must be extracted from the URI connection string *before* the interfering characters are handled - and that's bound to be an incomplete hack given all the possible formats in [RFC3986](https://datatracker.ietf.org/doc/html/rfc3986).  Quoting the entire connection string will result in an unparseable URI.

I propose documenting this in the config option's description (all database connection options): if the password (or user) contains characters `[]#/?`, it should be encoded via `import urllib; urllib.parse.quote(your-value)`. Thus, a connection string `postgresql://user:[secret@host/db`, would be listed in galaxy.yml as `postgresql://user:%5Bsecret@host/db`.

If Galaxy had access to the db password value *in addition* to the connection string (via separate config option), then automating this would be trivial. However, that complicates configuration which, I think, is unnecessary here.

**Comment by jdavcs** [comment]
After discussing it on the backend channel with @dannon, we decided to go with the proposed solution + do a check at startup and raise an error with an informative message in case the connection URI cannot be parsed.

For additional context (and more support for observations in previous comment) see https://github.com/python/cpython/issues/77523, https://github.com/python/cpython/issues/67517, https://github.com/python/cpython/issues/80519.
