### ISSUE TITLE
Refactor Tool Panel views into one Toolbox

### ISSUE THREAD

**Issue by ahmedhamidawan** [galaxyproject/galaxy#16101]
Currently, we have 3 toolbox views in the `panelStore`: default, EDAM ontology and EDAM topics:
- api/tools?in_panel=true&view=default
- api/tools?in_panel=true&view=ontology:edam_topics
- api/tools?in_panel=true&view=ontology:edam_operations

The only thing that changes in those three is the ordering of sections; the data for each tool remains the same.

Instead of having three views in the client store, we should only have one central flattened toolbox (`api/tools?in_panel=false`) with each tool having sufficient information about sections/ontologies, **so that this information can be accessed at all times, regardless of what "view" is currently enabled**.

In addition to the `api/tools?in_panel=false`, we would then GET 3 views from the backend, each returning the `ToolSection` details, with `section.elems` not being a list of `Tool`s and instead a list of `tool_id`s from each section. _This would mean a change to the backend tool structure..._

xref https://github.com/galaxyproject/galaxy/issues/16453#issuecomment-1649341706
Marius has outlined the idea here ^

Once we have the 3 section views, and one flattened toolbox from the backend, we would then create 3 front-end views for the ToolPanel.

**Comment by tcollins2011** [comment]
Following Ahmed's suggestion I'll move my comment about the bio.tools edam tags over here:

As a continuation from the edam talk, most tools should now contain a bio.tools id that links to EDAM section so if someone wants to refactor how EDAM is being stored it could be worth seeing if we can bring in the bio.tool edam information as well. Especially since a lot of our tools are listed as uncategorized currently and lack useful tags.
