### ISSUE TITLE
`expect_num_outputs` required when filter present and `expect_num_outputs` incompatible with with `expect_failure`

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#16235]
So basically you can't have `expect_failure="true"` and output filters.

**Comment by bernt-matthias** [comment]
This is because the [testing framework forbids](https://github.com/galaxyproject/galaxy/blob/e6f6c1d89a8d93506cb72e892f031c86ae25097a/lib/galaxy/tool_util/verify/interactor.py#L1438) to have any outputs if you have `expect_failure`.  So it seemed logical (aka OK) to forbid `expect_num_outputs` as well. But I recall that I was wondering about this when I touched the code. 

What is the context here, i.e. what exactly are you trying to test?

**Comment by gregvonkuster** [comment]
Trying to test the gtdbtk_classify_wf tool.  The issue is that the required gtdbtk database is extremely large, so cannot be used with the current Galaxy test framework.  Since at least 1 test is required, this is the one we're using https://github.com/galaxyproject/tools-iuc/blob/main/tools/gtdbtk/gtdbtk_classify_wf.xml#L132.  When we have a work-around for the large gtdbtk database issue, we will be able to uncomment this more useful test https://github.com/galaxyproject/tools-iuc/blob/main/tools/gtdbtk/gtdbtk_classify_wf.xml#L67.

**Comment by bernt-matthias** [comment]
Maybe like so: https://github.com/galaxyproject/galaxy/pull/16237
