### ISSUE TITLE
23.1 testing: notifications issues

### ISSUE THREAD

**Issue by luke-c-sargent** [galaxyproject/galaxy#16357]
**Describe the bug**
Testing notifications (#15663), some observations:

PUT api/notifications/broadcast/{id}
- when broadcasting, notifications pop up in open galaxy tabs and if a user isn't currently on galaxy, pops up when they land. modified broadcasts do not change existing popped up and visible notifications (seems fine) but users that weren't on during broadcast and then navigate to galaxy do not get any broadcast. GET still shows the modified broadcast

GET api/notifications/status
- only shows a subset of the broadcasts; they seem to be only the unmodified ones

POST api/notifications
- api/docs 'notification: category:' defaults to broadcast, which results in an internal server error (KeyError: broadcast) as its not a broadcast; changing it manually to message works

GET api/notifications/status
- doesn't show notifications that can be seen via api/notifications/{id} (both commands issued by the same user)

testing done with users across different browsers / private windows to prevent credential mixups

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.1:rc1
Commit: 0b1a41bd866781355317f0ce13593a0acf7c135b

**To Reproduce**
See above

**Expected behavior**
The behavior as described in the api docs

**Additional context**
local instance with local users

**Comment by davelopez** [comment]
@luke-c-sargent thank you so much for the in-depth testing!

> PUT api/notifications/broadcast/{id} when broadcasting, notifications pop up in open galaxy tabs and if a user isn't currently on galaxy, pops up when they land. modified broadcasts do not change existing popped up and visible notifications (seems fine) but users that weren't on during broadcast and then navigate to galaxy do not get any broadcast. GET still shows the modified broadcast

So if I understand correctly, the issue is that if a user is not on Galaxy when the broadcast is sent, they will not see it when they land on Galaxy. Is that correct? I think this can only happen if you are using the same browser for both users. When you dismiss a broadcast notification, it is stored in the browser's local storage. So if you are using the same browser for both users, the second user will not see the broadcast notification because it is already dismissed. If you use a different browser for the second user, you should see the broadcast notification. We could also associate the broadcast notification with the user's ID so different users on the same browser would see the broadcast notification but I would say this scenario is not very common as having multiple accounts in the same instance is usually against the terms of use.

> GET api/notifications/status only shows a subset of the broadcasts; they seem to be only the unmodified ones

This seems to be working for me. I created 2 broadcast notifications and modified one of them. I can see both of them in the `status` request. Please make sure the `since` parameter is set to a date before the broadcast notifications were created (just in case) or that any of the notifications not returned by the request are not yet expired.

> POST api/notifications api/docs 'notification: category:' defaults to broadcast, which results in an internal server error (KeyError: broadcast) as its not a broadcast; changing it manually to message works

Ok thanks I'll fix the interactive docs 👍

> GET api/notifications/status doesn't show notifications that can be seen via api/notifications/{id} (both commands issued by the same user)

Can you verify that those notification that didn't show up in the `status` request have been created or modified *after* the `since` parameters in the request? the status request only returns notifications that have been created or modified after the `since` parameter to avoid returning too many notifications that are supposed to be already in the browser's local storage.

Again thank you so much for the testing and the feedback! I'll fix the interactive docs and wait for your response to debug those cases. I also found another UI issue (https://github.com/galaxyproject/galaxy/issues/16363) while testing your comments :)

**Comment by luke-c-sargent** [comment]
thanks for the clarifications! i'll dig into this further. it took me a bit to wrap my head around the behavior of the notification types (e.g. who should be able to see what -- very sensible in retrospect), and the hijacking of `run-as` by the session token messed up my initial testing.

a little more about my testing setup: i had three accounts set up, each in its own 'isolated' window: admin in firefox, regular user in chrome, another regular user in a private browsing window. i tried API calls from all of these to get the different user perspectives, and checked identity with the `/api/whoami` call thanks to Marius's helpful input. i set the 'since' to a month before the broadcast to be safe. i will try 'em again though as its entirely possible i borked any or all of the above up :D

re: the broadcasting situation: i would issue a broadcast with the admin in a normal firefox window and another user in a private window having a galaxy tab open, and the chrome user having no galaxy tab open. if i navigated to galaxy with the chrome user afterwards, a non modified notification would then pop up. if i repeated the initial conditions (two different windows with a galaxy tab open, one not), then modified the broadcast, the initial broadcast popup at the bottom with the full text in the black footer that initially popped up before the modification would remain unmodified (expected, i would imagine), but navigating to galaxy with the third user would show neither the old nor the new version of the notification. i tried it twice to be sure, but it could be that was insufficiently careful with my setup so i will give it another go, paying extra attention to the 'since'

**Comment by davelopez** [comment]
> the initial broadcast popup at the bottom with the full text in the black footer that initially popped up before the modification would remain unmodified (expected, i would imagine)

That would not be the expected behavior. If a broadcast is currently being displayed (and not dismissed) and the admin updates the exact same broadcast, the displayed broadcast should be updated too.


https://github.com/galaxyproject/galaxy/assets/46503462/111ed365-e99b-4634-9c96-85f96472b049

**Comment by luke-c-sargent** [comment]
thanks for the video, something must be wonky in my setup. i will try all this again

**Comment by luke-c-sargent** [comment]
okay, it behaved as it should upon repeating these experiments. I might have forgotten to update the expiry generated by the API docs call, and so it immediately expired... sorry to make you spend time correcting me! to be clear:
- broadcasts update in open windows, and windows opened after the mod are fine
- shows with status

... again i am going to blame my misunderstanding of how expiry works. closing this, thanks for holding my hand through the process ;)

**Comment by davelopez** [comment]
@luke-c-sargent no worries! It is always good to have a second try and I also found https://github.com/galaxyproject/galaxy/issues/16363 while testing :)

Thanks again for the detailed testing, really appreciated!
