### ISSUE TITLE
UI does not respect the default number of repeat units

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#16487]
**Describe the bug**

For a repeat `<repeat name="parameters" min="1" default="2">` the UI shows 1 repeat unit by default. It should show 2. 

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.0 at least

**To Reproduce**

Look at any tool with a repeat where `min < default` or `min` is not set and `default>0` (IUC apparently has none with this config .. so I guess this is broken since a long time).

**Expected behavior**
Show default number of repeat elements.

**Comment by bernt-matthias** [comment]
Seemed to have worked before https://github.com/galaxyproject/galaxy/issues/1016

**Comment by hujambo-dunia** [comment]
Hi @guerler, are you able to confirm @bernt-matthias' suggestion (referencing #1016) that there was a change referencing "repeating DOM elements" on your PR deleting this file `client/src/mvc/form/form-section.js` in [this commit](https://github.com/galaxyproject/galaxy/commit/da0ccbaec8dd4766f7a98be86b8a6df0900efb97#diff-1cacf7869df763d8e0724de99083e02000e5964f59cefe3faca1d646192b8a1c) (file was renamed in [this even earlier commit](https://github.com/galaxyproject/galaxy/commit/c39baff8644cbcbcb18be2b4ce1d4b5aa538dcd8))? In short, putting this file (or putting back this logic in a new file) back in place would fix the issue? Or is it more complex than that?

Cc: @dannon

**Comment by guerler** [comment]
@hujambo-dunia thank you for looking into this. The referenced PR is from 2016, a lot of things have changed since then. I'd suggest to take a look at the latest `FormRepeat` component and at `grouping.py` which should populate the default number of repeats (https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tools/parameters/grouping.py#L152).

While looking at this I noticed that the min/max attributes are not recognized either i.e. users can add more repeats, exceeding the maximum number of allowed repeats. The fix for this should be straightforward and can be handled in the Vue Component itself. We would only have to disable the `Insert repeat` button if the maximum number of repeats has been reached (`cache.length >= input.max`). Analogously we would disable the `Delete repeat` button if the minimum number of repeats has been reached.

**Comment by guerler** [comment]
@hujambo-dunia thank you for looking into this. Yes, in principle we might need to restore some of the logic from https://github.com/galaxyproject/galaxy/pull/1635/files. I'd suggest to take a look at the latest FormRepeat component but also at `grouping.py` which seems to populate the default number of repeats (https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tools/parameters/grouping.py#L152) in the backend.

While looking at this I noticed that the min/max attributes are not recognized either i.e. users can add more repeats, exceeding the maximum number of allowed repeats. The fix for this should be straightforward and can be handled in the Vue Component itself. We would only have to disable the Insert repeat button if the maximum number of repeats has been reached (cache.length >= input.max). Analogously we would disable the Delete repeat button if the minimum number of repeats has been reached.

**Comment by hujambo-dunia** [comment]
Thanks @guerler - this is all good to hear! I will do as you suggest.

**Comment by hujambo-dunia** [comment]
This has been addressed in the merged PR #17018
