### ISSUE TITLE
Can't connect text parameter to data_column parameter in workflow editor

### ISSUE THREAD

**Issue by mthang** [galaxyproject/galaxy#16491]
Hi there,
I tried to create a workflow to generate a plot that required specify columns from a table and the plotting tool (see attached screenshot) does not have the data_column type, so I can't add a tool (i.e datasest with specify number of column in the file) to connect to the y-axis column of the plotting tool.

![data_column_type](https://github.com/galaxyproject/tools-iuc/assets/19919190/31a9fa7a-8e08-49a9-aa57-161fcff18a43)

**Comment by mvdbeek** [comment]
Can you please attach a workflow or tell us which plotting tool this is ? As the editor says, you can't attach a data input to a data_column input, but as with any select or text parameter you should be able to connect a text parameter.

**Comment by mthang** [comment]
This tool , **Plotting tool** for multiple series and graph types (Galaxy Version 1.0.2), is part of the workflow (see attached) 
![workflow](https://github.com/galaxyproject/galaxy/assets/19919190/056bf1d8-e851-483c-a7ef-c6e367fddcc6)

The research who created this workflow would like to automate the task as much as possible for metagenomic data processing. One of the issue is unable to pass specify column from the output of rarefraction into the "Plotting tool" Y-axis column due to the datatype of the that column is the data_column type.

**Comment by mthang** [comment]
here's the workflowk link - https://usegalaxy.org.au/u/mike/w/workflow-6-alpha-diversity-galaxy-training-16s-microbial-analysis-with-mothur-imported-from-url

**Comment by bernt-matthias** [comment]
Did you check out the [workflow parameter tutorial](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/workflow-parameters/tutorial.html)?

**Comment by mvdbeek** [comment]
Sorry, I was being unclear here: it doesn't work, but we should fix it.

**Comment by mvdbeek** [comment]
> One of the issue is unable to pass specify column from the output of rarefraction into the "Plotting tool" Y-axis column due to the datatype of the that column is the data_column type.

I am not sure i completely follow, the data from the rarefaction tool can be passed to the plotting tool, as you're showing. What you can't do is set the columns as a parameter ... we can make it so you can connect a workflow parameter (that part needs some fixing), however I want to warn you that you'll have to specify in the workflow which columns are possible columns to select from, since we can't know which columns the rarefaction output dataset contains.

If there's only a single column that makes sense you don't need a workflow parameter, you can just set this in the workflow editor.
