### ISSUE TITLE
Workflow report content resets to default after making changes

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#16549]
**Describe the bug**
From @AnnaSyme:

> Another workflow report question - I've noticed that if I make any changes to the workflow, the workflow report content resets to the original default text. Is that meant to happen?

**Comment by mvdbeek** [comment]
Not sure if frontend or backend bug, both is a possibility.

**Comment by jmchilton** [comment]
I can't easily replicate this with 23.1 - I tried a variety of things. I'm assuming this was fixed with @mvdbeek's big workflow editor that replaced all the state handling and made things a lot more consistent by relying on Vue for managing these things.

I'm going to close this bug report for now - but please reopen if it remains an issue in Galaxy 23.1.

**Comment by AnnaSyme** [comment]
Thanks @jmchilton yes I also can't see this issue now on Galaxy 23.1 (Galaxy Eu), so it seems to be fixed, thanks.

**Comment by mvdbeek** [comment]
I think there was an additional factor here, which https://github.com/galaxyproject/galaxy/pull/17904 is going to fix.
