### ISSUE TITLE
Output extra files no longer collected

### ISSUE THREAD

**Issue by abretaud** [galaxyproject/galaxy#16890]
**Describe the bug**
Since my last update on the 23.0 branch, the extra files from tool output are no longer saved after job completion. Jobs are running in non-pulsar mode, on a standard slurm cluster.

I suspect it comes from https://github.com/galaxyproject/galaxy/pull/16541 : I tried to downgrade to the commit before this PR, and the problem is gone

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.0
Commit: ea2be33b6ec29e1290a112652698258ddaeab6a2

**To Reproduce**
1. Launch a tool like jbrowse or velveth
2. The output extra files are not collected

**Comment by mvdbeek** [comment]
Do you have a copy of galaxy on your cluster and does it need to be updated ? We've been running for quite some time in production with local and remote runners and it's working fine.

**Comment by abretaud** [comment]
Nope, no copy of the code, it's on a shared volume. I'm a bit surprised by this bug, I more cleanly reverted #16541 and it really fixes it. But I don't see why we would have a problem and not others...
I'll see if I can make more debugging later

**Comment by mvdbeek** [comment]
Did you have any time to look into this @abretaud ? What are the settings for `outputs_from_working_directory` and `object_store_store_by` ?

**Comment by abretaud** [comment]
Haven't had the time yet unfortunately, it coul take a few days...
`outputs_to_working_directory` is set to true, and `object_store_store_by` is not defined

**Comment by mvdbeek** [comment]
Can you check if datasets are stored by id or uuid (you can see that for newly created datasets if you look at the file path).

**Comment by abretaud** [comment]
Oops, sorry for the delay!
They are stored with id currently (galaxy/datasets/006/549/dataset_6549309.dat)

**Comment by mvdbeek** [comment]
This should be fixed in https://github.com/galaxyproject/galaxy/pull/17067. I'd encourage you to also consider migrating to an object store that uses the newer `store_by="uuid"` mechanism, which 
- should lead to better job throughput (since we don't need to generate a primary ids up front for every output)
- is much better tested at this point and the default when setting up a new instance
- and would allow you to also use `metadata_strategy: extended`, where dynamic outputs can be pushed to the object store by the metadata script as part of the job (instead of the job handler doing the data transfer).

You can do this migration by setting up a distributed object store as in https://training.galaxyproject.org/training-material/topics/admin/tutorials/object-store/tutorial.html#distributed-object-store and give the old object_store a weight of 0

**Comment by abretaud** [comment]
Cool thanks so much Marius!
I'll apply it shortly, and look into the object store change too

**Comment by abretaud** [comment]
I confirm that the fix works :+1:
