### ISSUE TITLE
Workflow that accepts paired input doesn't accept list:paired input

### ISSUE THREAD

**Issue by pvanheus** [galaxyproject/galaxy#1701]
Currently tools that accept paired input also accept list:paired input and operate correctly (map across the list). As of the latest dev, this doesn't seem to be true for workflows: a workflow that accepts paired only operates on a paired collection, and doesn't allow a list:paired to be selected.

**Comment by jmchilton** [comment]
Yes, this would be a nice feature for sure and the framework plumbing should mostly allow it. I don't know if I'll find time this cycle to work on it - especially because most of the work is at the top of that workflow running stack - the run workflow form and initial API entry point - both of which will be undergoing a significant overhaul with 16.04 (work started by @guerler in 16.01).

xref https://trello.com/c/WodW2sLb

**Comment by hexylena** [comment]
![image](https://user-images.githubusercontent.com/458683/62789405-24cb3200-bac9-11e9-84ee-776e76747e2a.png)

looks like this works now :)
