### ISSUE TITLE
Discovered collection output errors give little information

### ISSUE THREAD

**Issue by astrovsky01** [galaxyproject/galaxy#17121]
On a tool that has all discovered collection outputs, errors are not registering on the history UI, and are only shown as errors on the info page, which also may not give error info, depending on when the tool fails. Additionally, there is no easy way to rerun the job from the history, as the rerun button is not available. This was run on Test

<img width="1406" alt="Screenshot 2023-12-01 at 1 57 06 PM" src="https://github.com/galaxyproject/galaxy/assets/40246333/89f328f2-1353-4d37-b9fc-6dd23f37a278">

**Comment by dannon** [comment]
Can you share the history here so we can look into it?

**Comment by astrovsky01** [comment]
> Can you share the history here so we can look into it?

https://test.galaxyproject.org/u/alexo/h/collection-history

**Comment by mvdbeek** [comment]
<img width="1697" alt="Screenshot 2023-12-12 at 19 44 19" src="https://github.com/galaxyproject/galaxy/assets/6804901/ede0ce22-4aae-4571-a1ac-e1401f39c531">
this is a tool error and the traceback property is an admin only property of the job since it could contain secrets. I don't think there's anything to fix here and

**Comment by astrovsky01** [comment]
At the very least I think a rerun button would be good for jobs with many params that hit this case
