### ISSUE TITLE
Deleting a data collection with datafiles already on another data collection make this last data collection presenting data files not useable

### ISSUE THREAD

**Issue by yvanlebras** [galaxyproject/galaxy#17249]
**Describe the bug**
Deleting a data collection with datafiles already on another data collection make this last data collection presenting data files not useable

**Galaxy Version and/or server at which you observed the bug**
usegalaxy.eu in 2024/01/01

**To Reproduce**

- Upload 3 files
- Create a data collection with these 3 files
- Create another data collection with 2 of these files
- Delete the first data collection asking for deleting related datasets
- Try to access or use dataset from the second data collection

**Expected behavior**
No possibility to remove dataset already on another collection OR having a message to advertise at least?

**Comment by mvdbeek** [comment]
So this only happens when you select `Hide original elements`? (which is the default), after which point you can only reproduce this if you show the hidden datasets, then use the same datasets again with the `Hide original elements ?` set to true again. `Hide original elements` here means we simply include the original datasets in the collection, instead of making a copy and adding the copy to the collection. There's some overhead in always creating a copy, but it is surprising in a bad way that you can delete datasets from an unrelated collection, so I guess the fix is to always make a copy **and** hide the original if necessary.

**Comment by yvanlebras** [comment]
You totally right Marius on the "hide original elements statements! I was thinking that this option was "just" to hide or not related datafiles on the history view... Are you sure that in fact if we didn't select `Hide original elements`, datafiles are copied between the history view and the collection ? (I really hope this is not the case because this is not strait forward IMO). If selecting this option is not changing the "copy" state, we in fact have something like a "symbolic link" between dafiles from collections, so if we delete a collection, we can delete "symlinks" but not datafiles is already used by another collection. Furthermore, we can imagine that a datafile is used alone by a history step + be in a data collection and I don't want the datafile deleted if I want to "just" remove the collection....
