### ISSUE TITLE
Megablast has been non-functional on default cluster at http://usegalaxy.org since 10/2015

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#1745]
**Issue**

Megablast errors out, appears to be a dependency issue.

Runs fine on the local cluster.

**Error**

> python: can't open file '/galaxy/main/migrated_tools/toolshed.g2.bx.psu.edu/repos/devteam/megablast_wrapper/dc7b4acb3fa6/megablast_wrapper/megablast_wrapper.py': [Errno 2] No such file or directory
> /scratch/03166/xcgalaxy/main/staging/11850313/command.sh

**Trello**

Migrated from here: https://trello.com/c/LNSxlzGq

Note that there was an older issue (everywhere, local and default cluster), it was fixed on both clusters, but triggered this new error only at the default cluster. 

**Timeline** 

Megablast has been non-functional on Main (http://usegalaxy.org) since at least 10/2015.

**Comment by natefoo** [comment]
This is at least a twofold problem. The first is fixed in #1812.

The second is that megablast uses bx-python, which is installed into a virtualenv. This virtualenv's python overrides the Stampede environment's virtualenv, which includes all of Galaxy's dependencies that are necessary to run the set_metadata.py script after the job completes. I can't fix this by forcing `$PYTHONPATH` to include the Stampede venv's `site-packages` directory because set_metadata.py imports `routes` which imports `repoze.lru`, a namespace package, which cannot be imported directly from `$PYTHONPATH` (it only works through the magic of the virtualenv's `python`).

I was able to fix this by **manually** setting bx-python's `env.sh` to add the bx-python virtualenv to `$PYTHONPATH` and `$PATH` at the **end**. I can't think of a better way to fix this unless/until we isolate the `set_metadata.py` command in the job script. @jmchilton might have better ideas.

**Comment by jennaj** [comment]
Hi @natefoo - thanks for rooting out the core issue and completing a workaround. Do you want me to test now or wait? Test or main?

**Comment by natefoo** [comment]
It's not fixed on Main yet - could you try out a real example on Test please?

**Comment by jennaj** [comment]
On it, thanks

**Comment by jennaj** [comment]
@natefoo Megablast on Test is good.

**Comment by natefoo** [comment]
@jennaj It should now be fixed on Main as well if you'd like to test it out. My test case there worked.

**Comment by jennaj** [comment]
Short run on Main success for me too. Longer still running but it would have failed by now if was the same problem. thanks!
