### ISSUE TITLE
removing toolshed tool from favorites broken

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#17519]
this works for builtins but is broken for toolshed tools

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: main
Commit: https://github.com/galaxyproject/galaxy/commit/3450b48a5ab3b919f6c1f9cdd65d2a591ba1a805

![Screenshot 2024-02-20 at 4 09 32 PM](https://github.com/galaxyproject/galaxy/assets/1814954/710126ae-d84a-492b-af56-f4c737905cda)

**Comment by bernt-matthias** [comment]
Interesting. I recently noted that adding does not work https://github.com/galaxyproject/galaxy/issues/17150

**Comment by ahmedhamidawan** [comment]
I feel like this might be failing because we are somehow not sending an encoded `toolId` to the backend?
The response you get is:
```
No route for /api/users/f2db41e1fa331b3e/favorites/tools/toolshed.g2.bx.psu.edu/repos/galaxyp/peptide_to_gff/peptide_to_gff/1.0 
```

Even though the headers in the request are (correctly?) sent as:
```
/api/users/f2db41e1fa331b3e/favorites/tools/toolshed.g2.bx.psu.edu%2Frepos%2Fgalaxyp%2Fpeptide_to_gff%2Fpeptide_to_gff%2F1.0
```

And we don't even get to [this point](https://github.com/ahmedhamidawan/galaxy/blob/bc0d075d552cc10d9c452e9e0a4595b3e079301e/lib/galaxy/webapps/galaxy/api/users.py#L373) in execution

**Comment by ahmedhamidawan** [comment]
https://github.com/galaxyproject/galaxy/pull/17634/commits/d57341efb8cd555822a4fc7b8776f32524f413ad#diff-81f02aa7db4542a10fbd092000623dc23c2105a8b23c9a6223706bd738c90472R349

fixed this

@martenson does this seem like an appropriate solution?

**Comment by martenson** [comment]
thanks @ahmedhamidawan !
