### ISSUE TITLE
Conversion tools (e.g. tabular to csv and vice versa) are not available when building workflows

### ISSUE THREAD

**Issue by hechth** [galaxyproject/galaxy#17575]
**Describe the bug**
Conversion tools (e.g. tabular to csv and vice versa) are not available when building workflows using the UI. They are embedded in workflows though if they are used on a dataset in a history and then the extract workflow function is used.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.1.5, usegalaxy.eu

**Expected behavior**
I would expect to find the conversion tool somewhere in the tool panel when building a workflow.

**Comment by nsoranzo** [comment]
Do you have the `display_builtin_converters` option set in `config/galaxy.yml` ?

**Comment by bgruening** [comment]
Isn't it true by default? https://github.com/usegalaxy-eu/infrastructure-playbook/blob/master/group_vars/gxconfig.yml#L2485

**Comment by bernt-matthias** [comment]
Are you using the tool panel or a tool panel view in the workflow editor? If it is views then https://github.com/galaxyproject/galaxy/pull/17209 might fix it.

**Comment by hechth** [comment]
> Do you have the `display_builtin_converters` option set in `config/galaxy.yml` ?

I am not sure and will verify that.

> Are you using the tool panel or a tool panel view in the workflow editor? If it is views then https://github.com/galaxyproject/galaxy/pull/17209 might fix it.

What is the difference? I am talking about the tool panel (view?) when having the workflow editor open.

**Comment by bernt-matthias** [comment]
![Screenshot from 2024-03-07 09-29-10](https://github.com/galaxyproject/galaxy/assets/25689525/2eaf211c-e326-4e18-87f7-3ac9857a9e41)

If you checked *Full tool panel* then you see the tool panel, otherwise a tool panel view. 


Seems that EU does not have the `Built-in Converters` section in any tool panel or view (also for normal tool execution). Maybe they do not have disabled the option (unlikely) or https://github.com/galaxyproject/galaxy/pull/17209 has not arrived there yet.

If we see them in the normal tool panel we can recheck.

On ORG I see the built-in converters for normal tool execution and workflows.

**Comment by davelopez** [comment]
EU is still running version 23.1, I can see that the milestone for https://github.com/galaxyproject/galaxy/pull/17209 is 24.0 but I would think based on the merge date that it should be 23.2... :thinking:
