### ISSUE TITLE
[Feature request] Admin web interface: Ask confirmation before user delete and purge

### ISSUE THREAD

**Issue by microfuge** [galaxyproject/galaxy#17588]
Hi ,

While deleting/purging users from the Admin web interface, a "Are you sure?" dialog would be good.

**Comment by dannon** [comment]
Flagged this earlier to follow up on because I thought it might be the case -- this should actually be enabled in the latest dev (and forthcoming 24.0):

![image](https://github.com/galaxyproject/galaxy/assets/155398/4bffab8a-1c8d-4da1-8018-09296f2a794d)

Or are you referring to a different delete mechanism @microfuge?

**Comment by microfuge** [comment]
Hi @dannon ,

Thanks! I exactly meant that. I am using 23.2 and was not aware about dev/24 having this feature already. Thanks again and the issue is closed from my side.

**Comment by dannon** [comment]
@microfuge Thanks for the confirmation!
