### ISSUE TITLE
`assert_contents` skips tests if no outputs are produced

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#17829]
Might apply to more than just `assert_contents`.
See https://github.com/galaxyproject/tools-iuc/pull/5830/files#diff-495875e87b2551855bb16ba2e6be513e7517632dbaea4dc8e4c582a448061cf7R42-R61, which runs assertions against outputs that are never produced.

Tests should fail at this point, however we got a successful test output

**Comment by bernt-matthias** [comment]
The problem may actually be that Galaxy fails to prepare the jobs at all (and that this goes unnoticed). Probably because the job produces no outputs at all? Anyway we should produce an error somehow. 

If you run the test then you see 4 job working directories. The two for the actual tool runs are incomplete, e.g. no job or tool script.

**Comment by bernt-matthias** [comment]
[This assertion](https://github.com/galaxyproject/galaxy/blob/6aac46180e447ae2d70244ec77eec44abbf76e0f/lib/galaxy/tool_util/verify/interactor.py#L1432) is raised and this goes unnoticed.

**Comment by bernt-matthias** [comment]
Got it. Ended up nearly at the same as https://github.com/galaxyproject/galaxy/pull/16094, but maybe its better to move the assertion into the `_verify_outputs` function instead of removing it (the later seems to produce an error that is difficult to understand).

**Comment by mvdbeek** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/17874, but still needs new packages and https://github.com/galaxyproject/planemo/pull/1441
