### ISSUE TITLE
Incomplete hiding of intermediate jobs while using dataset collections

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/galaxy#1790]
When running tools on dataset collection there is a large list of datasets in the history corresponding to each job. These are then hidden as they migrate from scheduled to done state. On several occasions this dataset hiding process does not proceed to completion and some datasets remain in the history. 

The example below shows a collection (history item 1738) generated by running `bamLeftAlign` on a collection of BAM files. All jobs have been finished but some datasets (i.e., 1618, 1614 and so on) remain. Refreshing history does not change this. 

![screen shot 2016-02-24 at 12 04 00 pm](https://cloud.githubusercontent.com/assets/4291636/13293692/ba40f18a-daee-11e5-980a-4a45de870bf6.png)

**Comment by jxtx** [comment]
Rather than hiding, would it make more sense for the created datasets to be in a collection from the moment they are visible? I find working with this UI a bit confusing.

**Comment by jmchilton** [comment]
@jxtx Absolutely - it is/was a stop gap that they ever appeared in the history. Mostly it was done just so they have HIDs and so if there were problems people could see the problems. Now that one can dig into collections - the second half of that is not important.

Someone (me I suppose) has to work through the ramifications of having datasets in a history but not in the history (how to delete, what should be used instead of hid in dataset naming, etc...).

**Comment by jmchilton** [comment]
@jxtx I have expanded on what you said here and created an issue for this change https://github.com/galaxyproject/galaxy/issues/1810.

**Comment by mvdbeek** [comment]
One instance where this can happen is if a job finishes before the scheduling code reaches https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tools/execute.py#L198 (that is probably not the case when running BamLeftAlign ...), just stumbled across this when skipping job execution for equivalent jobs that have already been run.
