### ISSUE TITLE
No link to imported history

### ISSUE THREAD

**Issue by jgoecks** [galaxyproject/galaxy#17989]
**Describe the bug**
After importing a history, there's no clear way to navigate to the imported history.

**Galaxy Version and/or server at which you observed the bug**

https://usegalaxy.org on April 15, 2024

**Browser and Operating System**
Operating System: macOS
Browser: Chrome,

**To Reproduce**
1. Go to a shared history
2. Click on 'Import this history'
3. After import, there is no way to navigate to the history

**Expected behavior**
There should be a link that takes you to the imported history.

**Screenshots**

<img width="1110" alt="Screenshot 2024-04-15 at 4 48 12 PM" src="https://github.com/galaxyproject/galaxy/assets/882193/ba222351-e11e-4ca9-88d6-312972bed518">

**Comment by dannon** [comment]
Upon import a history is set to the active history and should be immediately reflected without any action taken.  Two quick questions: 1) did that not work, or was it just not obvious that the history should be visible?  2) if we did add a link, would a link back to the analysis interface starting point be what you want (so, showing a 'reset' view with the history visible), or, would you expect a link that showed the 'history view' in the center panel (which might be weird, since it's going to show the history in the right side history panel as well, by default)?
