### ISSUE TITLE
move workflow editor actions out of the toolform

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#18166]
These belong to the editor header, next to the undo/redo buttons

![Screenshot 2024-05-16 at 11 51 12 AM](https://github.com/galaxyproject/galaxy/assets/1814954/5af0516c-d489-4983-b404-414e650f16b7)

**Comment by ahmedhamidawan** [comment]
Would having tabs in the right panel still make sense? Since, some of these actions are tabs/actions/dropdowns:

https://github.com/galaxyproject/galaxy/assets/78516064/887ac510-3ff4-4a5d-aeb2-f8af732fe04c

**Comment by guerler** [comment]
Thanks for creating this ticket, the workflow ui does need reorganization, but instead of moving the workflow actions to the redo/undo buttons it should be the other way around. We also need to consolidate the comments tool bar with the zoom buttons and ideally move it to the bottom, so it does not jump between vertical and horizontal layout. I would even say that the redo/undo buttons should be placed in there. Right now options appear in five different spots which is confusing. We could easily consolidated by using only two horizontal bars i.e. 1) toolbar at the bottom and 2) workflow actions at the upper right.

**Comment by martenson** [comment]
@ahmedhamidawan I think I like that. I wouldn't use "lint", that is a tech term. 

I'd suggest to move out the "edit report" and "cog" contents to the workflow tab and leave only the "save" and "run" with the undo/redo.

![Screenshot 2024-05-20 at 1 59 54 PM](https://github.com/galaxyproject/galaxy/assets/1814954/359510c5-ec86-4df2-9a6c-451cd80b963d)


@guerler The save and run actions are the most important buttons imho. They should stand out and be reachable at all times. The editor should be useful when the right panel is collapsed and the focus should be on its canvas not on the side panels.
As of where the comment actions/zoom controls/etc. should go, I dare to say majority of our interfaces have actionable elements at the top of the page and workflows would imo benefit from the same.


In my mind in an ideal world the workflow editor would have no sidepanels and full width of the canvas would be occupied by the nodes and panels' functionalities folded in. Then one button would add node with a toolpanel search popping up and node details would only pop when selected.

**Comment by guerler** [comment]
@martenson I think that's what I am saying. We should have two locations instead of five and consolidate options into those. 1) toolbar at the bottom and 2) workflow actions at the upper right. Having the workflow actions merged into the title header is possible but could squeeze the title imo, but that's just a minor issue.

**Comment by ElectronicBlueberry** [comment]
> As of where the comment actions/zoom controls/etc. should go, I dare to say majority of our interfaces have actionable elements at the top of the page and workflows would imo benefit from the same.

This is also a common design pattern, which is why I'd like to stick to it. While I can think of many examples of visual editors which have some sort of tools at the top, I can't think of a single example which has it at the bottom.

I'd also argue that grouping them with the zooms controls is a net minus, as those are two very different actions. Zooming does not change the state of the workflow at all, nor does it precede an action which changes the state. I'd again like to refer to common design patterns. While zoom controls can be found in almost any corner of the window, depending on what software you look at, they are never (to my knowledge) grouped with tools/actions, for the reason outlined above.

----

#18729 enables stripping most of these actions out, and making the left panel quickly toggleable. With this issue in mind, I have the following proposal for the PR:

- Move run and save out of the right panel into the center, as suggested here.
- Move Workflow Attributes and Lint to the activity bar.
- Move Reports to the activity Bar.
- Have the right panel exclusively be a node inspector.

What I'm unsure about are the remaining actions hidden in the cog drop-down. They may work as an activity, or it could make the too hard to find. I'll give it a try and see how it feels.
