### ISSUE TITLE
import user module in tool wrapper xml

### ISSUE THREAD

**Issue by methylome** [galaxyproject/galaxy#1833]
Is it possible to import a user module in a tool wrapper xml? Although I add the directory of the module as shown in the following example, I got ImportError.

<tool id="test" name="test" version="1.0.0">
    <command>
        #import sys, os
        #$sys.path.append($os.path.dirname($os.path.dirname($os.path.abspath($**file**))))
        #from user_module import user_func
        #user_func()
    </command>

**Comment by jmchilton** [comment]
I suspect you could use `$__tool_directory__` instead of `__file__` since the latter is not the tool xml file but probably some temporary generated thing created who knows where by Cheetah. But this is a usage pattern the Galaxy team probably wants to very actively discourage. I would encourage you to write out a config file of some sort or the other and do this processing in the job instead of before the job.

**Comment by methylome** [comment]
_tool_directory and even hard coded path didn't work. I will try a config file.
Thanks.

**Comment by methylome** [comment]
@jmchilton Is there any way to get the URL or prefix of a galaxy instance in tool wrapper? I guessed something like $**app**.config.get('prefix', '')
