### ISSUE TITLE
Identified Performance and UX Challenges

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#1856]
### UX/perf problems mainly related to and reported from Main:

**probably history-size related:**
- [ ] if you try to edit WF and your current history is huge it will never load/crash
  - https://github.com/galaxyproject/galaxy/pull/1861
- 35k items history often does not load or crashes the browser (preferably _out-of-memory_)
- _saved histories_ page
  - loading is slow if you have histories with 40k items 
  - when you click to _switch as current_ it does that quickly but also tries to refresh the numbers of green/red datasets of all histories which is very slow
  - ~~there used to be indicator of state _new_ datasets but is not there anymore~~
  - besides red/green indicators others would be useful (waiting, queued...)
- opening toolform can be slow with large histories causing a bad UX - user clicks again on the link, enters params in the form and then the form gets overridden by the second click's response (maybe provide load indicator?)

**other**
- landing page https://usegalaxy.org/ takes 6s
- opening **published workflows** list takes 33s (it lakes paging) https://usegalaxy.org/workflow/list_published
- opening **published pages** list takes 11s https://usegalaxy.org/page/list_published
- FTP upload/import of many items has bad UX (https://github.com/galaxyproject/galaxy/issues/1090)
-  [ ] job scheduling slow on Galaxy's side 
  - https://github.com/galaxyproject/galaxy/issues/1831
- missing UI to monitor and control WFs
- job query on Main is slow (20-30s) even for the tiniest of jobs 
- _set_metadata_ still proves problematic and slow, maybe we can offload small files detection (<1MB ?) to be run on Galaxy itself and/or have a dedicated daemon so we do not have to load the needed code for each dataset
### ideas
- instrument server (and client side) to better track problematic requests/operations
- are some requests considerably slower when user is an admin?

**Comment by dannon** [comment]
@martenson Thanks for taking these notes.  https://github.com/galaxyproject/galaxy/blob/dev/config/galaxy.ini.sample#L732 is the request duration logging I mentioned on the call, we just need a little infrastructure set up to use it.

**Comment by carlfeberhard** [comment]
> there used to be indicator of state new datasets but is not there anymore

I thought this was a recent lack of queued datasets, not new - or rather that it never displayed new and still displays queued, but queued is more often set as new now (rightly AFAIK).

**Comment by martenson** [comment]
@carlfeberhard please modify as you feel is right, I am pretty sure I did not catch that one properly
ping @blankenberg

**Comment by jennaj** [comment]
@martenson Please add in that importing histories over 300 datasets will currently fail. Possibly related to other items (35k items), but should be a test case. I can provide example history one is if needed. Is a bug import or shared history import - perhaps these route through a different mechanisms. 

Note that the actual number of datasets may not be the root issue - rather the _size_ of the datasets and overall history is the key factor to consider (agrees with out-of-memory suspicion of load failure trigger). 

And last, what I tried to communicate with this: https://github.com/jennaj/support-known-issues/wiki
is that key tools are non-functional due to dependency issues on main and have been for a while. Would be good put a priority on these individual tickets, to set expectations for users that are tracking. Sorry if this is a pain (and doesn't belong exactly here in this ticket), but are important for main in general - so maybe is worth tracking as a group.

**Comment by blankenberg** [comment]
> > there used to be indicator of state new datasets but is not there anymore
> 
> I thought this was a recent lack of queued datasets, not new - or rather that it never displayed new and still displays queued, but queued is more often set as new now (rightly AFAIK).

Right. All datasets used to enter the 'queued' state immediately. Now they enter and stay in the 'new' state until the job is actually queued for execution (i.e. after all input datasets have finished); basically the datasets are in a 'waiting' state, which is useful to know as an overview of the history state -- lumping them in with queued (like before, because state was set to queued) gives an indication of how much of a workflow/job set still needs to run; having them listed as a separate item might be even better, but at least they should show up somewhere in the overview of the history.

**Comment by martenson** [comment]
I think we actually address 99% of these. Good job everybody!
