### ISSUE TITLE
Creating a new workflow + saving it has some odd UX

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#18609]
**Describe the bug**

the following was reported to me

> When you change the name on a new (unnamed) workflow. It should prompt and save (edited) 
> When you renamed the worfklow It didn't save. And then it said "create new workflow" when you mouse over the save icon so it wasn't clear how to save changes (edited) 

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version:  24.1.2.dev0

**Browser and Operating System**
Operating System: Linux
Browser: Firefox

**To Reproduce**

1. Go to your workflows list
2. create a new workflow
3. you're in the editor, cool
4. Change the workflow title
5. :lady_beetle: **Notice**: the save button says "create new workflow" which is odd, I just did that, didn't I?
6. Without saving open the help tab because you want to report a new issue
7. :lady_beetle: Ctrl-click the 'about' item and note that it doesn't open in a new tab, instead it opens in the current window
    8. :lady_beetle: and it opens immediately, the popup for "unsaved changes" is not shown
9. Copy the version and navigate back to your workflow
10. Because you didn't save, and the popup didn't show of "unsaved changes", that state was lost

You can fill out; title, description, license, creator information, and tags. The workflow editor doesn't show a "unsaved changes" popup.

**Expected behavior**

0. The text on a new workflow's 'save' button should be "save workflow" not "create new"
1. Changes to title/description/license/creators/tags should mark the form as dirty and at least pop up before navigating
    2. This could also be solved by when I click 'create workflow' creating a new workflow and immediately saving it. (though I'm guessing this change was made intentionally to stop cluttering the user's accounts with empty/untouched workflows?)
3. Ctrl clicking links should work

**Screenshots**

**Additional context**

**Comment by ahmedhamidawan** [comment]
Thank you for reporting this, there are a couple bugs here, and maybe potential improvements in UX needed.

> 4. Change the workflow title
> 5. 🐞 Notice: the save button says "create new workflow" which is odd, I just did that, didn't I?

The reason for this is that in this change: [Remove "Create Workflow" form and allow workflow creation in editor](https://github.com/galaxyproject/galaxy/pull/16938), this interface was changed to work as follows:
- You click on `+ Create` in the workflows grid, and it takes you to an empty workflow editor **(note that a new workflow hasn't been created as of yet)**
- From there, a new workflow will not be created **_until_** the user clicks save the first time.

### Potential UX improvements:
This is probably not intuitive for users and so maybe:
- Instead of `+ Create` button in the workflows grid, it should say something else which indicates a workflow will not be immediately created, and an empty editor will be opened by default.
- Maybe, for a fresh, unsaved/uncreated workflow editor, instead of save in the right panel, the button should have a different icon and tooltip that is highlighted and shouts at the user to remind them that workflow hasn't been created until they click it.

### Bugs discovered/noted here:
1. Now, the confirmation dialogue does show up once you add a node to the editor itself, but it definitely doesn't show up for the attributes section in the right panel (for name, annotation etc.). That is a bug🐞 
2. Ctrl-Click on masthead action items is not opening in new tab (from any interface/view, not just the editor) 🐞

**Comment by hexylena** [comment]
> The reason for this is that in this change: https://github.com/galaxyproject/galaxy/pull/16938, this interface was changed to work as follows:

totally makes sense for technical reasons, just the text itself was confusing for the user reporting it to me (and I can sympathise.) Maybe the distinction in the button text isn't important to communicate though? it isn't important that the user have to understand that the first "create workflow" didn't actually create something, and the button text can be "save new workflow" or something if it has to be different than subsequent saves?
