### ISSUE TITLE
Job execution notification emails do not generate accurate URLs for jobs.

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/galaxy#18747]
**Describe the bug**
When an email is sent to notify the user that a job has completed, the link to the job uses the `galaxy_infrastructure_url`, which is not always appropriate. Instead, it should use `url_for`.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.05 (expect it to exist on 24.1 and up as well)

**Browser and Operating System**
Operating System: Windows, Linux, macOS (all)
Browser: Firefox, Chrome, Chrome-based, Safari (all)

**To Reproduce**
1. Run a job and select email notification when complete
2. The URLs in the email will be to `localhost` or whatever `galaxy_infrastructure_url` is set to.

**Expected behavior**
The URL should use the appropriate server address. The [`galaxy_infrastructure_url` is only intended to be used by internal services](https://docs.galaxyproject.org/en/master/admin/config.html#galaxy-infrastructure-url).

**Additional context**
The post execution job action uses `galaxy_infrastructure_url`.
https://github.com/galaxyproject/galaxy/blob/fb4d5beb4860b860f64ebeb04a3b9863d93d006a/lib/galaxy/job_execution/actions/post.py#L58-L61

Instead, it should use `url_for` which is done in the error reporting emails.
https://github.com/galaxyproject/galaxy/blob/fb4d5beb4860b860f64ebeb04a3b9863d93d006a/lib/galaxy/tools/errors.py#L164-L166

**Comment by mvdbeek** [comment]
Hey @lparsons, that is not possible unfortunately, url_for only works in a web context that is not available in the job and workflow runners where these are used. The error report emails are handled within the web context, that's why they can use url_for. This is the relevant work to move it over: https://github.com/galaxyproject/galaxy/pull/18576.

Realistically there's only a problem with `galaxy_infrastructure_url ` if it is set to a trlu internal URL for ITs or pulsar that is distinct from the public fqdn.

**Comment by lparsons** [comment]
Thanks @mvdbeek. I didn't realize the issue with using `url_for`, that's too bad. We never had `galaxy_infrastrucutre_url` set since it didn't seem necessary, and the default is technically correct (localhost), however, it caused the links to be broken. I guess going forward we'll just make sure to set it to the public URL instead.
