### ISSUE TITLE
Difference  between conda and the singularity image generated in https://depot.galaxyproject.org

### ISSUE THREAD

**Issue by lindenb** [galaxyproject/galaxy#18761]
Hi all,
I'm trying to run a **nf-core** module that use the following recipe: https://github.com/bioconda/bioconda-recipes/blob/66c809b19344d7322e74375327bd1e4af323fb4e/recipes/jvarkit/meta.yaml#L30

```yaml
(...)
  run:
    - openjdk >=11
    - samtools >=1.20
    - bcftools >=1.20
(...)
```

when I run my module with nf-core with **conda** , i've got no problem.

But when I run the same test with the **singularity** image generated by **galaxy**: https://depot.galaxyproject.org/singularity/jvarkit:2024.08.25--hdfd78af_0', I get the following error: `bcftools: command not found`

So it looks like that the singularity image is lacking the tools required by the module ?

Another test:

```bash
$ wget -O test.img "https://depot.galaxyproject.org/singularity/jvarkit:2024.08.25--hdfd78af_0"
$ apptainer shell test.img
Singularity> which jvarkit
/usr/local/bin/jvarkit
Singularity> which bcftools
Singularity> 
```

Thanks for your help,
P.

**Comment by nsoranzo** [comment]
@lindenb Thanks for the issue, but this has nothing to do with Galaxy. I've just created a fresh conda environment for jvarkit 2024.08.25 and it doesn't install neither samtools nor bcftools because https://github.com/bioconda/bioconda-recipes/pull/50305 was merged after https://github.com/bioconda/bioconda-recipes/pull/50306 without a build number bump, so the conda package on anaconda servers doesn't actually contain the 2 new run requirements.
Just open a PR on bioconda-recipes repo bumping the build number and it should be solved.
