### ISSUE TITLE
collapse all / expand all datasets button

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#18894]
In other apps some history-like interfaces have the collapse all / expand all buttons available to quickly open or close all elements. Would it make sense to have these in Galaxy?

**Comment by davelopez** [comment]
We already have the "collapse all" button next to the selector, and I guess we didn't add the "expand all" intentionally because of large histories. It can potentially be really unresponsive because on every update we will poll for too much data.

Maybe we can allow it for small histories, but then it will work inconsistently with big histories where it is probably a no-go :disappointed:

**Comment by martenson** [comment]
TIL 🤣
