### ISSUE TITLE
ipynb files cannot be uploaded into Galaxy

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/galaxy#1922]
They appear green in history with the following message: `The uploaded file contains inappropriate HTML content`.

**Comment by hexylena** [comment]
cc @dannon @blankenberg @jmchilton @bgruening @natefoo 

Here are the options:
- processing step (like bam sorting on upload???) to strip out output cells from notebooks
- bleach/strip HTML content, rather than killing the job completely
- https://github.com/galaxyproject/galaxy/issues/1932 serve user content from a separate domain, allowing us to forgo stripping content.

**Comment by bgruening** [comment]
Here is code to strip out the uploads. I think we should indicate this to the user, he probably expects some nice figures in it.

This gist:
https://gist.github.com/minrk/6176788
ended up in https://pypi.python.org/pypi/nbstripout/0.2.0

**Comment by martenson** [comment]
This is currently working. Closing.
![Galaxy](https://user-images.githubusercontent.com/1814954/121351197-cc1a8980-c92b-11eb-9d0e-307886631a2b.png)
