### ISSUE TITLE
Question regarding usage of "options from_dataset"

### ISSUE THREAD

**Issue by george-weingart** [galaxyproject/galaxy#19368]
Hello Galaxy Forum,
I have a question regarding usage of the "options from_dataset" field 
See enclosed pdf
Thanks !
George Weingart PhD
Huttenhower Lab
Harvard School of Public Health

**Comment by george-weingart** [comment]
[Galaxy_Forum_Question_DT20241223_George_Weingart_V2.pdf](https://github.com/user-attachments/files/18233766/Galaxy_Forum_Question_DT20241223_George_Weingart_V2.pdf)

**Comment by bernt-matthias** [comment]
This is more a question for the tool dev/IUC matrix channel.

To me it seems that the user has no choice here anyway, but the three values should be derived from the input file within the R script?

Closing this. Feel free to reopen if you don't know the matrix channels yet. Could not post a link directly, since I'm traveling.

**Comment by bernt-matthias** [comment]
Otherwise make the 2nd and 3rd select optional?
