### ISSUE TITLE
Galaxy reports a missing dependency for outdated package

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#2049]
reported by @richard-burhans 
- install an older revision of https://toolshed.g2.bx.psu.edu/view/iuc/package_libcurl_7_35/0d934b13250c that still listed openssl package as its dependency
- during installation package_openssl will get installed
- update the package_libcurl_7_35 to the newest revision that does not require openssl anymore
- uninstall package_openssl as it is not needed
- observe that in the admin panel package_libcurl_7_35 now has missing dependencies 

note that package_libcurl_7_35 is working fine (in runtime depends on system-ssl as designed)

**Comment by mvdbeek** [comment]
This is partly fixed with a series of fixes by @gregvonkuster and me.
Specifically missing from 16.01 is this one https://github.com/galaxyproject/galaxy/pull/1850
I will try to reproduce with dev to make sure this works fine now. It might be possible that an explicit repair of package_libcurl_7_35 after the whole install/uninstall procedure is still required.
xref https://github.com/galaxyproject/tools-iuc/issues/631 and http://dev.list.galaxyproject.org/perl-version-5-18-1-repository-error-td4669203.html

**Comment by martenson** [comment]
thanks @mvdbeek - I was about to explore your commits because I remember you dealing with it

**Comment by mvdbeek** [comment]
May or may not be fixed, but if it isn't we're not going to fix it. Packages are dead :).
