### ISSUE TITLE
"Trim leading or trailing characters" fails with option to specify input is fastq, impacts http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#2245]
**Issue**

Using the form option "Is input dataset in fastq format? Yes" triggers this error:

> Traceback (most recent call last):
>   File "/cvmfs/main.galaxyproject.org/galaxy/tools/filters/trimmer.py", line 111, in <module>
>     main()
>   File "/cvmfs/main.galaxyproject.org/galaxy/tools/filters/trimmer.py", line 75, in main
>     invalid_starts[i] = chr( int( item ) )
> ValueError: invalid literal for int() with base 10: '-q'

**Option introduced here**, but latter changes seem to have broken how this functionality works, used to be fine .. linked to 16.04 or subsequent tool updates ??

https://github.com/galaxyproject/galaxy/commit/aaff3baf522bb001607093ad14ddd0335dc316c7

**Impacts Main and core Galaxy installs (locals). Not tested on Cloudman.**

Tool is part of Galaxy distribution

**WORK-Around (updated)**

If working on Galaxy Main, try another trimming tool from the tool group "NGS: QC and manipulation". If working in a local/cloud Galaxy, install your favorite of these tools onto your own server.

**Reported by**

https://biostar.usegalaxy.org/p/17217/

**Comment by nsoranzo** [comment]
@jennaj Testing a patch now.

**Comment by nsoranzo** [comment]
Actually this should be already fixed with commit e5b3c94c5e03a963059a58243858b7244508fb63, but Galaxy main may have not been updated yet, ping @natefoo.

On the other end, the trim wrapper should probably be updated to be more robust, a PR is coming for this.

**Comment by guerler** [comment]
Thanks @nsoranzo

**Comment by nsoranzo** [comment]
@jennaj Trim tool robustness should be increased by #2248 (which targets the dev branch, since the reported bug has been already fixed in 16.04).

**Comment by jameskim0903** [comment]
Hi @nsoranzo, thanks for helping on this issue.

If you go to usegalaxy.org, right below the header it says :
"We have updated Galaxy to the forthcoming **16.04 release** and made some configuration and  deployment changes, so you may encounter a few problems. We are working on these, and please feel free to report any errors you encounter."

I believe this means galaxy is already updated to 16.04. However, we're still seeing this issue. I'm unsure if this bug has been fixed in 16.04 (as you said in the comment above). Would this be fixed when #2248 is pushed? Or is more debugging needed from your side?

The "WORK-around" that was mentioned on the top seems to have an issue as well. See the comment here: https://biostar.usegalaxy.org/p/17217/#17227

**Comment by jennaj** [comment]
@jameskim0903 Yes, the work-around was bad. I updated it. ... (rats - I knew this!)

@nsoranzo Main is running at 16.04 but was last updated 10 days ago from what I know. 

Nate and Sam seem to be on it. Once on Main, I'll test (along with whoever beats me to it!)

**Comment by martenson** [comment]
This is now on Main, please retest @jennaj

**Comment by yenaoh90** [comment]
Trim works perfectly now.Thanks everyone for your input. Really appreciate it!
