### ISSUE TITLE
Changing workflow input type causes some tools to no longer accept the input

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/galaxy#2315]
Steps to reproduce:
1. Create workflow with Input (List), Tophat (single end), FastQC. 
2. Connect Input to Tophat and FastQC.
3. Save workflow, close.
4. Reopen workflow.
5. Remove connections from input to Tophat and FastQC.
6. Change Tophat option to paired
7. Change Input type to (paired list)
8. Connect Input to FastQC (works)
9. **Connect Input to Tophat (not allowed)**
10. Add new Tophat tool
11. Connect Input to new Tophat tool (works).

**Comment by jmchilton** [comment]
This is the expected behavior. The input dataset collection has collection type ``list`` - so you could connect it to a single data input, a multiple data input, or a collection input of type ``list``. Tophat's 'paired list' input is of collection type ``paired`` - so inputs of collection type ``paired``, ``list:paired``, ``list:list:paired`` could connect to it - but not a ``list`` input. The suffix needs to be the same - since this makes it clear how to "map" over the structure above that in the hierarchy. Galaxy doesn't know how to warp the list structure into the paired structure as you are requesting here.

Feel free to re-open if I missed something or with a clarification.
