### ISSUE TITLE
LEfse errors

### ISSUE THREAD

**Issue by rohan7293** [galaxyproject/galaxy#2425]
Hi,

whenever I uplad my file to run LEfse (format data for Lefse step to be exact)on it I get an error , (my file is in the correct format).Im not even able to report the error. Is there any reason for this and how do I fix it? 

Traceback (most recent call last):
  File "/net/rcstore02/ifs/rc_labs/galaxy/www/galaxy_hutlab14/shed_tools/toolshed.g2.bx.psu.edu/repos/george-weingart/lefse/db64b6287cd6/lefse/home/ubuntu/lefse_to_export/format_input.py", line 435, in <module>
    feats = numerical_values(feats,params['norm_v'])
  File "/net/rcstore02/ifs/rc_labs/galaxy/www/galaxy_hutlab14/shed_tools/toolshed.g2.bx.psu.edu/repos/george-weingart/lefse/db64b6287cd6/lefse/home/ubuntu/lefse_to_export/format_input.py", line 174, in numerical_values
    feats[k] = [float(val) for val in v]
ValueError: could not convert string to float: A

Thanks 
Rohan

**Comment by jenlang** [comment]
I've got a similar error. I keep finding this question in multiple places but no answer. Help would be much appreciated!

Traceback (most recent call last):
  File "/shed_tools/testtoolshed.g2.bx.psu.edu/repos/george-weingart/lefse/a6284ef17bf3/lefse/format_input.py", line 435, in <module>
    feats = numerical_values(feats,params['norm_v'])
  File "/shed_tools/testtoolshed

More specifically what does the  **feats = numerical_values(feats,params['norm_v'])** mean. I can't figure it out and can't find anywhere else explaining it. 

I downloaded the 73.txt file of example data and that works fine. I tried a different file of mine that I used previously in LEfSe but I'm now getting the same error. I don't remember changing the file in anyway so I don't know why its giving me an error when I used it fine previously. I just want to fix what is causing the problem but the error isn't telling me what the problem is!

**Comment by nsoranzo** [comment]
Unfortunately these errors seem to come from the lefse tool, not Galaxy, so you should report these problems to the author George Weingart https://huttenhower.sph.harvard.edu/people

Sorry we cannot help more.

**Comment by jjovelc** [comment]
The problem is originated by special characters in the metadata. Eliminate ALL special characters and it should work. Keep format as simple as posible; e.g.:

class group1 group1 group1 group2 group2 group2
tax1 #.### #.### #.### #.### #.### #.###...

**Comment by marina-yurieva** [comment]
I had that error when I forgot to specify a row for the subject

**Comment by JayanthiGangiredla** [comment]
I am having an issue with galaxy version of Lefse since the time we upgrade the galaxy version to python 3. Not sure whom to contact regarding this.

**Comment by mvdbeek** [comment]
We are not maintaining lefse, you could try to contact someone from the huttenhower lab: https://huttenhower.sph.harvard.edu/people
