### ISSUE TITLE
Reimplement dataset matchers in Javascript to improve content selector performance?

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#2449]
UI content selectors currently receive the available dataset and collection options from the backend:
https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tools/parameters/basic.py#L2053
We need to review the benefits of replacing the backend filtering with front-end filtering and potentially reimplement the dataset matchers in the front-end.

**Comment by martenson** [comment]
Reimplementing the dataset matcher in the front end might be troublesome due to history switching to non-complete representations (pagination or similar). 

It seems that we either make the Python filtering faster or change the paradigm (e.g. you will search for the datasets, not select them - thus you can limit the datasets in the history by query string first (cheap) and type later(expensive))

**Comment by guerler** [comment]
Sounds good to me.

**Comment by guerler** [comment]
Closing this, since the discussion here is reflected in other issues related to the advanced dataset picker and central storage.
