### ISSUE TITLE
Galaxy no longer respects <param id="drmaa_library_path">

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/galaxy#2463]
Due to switching Galaxy to use Pulsar's DRMAA code in #2102, Galaxy will only use the drmaa library set in the `DRMAA_LIBRARY_PATH` environment variable or the default one (e.g. `/usr/lib(64)/libdrmaa.so`). This regression prevent the use of multiple drmaa runners.

**Comment by natefoo** [comment]
Ping @nsoranzo and @chambm as I believe both of you encountered this.

**Comment by nsoranzo** [comment]
Indeed, I just commented there https://github.com/galaxyproject/galaxy/pull/2102#issuecomment-224355900 .

**Comment by natefoo** [comment]
What's strange is that `$DRMAA_LIBRARY_PATH` comes from the Python drmaa module and so should not be Pulsar or Galaxy specific. Indeed, Pulsar has a facility to set it when you start Pulsar the old fashioned way: https://github.com/galaxyproject/pulsar/blob/master/local_env.sh.sample

**Comment by nsoranzo** [comment]
@natefoo Sorry, I was wrong, DRMAA_LIBRARY_PATH is indeed still respected and working. After modifying the `environment` directive of `supervisord.conf` I restarted Galaxy through `supervisorctl` instead of reloading `supervisord`, after reloading it is ok.

I updated the issue title and description.

**Comment by martenson** [comment]
fixed via #2466 I think
