### ISSUE TITLE
Htseq-count does not report standardized memory failure error message at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#2532]
**Not true for all memory failures**

Specifically: No failures with this error message, for this tool, have been reported prior to the original date of this issue post.

This tool fails for many users .. see this ticket about the request for a memory bump
 https://github.com/galaxyproject/galaxy/issues/2501

**Q: Does this belong in the galaxy repo or the tool repo?**

**Example of the alternate error message**

> job stderr:
> Fatal error: Unknown error occured
> 4085 GFF lines processed.
> 100000 SAM alignment record pairs processed.
> Error occured when processing SAM input (record #3225944 in file /galaxy-repl/main/files/XXX/XXX/dataset_XXX.dat):
>   Maximum alignment buffer size exceeded while pairing SAM alignments.
>   [Exception type: ValueError, raised in **init**.py:671]

**What we usually include** 

Note: Retaining other details are helpful, so this is an addition.

The full error message will be reported as below, and can be found by clicking on the bug icon for a failed job run (red dataset):

> job info:
> This job was terminated because it used more memory than it was allocated.
> Please click the bug icon to report this problem if you need help.

On rare cases when the memory quota is exceeded very quickly, an error message such as the following can appear. 

> job stderr:
> Fatal error: Exit code 1 ()
> Traceback (most recent call last):
> (other lines)
> Memory Error

**Comment by pvanheus** [comment]
@jennaj do you ever see this with a dataset that remains green even while failed?

**Comment by jennaj** [comment]
@pvanheus Peter, this sounds like another recent problem, but I thnk that was another tool (will double check). Have you seen that kind of behavior?

**Comment by natefoo** [comment]
These differences in errors occur due to the different ways that memory limits are reached. A bit of hopefully helpful explanation:
1. > Maximum alignment buffer size exceeded while pairing SAM alignments.
   > [Exception type: ValueError, raised in init.py:671]
   
   This appears to be the tool itself catching itself using too much memory. Apparently it's allocated buffers of a certain size and the job results in an attempt to use more memory than the buffers the tool allocated.
2. > job info:
   > This job was terminated because it used more memory than it was allocated.
   > Please click the bug icon to report this problem if you need help.
   
   This means that Slurm killed the job because it used more than its allocation (8GB).
3. > Memory Error
   
   This means that the kernel killed the job because the memory on the entire system was exhausted. This probably happened because the job was running on a node with other jobs, quickly consumed over 8GB, and hit the system's memory limit before Slurm's periodic memory checks noticed and caught the job.

In theory the tool wrapper could catch the 1st and 3rd messages in the output and output a more user-friendly message, although I think we need to make this much simpler for tool developers by adding terminal state assertions to the tool framework. Something like "if this message is in the output it means 'out of memory'," which allows the job system to make immediate decisions (e.g. rerunning the job with a larger allocation) and provide unified messaging to the user. This should get it's own issue if there isn't one already.

As mentioned in #2501, I have now increased the memory allocation for this tool to 16GB.

**Comment by gregvonkuster** [comment]
Thanks a bunch @natefoo - this information is very helpful!

**Comment by jennaj** [comment]
Thanks @natefoo definitely helpful! I'll captures these and add to the wiki we share with users when there is a memory problem. I like your idea of simplifying - you'll make the ticket? Could you link that here so there is some user-impact context when it is done/tested?

**Comment by natefoo** [comment]
@jennaj I created one in #3107.

**Comment by pvanheus** [comment]
@jennaj my error was similar to what @natefoo listed as failure mode (2). Specifically this happened with SGE on our cluster  - a cufflinks job ran for 8 hours and was then killed because it hit a hard wallclock limit. In the `qacct` report the job was listed as 

```
failed 100 : assumedly after job
exit_status 137
```

And the resulting dataset was green with an empty output file.

**Comment by natefoo** [comment]
@pvanheus does the tool wrapper detect failure on stderr and was anything set on stderr? Or does it use exit codes?

**Comment by pvanheus** [comment]
@natefoo the tool wrapper cannot detect failure because the tool is terminated by the scheduler. This should set an exit code that Galaxy picks up though.

**Comment by natefoo** [comment]
If the tool has <stdio> tags handling the exit code this should happen. Are you using the devteam version of the cufflinks wrapper?

Sometimes the scheduler writes to stderr when the job, sounds like SGE doesn't do this unfortunately. =( Can it be configured to do it? That'd take care of any tools which don't use the exit code to determine failure.

**Comment by bernt-matthias** [comment]
Flexible stdio and exit code handling can now a days be defined in tools. Also runner and tool stderr is now well separated to the best of my knowledge.
