### ISSUE TITLE
DEFAULT_JOB_FILE_TEMPLATE.sh doesn't set TMPDIR

### ISSUE THREAD

**Issue by pvanheus** [galaxyproject/galaxy#2583]
The DEFAULT_JOB_FILE_TEMPLATE.sh doesn't set TMPDIR with the result that when tools (such as converters) use sort, /tmp is used as the home for temporary files, often with the result that the job runs out of disk space.

Proposed fix: set TMPDIR to $working_directory/tmp and create this directory. Comments appreciated.

**Comment by osallou** [comment]
+1

**Comment by nsoranzo** [comment]
Environment variables can be defined per destination in job_conf.xml , which I think is a better approach.

**Comment by pvanheus** [comment]
@nsoranzo indeed they can. Perhaps this could be shown in the sample files with a comment describing its purpose. The current situation leads to Galaxy failing in its default configuration for some users.

**Comment by natefoo** [comment]
On Galaxy Main we set `$TEMP` and `$TMPDIR` in job destinations. [Here](https://github.com/galaxyproject/usegalaxy-playbook/blob/2e3403866b618fa15a9cc34b8c6e1bb8d30c6113/templates/galaxy/usegalaxy.org/config/job_conf.xml.j2#L400) it's set to Pulsar's job cwd for Jetstream jobs and [here](https://github.com/galaxyproject/usegalaxy-playbook/blob/2e3403866b618fa15a9cc34b8c6e1bb8d30c6113/templates/galaxy/usegalaxy.org/config/job_conf.xml.j2#L266) it's set to a cluster-wide NFS directory for "local cluster" jobs.

Personally I think the isolated per-job `$TEMP` and `$TMPDIR` are the ideal situation (@nsoranzo pointed me at this issue because `/galaxy/scratch/main` is currently so full of job stuff despite running `tmpwatch ... 14d` on it nightly that it's affecting web worker performance since `$TEMP` is the same dir for the Galaxy server). However, the hack we've used for Jetstream should probably be standardized into a job destination param like:

```xml
    <param id="tmp_dir">/abs/path/to/dir</param> <!-- flat dir -->
    <param id="tmp_dir" append_job_id="True">/abs/path/to/dir/</param> <!-- /abs/path/to/dir/12345 -->
    <param id="tmp_dir">working</param> <!-- magical value for <job_working_dir>/_galaxy_tmp or something like that -->
```

**Comment by natefoo** [comment]
Forgot to add, I presume that "magic" setting would work for you @pvanheus? The question then is whether it should be the default or we should continue to leave `$TEMP` and `$TMPDIR` untouched by default as we do now. The argument against defaulting to "set" is that some cluster admins set these to cluster scratch and it may not be a good idea to override them.

**Comment by nsoranzo** [comment]
I don't think we should change them by default.

**Comment by jmchilton** [comment]
It shouldn't be ``$working_dir/tmp`` since tools are guaranteed clean working directories as of Galaxy 16.04 - it should be ``$job_dir/tmp``.

I'll quote pieces of the CWL spec that we should align with (http://www.commonwl.org/v1.0/CommandLineTool.html):

> Files may also be written to the designated temporary directory. This directory must be isolated and not shared with other processes. Any files written to the designated temporary directory may be automatically deleted by the workflow platform immediately after the tool terminate
 
> TMPDIR must be set to the designated temporary directory.

We should extend this to TMP and TEMP.

**Comment by natefoo** [comment]
Yeah sorry for my loose usage of terminology ("job working dir" is the name of the parent directory of all job dirs/working dirs). Agreed it should be in `$job_dir`.

**Comment by pvanheus** [comment]
Agreed @natefoo and @jmchilton, this would work well for us because it keeps things in the shared storage where `$job_dir` is located.

**Comment by hexylena** [comment]
Hi all, is this still an issue? I think `tmp_dir` and some magic are discussed in the job conf?

**Comment by natefoo** [comment]
Yes, this should all be addressed with [`tmp_dir`, documented in the job conf](https://github.com/galaxyproject/galaxy/blob/0daa4aa2e42bc38ec5f57d7b4dc0f40c8406b346/lib/galaxy/config/sample/job_conf.sample.yml#L686)
