### ISSUE TITLE
Randomly labelled empty files that are not empty

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#2598]
One of our users is running a long workflow with 400 steps. Sometimes it runs perfectly fine, sometimes we get 1-3 error messages per workflow.

The mistake is always the same:
One of the commands (command 1, it can be "join" or "compute" or "group") in the workflow chain gives an "empty" output, and than the next command in the chain (command 2, it can be "compute" or "join" or "group") gives an error message.

Curiously, the output of the command 1 is not empty and seems to be perfectly fine. Command 1 does what it has to do, but the output is labelled "empty".

Has anyone seen this before? This is with 16.04.

**Comment by gregvonkuster** [comment]
Does the workflow include tools that produce dataset collections on output?

**Comment by bgruening** [comment]
No single files, very basic - just a huge workflow.

**Comment by mvdbeek** [comment]
I have seen this happening when NFS is slow to update the file attributes. Galaxy does create an empty file for each normal output before running the job, so I guess this is what's happening. This can often be fixed by setting https://github.com/galaxyproject/galaxy/blob/b149399fee97cacb16024dc4ecb4c00394de7e0b/config/galaxy.yml.sample#L1589 and/or adding to -noac NFS mount option. 

I'm gonna close this since this is pretty old and hasn't seen any updates, but feel free to reopen if it happens again.
