### ISSUE TITLE
Bedtools SpacingBed has dependency/config issues at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#2640]
SpacingBed (Galaxy Version 2.24.0)

Tool fails on all input types with this error:

<img width="350" alt="screen shot 2016-07-20 at 2 54 43 pm" src="https://cloud.githubusercontent.com/assets/8999735/17004466/f12a3a3a-4e89-11e6-907b-7fd10421b801.png">

Test history:  https://usegalaxy.org/u/jen/h/spacingbed-error-test-history

Reported via galaxy-bugs

**Comment by nsoranzo** [comment]
As can be seen by the job info, the wrapper requires bedtools v.2.24, but bedtools v2.16.1 is loaded instead. I suppose it's a problem with dependencies on Main, ping @martenson.

**Comment by martenson** [comment]
there are only bedtools 2.22 and 2.24 installed on Main... :/

**Comment by martenson** [comment]
the earliest iuc version (https://toolshed.g2.bx.psu.edu/view/iuc/bedtools/8e6b7c3597a8) is 2.19

**Comment by martenson** [comment]
this affects all bedtools; see the linked issue above

**Comment by natefoo** [comment]
The bedtools dependency for `package_bedtools_2_24` had actually failed to install because zlib headers were not available in the installer image. I installed `zlib-devel` from yum in the build container and reinstalled the dependency and this tool (and presumably other broken bedtools) should be fixed. Rerunning the job in the test history was successful.

**Comment by jennaj** [comment]
@natefoo I'm checking too - will close if fixed

**Comment by jennaj** [comment]
Fixed!!
