### ISSUE TITLE
Add "Job Resource Parameters" for more tools at http://usegalaxy.org - but especially those that routinely fail for memory 

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#2666]
Prioritize some now that fail on the default cluster?

I am not sure if these dispatch to Jetstream/Roundup depending on job scheduling (meaning a re-run could start up on Jetstream, even if it takes a few tries) or if these jobs only go to Roundup (the default cluster) at this time.

Example tool: Picard Mark Duplicates

ping @natefoo

**Comment by natefoo** [comment]
For Picard Mark Duplicates and other tools that consistently need > 16GB, I'd like to see some effort to determine whether a dynamic rule can be written for these tools. We're liable to eat up a large chunk of our resources if we just blanket grant huge amounts of memory for all runs of these tools. Someone who understands the tools should really do the development on such a rule (if not the rule code, then at least the memory profiling).

Sending them to Jetstream is (at the moment) a bad use of our Jetstream SUs, because there are no "single core big memory" instances in Jetstream. To get the amount of memory needed for these tools, we'd be using large (10C/30GB) or extra large (24C/60GB) multicore instances for a single core tool, and the core count is a multiplier on SU usage. There was talk of adding additional instance types for small cores/large memory to Jetstream, but I don't think it's happening any time soon.

**Comment by jennaj** [comment]
Thanks @natefoo for looking into this

Some solution would be good - many users are needing to move to a local/cloud (away from main) because of MD memory fails in particular (for even smaller datasets). I was wondering originally if jobs that fail for memory could be automatically re-run with more resource (larger node) as a fall-back, before giving the user an error dataset for exceeding memory .. but that might be a naive approach or a poor long term solution.

**Comment by oplantalech** [comment]
For me it would also be interesting to see if this issue can be solved, since I cannot run Picard Mark Duplicates because of memory fails.

**Comment by gregvonkuster** [comment]
+1 on this - I have the same problem with the Picard Mark Duplicates tool.

**Comment by jennaj** [comment]
htseq-count is another that could use more resource (fails often). Is in another ticket but related: https://github.com/galaxyproject/galaxy/issues/2501

**Comment by natefoo** [comment]
Thanks to @gregvonkuster I have just discovered that despite being allocated 16GB, all of the Picard tools default to using 2GB unless `$_JAVA_OPTIONS` is set to include an increase in the JVM's memory limit with `-Xmx`. I made these changes in galaxyproject/usegalaxy-playbook@505e87545af74c1cfd7e276b1d35a53d74ada938 and now the Picard tools (and all other Java tools) on Main should be getting just under 8GB. We can increase them to 16GB if needed but even 8GB is a 4x increase from what they had before.

**Comment by jennaj** [comment]
Several smaller jobs that previously failed now execute. Yea! Let's track future bug reports for this and decide about more memory then? Maybe two weeks?

**Comment by martenson** [comment]
form https://github.com/galaxyproject/galaxy/issues/1436 by @jennaj :
Consider allocating more memory to "Graph/Display Data: Scatterplot" on Main

This is the tool panel version of the tool.
Workaround: Try alternate scatterplot functions found in graph/vis pull-down menu per dataset

**Comment by martenson** [comment]
Other candidates are below. They tend to lead the list of OOM killed tools.

toolshed.g2.bx.psu.edu/repos/bgruening/sailfish/sailfish/0.7.6.0
toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/1.0.1
toolshed.g2.bx.psu.edu/repos/devteam/weightedaverage/wtavg/1.0.1

**Comment by jennaj** [comment]
Hi - I am going to close this out now. I think most if not all tools noted in this ticket have had the memory allocation adjusted. If we need to adjust more in the future, we can track those cases here instead: https://github.com/galaxyproject/usegalaxy-playbook/issues
