### ISSUE TITLE
improve reliability of Galaxy's auxiliary services

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#2699]
We are currently running few services that reduce Galaxy's Community usage experience significantly when they are down. These include:
- depot.galaxyproject.org / CargoPort
- Bioarchive
- Main Tool Shed

Moreover these dev-specific services could benefit too:
- Jenkins
- StarForge

We would like to design a deployment schema that will provide some redundancy of these.

pinging possible interested parties: @bgruening @erasche @natefoo @jmchilton @mvdbeek

**Comment by martenson** [comment]
- rsync servers with a VM webserver that does balancing and short-lived DNS entries?
- cvmfs?

**Comment by hexylena** [comment]
Rsync is online for some services, but I forget which ones/where.

When I originally looked into this a while back, I also looked at:
- bittorrent for distribution amongst universities
  - my original plans included using nodejs + https transport since it makes people more comfortable (or something)
  - would allow us to implement nice and complex rule sets to allow various universities to host just the subsets of things they want to host.
- TAHOE-LAFS
  - less code to write, might be easier to deploy, would allow us to provide good redundancy + expose the FS over HTTP.

In the end, these are all complex solutions to a simple problem, we should have a simple answer: just stick stuff on an s3 bucket.

I believe many of the larger groups amongst the community would be more than happy to provide bandwidth/storage for whatever resources, but the complexities of implementing whatever solution that might be would be huge compared to using established file storage areas.

**Comment by natefoo** [comment]
The only reason these things aren't in S3 is concerns over transfer fees. In reality the charges would probably be very small, although someone with malicious intent could cost a lot.

**Comment by dannon** [comment]
Maybe have a server proxy to s3 iff primary (free) is down?

**Comment by hexylena** [comment]
Is that part of the threat model? Do we need to put resources towards distributed hosting of files, and then some redirection service which will point at the various servers which have volunteered to host various resources?

(I'm saying "redirection service" instead of "RR dns entries" because I would not be able to host at the root of an fqdn, domain names are harder to get for my org, much easier to deploy in a subdir)

**Comment by martenson** [comment]
No matter what is the backend we probably need some proxy/dumb webserver on a VM that we can spin up. This we could primarily do on EC2 because it should have small/cheap bandwidth-footprint as it mostly redirects. It could additionally house logic regarding geo-aware choices based on the request's origin.

@natefoo's drawing of cvmfs-based system we discussed:
![img_20160802_114200](https://cloud.githubusercontent.com/assets/1814954/17335052/9922adb4-58a6-11e6-8f40-c52fe35378e8.jpg)

**Comment by martenson** [comment]
most of these have improved over time and we have cvmfs in place for the critical parts. Except Main Tool Shed - that is still a big point of failure when it is down.
