### ISSUE TITLE
Provide ability to export a workflow to the toolshed

### ISSUE THREAD

**Issue by alexlenail** [galaxyproject/galaxy#2702]
When you want to "Download or Export" a workflow, you go to the screen:

---

<img width="537" alt="screen shot 2016-08-02 at 2 50 10 pm" src="https://cloud.githubusercontent.com/assets/2761597/17340959/7b802470-58c0-11e6-80d7-61dcbc875e42.png">

---
- First, what is myExperiment? 
- Second, I believe there should be a way to one-click export a workflow to the galaxy toolshed. May I try to build this?

**Comment by hexylena** [comment]
Workflows are somewhat difficult to use when imported from the TS so this is not encouraged. Currently the community seems happy enough to post them on GitHub. Not a solution in every case, but it works for now, until the community can identify a better workflow sharing setup. Closing this since it is unlikely anyone will implement this and that sharing on Github is recommended (e.g. [training materials](https://github.com/galaxyproject/training-material/tree/master/topics/variant-analysis/tutorials/dip/workflows))
