### ISSUE TITLE
warn admin when no path to install a requirement exists

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#2927]
During the tool installation in case there is no TS package available and Conda is disabled we should warn admin that they need to enable Conda and restart Galaxy if they want to install dependencies. We should also link to https://docs.galaxyproject.org/en/master/admin/conda_faq.html

This is a quickfix that should get to 16.07 before we resolve this fully via https://github.com/galaxyproject/galaxy/issues/2925 or similar

What do you think @mvdbeek ?

**Comment by mvdbeek** [comment]
I think this is not so easy, we would need to query the TS for a list of requirements of all tools in that repository (because if there are no TS dependencies, we also don't see the requirements, IIRC). Or you mean to just always put that message when there are no repository dependencies (even if the tool has no requirements)?

**Comment by martenson** [comment]
ping @blankenberg as I discussed this with him

**Comment by martenson** [comment]
This does not seem to be an important issue anymore, with conda taking over.
