### ISSUE TITLE
Open up some metrics to non-admin users

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#2954]
From discussion on closed, top-secret IRC channel:

```
14:02 < natefoo> have i been assuming metrics are visible to everyone this entire time and 
                 they're admin-only?
14:13 < g2roboto> [delphine] That is what it seems, I have seen a discussion about that on 
                  the galaxyprojectchannel on september 20th and bag_ seemed to say it was 
                  an admin only view
14:14 < jmchilton> Was it always that way - I don't remember designing it that way?
14:27 < natefoo> yeah i don't remember that being the intent, for sure
14:51 < jmchilton> "A simple example demonstrating the core, uname, meminfo, cpuinfo 
                   plugins. (Only admins will see these job metrics in the UI.)"
14:52 < jmchilton> https://bitbucket.org/galaxy/galaxy-central/pull-requests/352/implement-plugin-framework-and-plugins-for/diff  
14:53 < jmchilton> Nothing in the PR or commit 
(https://bitbucket.org/galaxy/galaxy-central/commits/3ffd1ca6ac44736cba9e36abfaf3b1e607ddefb6?at=default) or comments about why it is admin only :D  
14:54 < jmchilton> The collectl metric reveals a path - the env metric would likely reveal 
                   many paths. I guess that was why
14:54 < jmchilton> I guess it should be admin-only based on the plugin 
```

**Comment by bgruening** [comment]
I have never seen this as general user and a few already ask if Galaxy collects these information.
@jmchilton you mean Slack not IRC isn't it?

**Comment by hexylena** [comment]
+1 for exposing those things to end users (minus the env which would reveal more than paths e.g. in docker)

**Comment by jubrilissa** [comment]
@erasche I would like to take this. Any clue on how to go about this?

**Comment by hexylena** [comment]
Hi @andela-ijubril

Thanks for your interest! The responses on this page are from [templates/show_params.mako](https://github.com/galaxyproject/galaxy/blob/71cea6604d43c5fe6215f5656462ba6c1af69bb6/templates/show_params.mako)

You would probably just remove the admin checks for displaying job metrics, the job command line and full path (the other two things behind a `user_is_admin()` check should probably stay admin only.

There are several different metrics plugins that are currently supported, we would like admins to be able to see all of the plugins. Regular users should see all of the plugins _except_ environment variables.

[Here](https://github.com/galaxyproject/galaxy/blob/71cea6604d43c5fe6215f5656462ba6c1af69bb6/templates/show_params.mako#L178) is the relevant line in the template file that you would need to work on, and [here](https://github.com/galaxyproject/galaxy/tree/d9af95b401ebec1db5cd6653f5ebbb9a7fd5c3f5/lib/galaxy/jobs/metrics/instrumenters) are some of the metrics plugins.

As for checking that your updated template behaves correctly, you will likely need to:
-  [setup](https://github.com/galaxyproject/galaxy#galaxy-quickstart) a copy of galaxy
- set an admin user in `config/galaxy.ini` in your copy of Galaxy
- enabling some of the metrics plugins by editing [`config/job_metrics.xml`](https://github.com/galaxyproject/galaxy/blob/dev/config/job_metrics_conf.xml.sample)
- creating at least two users in your galaxy (via registering via the webpage), one with an admin user email and another with a different email
- then running any of the tools like the upload tool 
  ![utvalg_028](https://cloud.githubusercontent.com/assets/458683/19136619/93d88902-8b5d-11e6-88bc-4408283efd93.png)
- and finally viewing metadata about the job as different users by clicking the "Info" icon (the "i" next to the save button / floppy disk in [this](https://github.com/ErasmusMC-Bioinformatics/galaxy-courses/raw/master/Galaxy101/images/101_14.png) picture. You may need to click on the title of the green block in order to view the full thing). This is how you view the show_params.mako template rendered with real data and can see what admin and regular users can see.

Apologies for the length/complexity/any confiusing, if you have any questions please let us know :)

**Comment by jubrilissa** [comment]
Thanks @erasche for the description. 
I have challenge with the `set an admin user in config/galaxy.ini in your copy of Galaxy` part of the description

I really appreciate the level of detail you put in the description. 👍

**Comment by nsoranzo** [comment]
@andela-ijubril It means you need to edit the `config/galaxy.ini` file of your Galaxy server, search for the line:

```
#admin_users = None
```

and below this add a new line with:

```
admin_users = admin@email.com
```

where `admin@email.com` is the email of exactly 1 of the 2 users mentioned above.

**Comment by jubrilissa** [comment]
Thanks @nsoranzo 👍
