### ISSUE TITLE
Sub datatype check for IEs

### ISSUE THREAD

**Issue by ThomasWollmann** [galaxyproject/galaxy#2982]
If I add for example "<test type="isinstance" test_attr="datatype" result_type="datatype">images.Tiff</test> " to jupyter.xml. I can open it with the IE. When I want to do it with the parent class "<test type="isinstance" test_attr="datatype" result_type="datatype">images.Image</test>" it is not working any more. Tried to find out what happend in the last commits, but I havn't figured it out yet. Any suggestions? I don't want to add each subdatatype separately.

**Comment by bgruening** [comment]
This looks like a regression. @guerler @carlfeberhard has anything changed recently in the VIS subsystem?

**Comment by carlfeberhard** [comment]
Short form: not a regression - this never worked but I'll ~~fix~~ hack it so that it does. 

Long form: The visualization plugin test gets its classes to test against from the datatypes registry and, since 'images.Image' is (essentially) an abstract base class and never loaded into the datatypes registry, 'images.Image' can't be found in the datatypes registry.

Does anyone know or see any other classes like 'images.Image' that aren't loaded into the datatypes registry but would be useful for 'isinstance' testing in visualization plugins?
