### ISSUE TITLE
Inter-Galactic transfer of histories failing with 'Export history to file' & 'Import from file'

### ISSUE THREAD

**Issue by MoHeydarian** [galaxyproject/galaxy#3235]
The 'Export history to file' and 'Import from file' functionalities are not exporting histories as they should be. 

When one clicks the 'Export history to file' button from the history menu, a link is generated that can be copied/pasted to the input box of 'Import from file' and after doing so Galaxy says, "This history will be visible when the import is complete." No new histories or data appear, even a day later. This happens on useGalaxy.org and on local instances. 

A workaround to this issue is to click the link that is generated by 'Export history to file' and download the history as a compressed (.tar) file that contains the datasets in that history. These datasets can be uploaded in bulk to the destination Galaxy instance. Note that the naming of the datasets is preserved from the initial history, but the order they appear is not.

**Comment by jgoecks** [comment]
@MoHeydarian You can only use the link when a history is **accessible/published** b/c another instance attempting to use a link to a history otherwise does not have access to it. This is clearly a problem and should be fixed, most likely by asking the user to make the history accessible/published when exporting it.

I have not seen dataset ordering changed when importing/exporting. If you can provide an example, that would help in debugging.

**Comment by MoHeydarian** [comment]
Yes, thanks for pointing that out, @jgoecks. Even when histories are made accessible and published they never get imported to the destination Galaxy.  

Here is a small (accessible and published) history I've been using to test the 'Export history to file'/'Import from file' feature: https://usegalaxy.org/u/mheydarian/h/test-for-meal-generator-workflow-imported-from-uploaded-file-run1

**Comment by jennaj** [comment]
Update on this (since still open), currently under Galaxy version 17.09:

 - **URL export/import works** between Galaxy servers now. 

 -- _Of note_: **failed datasets are transferred but show up green instead of red in the newly imported history version**..this seems like a bug. It can be seen in this URL transferred history, in dataset 40: https://galaxy.uni-freiburg.de/u/jenj/h/url-load-from-main-imported-from-archive-test-history-freebayes. The source has dataset 40 (correctly) shown in red: https://usegalaxy.org/u/jen/h/test-history-freebayes
 - **Archive downloaded/uploaded then export/import does not work**. Tested at https://usegalaxy.org and https://galaxy.uni-freiburg.de. The history downloads into an intact archive that can be opened with the correct content/datasets.

cc @dannon 

reported by https://biostar.usegalaxy.org/p/26361/

**Comment by mvdbeek** [comment]
This has seen a lot of improvements that will land in 19.05 (and some from even before that), I'm gonna close this, but feel free to re-open if something still doesn't work on 19.05.
