### ISSUE TITLE
datatypes are loaded from tmp dir?

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#3300]
This seems to be a bug, isn't it?

```
galaxy.datatypes.registry DEBUG 2016-12-10 23:08:58,055 Loading datatypes from /data/2/galaxy_db/tmp/tmp-toolshed-acalpdE1ZD7R
```

@natefoo do you see something similar on usegalaxy.org? I think these are the deeptools datatyps and it slows down restart quite dramatically.

**Comment by natefoo** [comment]
I believe this is because Galaxy writes TS-installed datatypes out to temp files to merge them together, but I have never been 100% clear on mine. Looking at a random one of mine, they do appear to be shed datatypes:

```xml
<?xml version="1.0"?>
<datatypes>
<registration>
        <datatype display_in_upload="True" extension="deeptools_compute_matrix_archive" subclass="True" type="galaxy.datatypes.binary:CompressedArchive" />
        <datatype display_in_upload="True" extension="deeptools_coverage_matrix" subclass="True" type="galaxy.datatypes.binary:CompressedArchive" />
    </registration>

</datatypes>
```

@gregvonkuster might be able to shed a little more light on why this is done, I don't remember exactly.

**Comment by gregvonkuster** [comment]
If Galaxy writes TS-installed datatypes out to temporary files, I do not know why.  This doesn't seem necessary to me, and I cannot remember writing code that takes this approach.  Of course, its been quite some time since I was involved in this, so I easily may have forgotten something.

IIRC (when I was involved), at startup, the datatypes_conf.xml file was read along with all of the datatypes_conf.xml files installed from the TS and an in-memory registry was created.  At that time, the set_metadata.py script was used to set metadata externally, and this script read the datatypes_conf.xml file from disk (since it was running external) so the in-memory registry was persisted so that the script could read it.

The in-memory registry was updated in real time if TS repositories that included datatypes_conf.xml files were installed / uninstalled.

**Comment by hexylena** [comment]
Seems fixed?

```
galaxy@sn04:~$ journalctl -u galaxy-handler@1 --since '24 hours ago' | grep 'Loading datatypes from'
galaxy@sn04:~$
```
