### ISSUE TITLE
search field missing in the new workflow submit form

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#3302]
One of our users is missing the search field in the new workflow submission form.

In the old UI there was a search field to search the history for input files. One example use case was to type `RNAseq` and all files could be loaded into the box with a single hit on the return key.

**Comment by jmchilton** [comment]
Indeed - here is the run form multi-select from 16.07.

![workflow_regression](https://cloud.githubusercontent.com/assets/216771/21500809/a7830eac-cc10-11e6-9798-b5f6ea662849.png).

I'd call this a regression - I'm unsure if it is intentional though.

I implemented the original functionality I think - or at least pieces of it. It was definitely useful for driving large numbers of workflows - hopefully the need for this is somewhat lessened by collections.

**Comment by guerler** [comment]
It was intentional as an effort to unify this view with the regular tool form view but since its a useful feature, particularly the `select all` option after filtering, it should probably be augmented.

**Comment by jmchilton** [comment]
@guerler Awesome - a good thing about it being unified is now the regular tool form can have that functionality also. Sounds like a good plan to me.

**Comment by hexylena** [comment]
I guess this is now based on size and unified? If it's still an issue we should reopen :)
