### ISSUE TITLE
Conda locking issue when launching multiple jobs simultaneously

### ISSUE THREAD

**Issue by Takadonet** [galaxyproject/galaxy#3438]
Having trouble initialisation a conda envs for the tool bcftools_consensus , https://toolshed.g2.bx.psu.edu/view/iuc/bcftools_consensus/c9ed58c0f8e3 , when launching dozens jobs simultaneously.  Getting the following error in my worker threads.

LockError: Lock error: Already locked: Lock error: 
LOCKERROR: It looks like conda is already doing something.
The lock [u'//galaxy/production/deps/_conda/pkgs/openssl-1.0.2j-0.pid29899.conda_lock'] was found. Wait for it to finish before continuing.
If you are sure that conda is not running, remove it and try again.
You can also use: $ conda clean --lock

I have enabled use_cached_dependency_manager parameter in my galaxy.ini file.  Seems like the the caching is not working or something else I am not seeing.

**Comment by mvdbeek** [comment]
The log points to the cached environment not being used. The easiest way is to re-install the tool in question, otherwise you can use the api to build the cached environment.
This python snippet should hopefully work for you (replace CONVERTER_fasta_to_2bit with the tool id in question ):
```Python
import bioblend.galaxy
url = 'http://localhost:8080/'
api_key = 'admin_api_key'
tool_id = 'CONVERTER_fasta_to_2bit'
endpoint = "api/tools/%s/build_dependency_cache" % tool_id
gi = bioblend.galaxy.GalaxyInstance(url, api_key)
gi.make_post_request("/".join((url, endpoint)), payload={'id': tool_id})
```

That said, with the upcoming 17.01 release we've reworked how the dependencies are built so that hopefully we can eliminate this caching hack soon.

**Comment by Takadonet** [comment]
That is super weird that it did not make the cache environment. All works now. Perhaps I installed before changing the value in galaxy.ini.

Thanks!
