### ISSUE TITLE
Binary datatype cxb cannot be uploaded to http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#3441]
Datatype is noted as supported (Upload tool, Edit Attributes) and is output by Cuffquant within Galaxy (intact + useable with downstream tools).

**YET** uploaded .cxb files load with empty content and this message in the green dataset:

> The uploaded binary file contains inappropriate content

Tested with a Galaxy Main produced .cxb dataset. Included a matrix of:
 1) using autoassign of datatype in upload tool 
 2) direct assignment in upload tool 
 3) post load assignment of datatype (edit attributes)
 4) FTP then upload tool (completely loaded via FTP to server intact)
 5) Upload tool with local file browsing

ping @guerler @galaxyproject/guac

**Comment by nsoranzo** [comment]
The same applies for the `cps` datatype and is due to their definition in `config/datatypes_conf.xml.sample`:
```
    <datatype extension="cxb" type="galaxy.datatypes.binary:Binary" mimetype="application/octet-stream" subclass="true" display_in_upload="true" description="Cuffquant output format" />
    <datatype extension="cps" type="galaxy.datatypes.binary:Binary" subclass="true" display_in_upload="true" />
```
Every binary datatype should be registered with either `Binary.register_unsniffable_binary_ext()` or `Binary.register_sniffable_binary_format()` in `lib/galaxy/datatypes/binary.py` , but this is usually done after defining a class for the datatype in the same file. Instead `cxb` and `cps` don't have a class defined and use the `subclass="true"` system.

The result of this is that the binary cannot be sniffed (because there is no sniffer defined) and even if the correct format is assigned in the upload tool, Galaxy refuses the content and creates an empty dataset with the "The uploaded binary file contains inappropriate content" description.

The simplest solution is to define 2 simple classes for the datatypes and register them (or even just register them with `Binary.register_unsniffable_binary_ext()` , but that's not the common practice). Alternatively the way in which the Upload tool works in this case should be changed.

There are other 5 binary datatypes (`toolshed.gz`, `bcf_bgzip`, `interval_index`, `tabix` and `bgzip`) which also don't have a class definition, but they are not specified with `display_in_upload="true"`, so they may probably stay as they are.

**Comment by jennaj** [comment]
I wanted to test this again to make sure the upload functions for .cxb after 18.01 updates. 

The warning tells users directly in the failed job comments what to do == assign the datatype at upload. Nice!

https://usegalaxy.org/u/jen/h/test-history-cuffquant-cxb-upload-sniffing
