### ISSUE TITLE
understanding API workflow status

### ISSUE THREAD

**Issue by jvolkening** [galaxyproject/galaxy#3944]
I am testing the Galaxy REST API for use in automated data upload and workflow scheduling. I can successfully upload inputs files and invoke a workflow on them, but I can't figure out how to tell when the workflow is completed. I am periodically refreshing the invocation status via the API but the 'state' field in the response is always 'scheduled', even long after the workflow completes. Is this the intended behavior? Is there another way to tell if the workflow has finished? I can see that the state of the final step in the workflow is 'ok'. Should I just be polling the status of the final step (assuming 'ok' means the tool is finished running)?

**Comment by jmchilton** [comment]
The workflow invocation endpoint only tells you if all the steps have been "scheduled". It doesn't indicate if all the jobs are complete and/or if all the datasets are ready. Once the workflow is ``scheduled`` then you can wait on the history to become ``ok`` if you know there is only one workflow running per invocation. Otherwise - you will need to wait on individual datasets and jobs currently.

Here is it in code form (``wait_for_workflow``) - as used by the API tests in Galaxy.

https://github.com/galaxyproject/galaxy/blob/dev/test/base/populators.py#L272

**Comment by jmchilton** [comment]
I'm going to close this issue since I guess I answered the question. Feel free to re-open if you stumble into problems implementing this. It might be worth adding new information about this to the workflow API endpoint - but there would need to be some flag to indicate this is some sort of extended status that isn't just the status listed in the database - feel free to open an issue for this.

**Comment by jvolkening** [comment]
> Once the workflow is scheduled then you can wait on the history to become ok if you know there is only one workflow running per invocation.

@jmchilton Thanks - that logic makes sense I guess (once the workflow is scheduled it just becomes a history running like any other). I'm don't think there's a need to open any further issues - the REST API documentation in general seems rather incomplete but I think this is a  known state of affairs (perhaps because most people are just using `bioblend`).
