### ISSUE TITLE
Improve naming files uploaded via the URL paste method

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#4005]
originally implemented in https://github.com/galaxyproject/galaxy/pull/3674
reverted in https://github.com/galaxyproject/galaxy/pull/3996 because of unwanted side effects

We need a better implementation, some ideas are listed in the [comments here] (https://github.com/galaxyproject/galaxy/issues/3695#issuecomment-283715195)

**Comment by chambm** [comment]
I think the easiest fix using the old implementation is to add a checkbox to the paste upload box like `Rename datasets to last path segment`. I agree that using the filename header from the server is even better, but that method wouldn't have worked for my situation. I was using a very simple Apache2 index to host my files, and that doesn't set the filename header. Thank goodness for Stack Overflow (er, Server Fault): https://serverfault.com/a/101966/302991
```
<Location /textfiles>
    SetEnvIf Request_URI "^.*/([^/]*)$" FILENAME=$1
    Header set "Content-disposition" "attachment; filename=%{FILENAME}e"
    UnsetEnv FILENAME
</Location>
```

So maybe a combo box instead of a checkbox, with options like:
Full URL (default)
Last path segment
Filename header

**Comment by hexylena** [comment]
Agreed with @chambm, would love to see this re-reverted with a checkbox so users can opt-in :)

**Comment by mtekman** [comment]
I was just thinking about this today

![Screenshot_2020-10-30 Galaxy](https://user-images.githubusercontent.com/20641402/97679086-1930a600-1a95-11eb-9e3b-b658f782a376.png)

**Comment by hexylena** [comment]
Here's a video from @foellmelanie where she spends like 5-10 minutes renaming files. https://youtu.be/ad3E4VaTp7M?t=510

We really need a checkbox like @mtekman suggested. https://github.com/galaxyproject/galaxy/issues/4005#issuecomment-719426038

I've tagged this papercut so hopefully this gets more eyes, but this is one of those missing features that regularly is an annoyance for users. #11371 is related

**Comment by assuntad23** [comment]
@hexylena Now that pasted URLs use the datafetch tool, is this resolved? 

It looks like it's in good shape now. I uploaded three of the files from that video, and they were renamed in a way that matched what the user was doing.

https://zenodo.org/record/4544529/files/Evidence.tabular
https://zenodo.org/record/4544529/files/protein_groups.tabular
https://zenodo.org/record/4544529/files/PTXQC_report.pdf

Feel free to try those (and/or whatever URLs you'd like) and let me know if it seems this issue is resolved for you.

**Comment by hexylena** [comment]
It looks like it's currently broken on main but test looks good!

![image](https://user-images.githubusercontent.com/458683/142395404-1f5c487c-0afe-454c-a5f1-ea1693f77f6c.png)

This is so beautiful :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: , it's going to save so much time. @shiltemann it finally happened!!! No more mothur tutorial naming issues because people don't rename the files properly like you tell them to!

![image](https://user-images.githubusercontent.com/458683/142395428-9fea9c4b-5595-4502-8c95-af63c94cb9e3.png)

**Comment by shiltemann** [comment]
Whoo! Thanks @assuntad23! Definitely a big QOL improvement for a lot of use cases and tutorials!

**Comment by mvdbeek** [comment]
That was fixed in https://github.com/galaxyproject/galaxy/pull/12861, that's why it works on test and not main.

**Comment by hexylena** [comment]
is that specific failure expected though @mvdbeek ? unsupported media type for two pasted URLs?

**Comment by mvdbeek** [comment]
No, but that also works for me. Can you check what endpoint returned this reponse, and which browser are you using ?
<img width="1499" alt="Screenshot 2021-11-18 at 11 50 20" src="https://user-images.githubusercontent.com/6804901/142401839-0111cf72-4daa-4674-82a0-ae1cfd470ff8.png">
?

**Comment by hexylena** [comment]
It works now, I cannot reproduce. :(
