### ISSUE TITLE
Kubernetes Staging

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#4030]
I've been thinking about how to use Kubernetes to schedule containers instead of scheduling cluster jobs. I know @pcm32 has already put a good deal of work into this - but it relies on having a shared file system available inside of the Kubernetes cluster. There are good use cases for that - but I think there are likely cases where such volumes are unavailable or impractical.

Pulsar is very good at taking a big json blob produced by Galaxy, communicating with Galaxy to stage the data, run a job, and stage out. However - Pulsar isn't available in containers generally - so we cannot leverage it from inside of the containers. So I think that leaves two paths forward - we either have the container we schedule do the staging and then schedule another container or we have separate containers for staging and running and instruct Kubernetes to process them in serial.

I have not found any APIs that seemed geared toward doing the first of these options. I don't see a general way to create some disk and then dynamically create a pod or job to attach to that disk and wait for it. Maybe I'm missing something though and this can be done cleanly - any ideas?

The second route seems more promising and it seems like we could pretty easily leverage the existing work on the Kubernetes runner. My idea is to use the ``batch/v1`` endpoint still - but we break the execution into two "init containers" and one normal container. The first init container would stage the data in, the second init container would run the job on the data, and the normal container would then stage the data out. The staging containers are pretty straight forward and can leverage a lot of the work that we have already done on the Mesos runner mode for Pulsar - but it is much simpler since we don't have to worry about state as much - Kubernetes takes care of that - this just looks like a normal job.

Both jobs themselves and init containers are kind of newish additions to Kubernetes but I did the following little example with my minikube setup to see if they work together:

```
$ cat galaxy-job.yml
apiVersion: batch/v1
kind: Job
metadata:
  name: galaxy-job-uuid-here
  labels:
    jobgroup: galaxy-job
spec:
  template:
    metadata:
      name: galaxy-job
      labels:
        jobgroup: galaxy-job
    spec:
      restartPolicy: Never
      initContainers:
      - name: pulsarstagin
        image: busybox
        command: ["sh", "-c", "echo 'staging in'; echo 'input' > /work-dir/input"]
        volumeMounts:
        - name: workdir
          mountPath: "/work-dir"
      - name: runcommand
        image: busybox
        command: ["sh", "-c", "echo 'running tool'; cat /work-dir/input; echo 'output' > /work-dir/output"]
        volumeMounts:
        - name: workdir
          mountPath: "/work-dir"
      containers:
      - name: pulsarstageout
        image: busybox
        command: ["sh", "-c", "echo 'staging out'; ls /work-dir/"]
        volumeMounts:
        - name: workdir
          mountPath: "/work-dir"
      volumes:
      - name: workdir
        emptyDir: {}
```

And the final output was:

```
2017-05-05T13:32:49.164483895Z staging out
2017-05-05T13:32:49.164545285Z input
2017-05-05T13:32:49.164550002Z output
```

So it seemed like these features worked together and saw each other disk and such.

Ping @pcm32 - does this seem like the right approach to you for staging? Is there a more obvious way to have one container schedule another with disk setup by the first?

**Comment by pcm32** [comment]
> I don't see a general way to create some disk and then dynamically create a pod or job to attach to that disk and wait for it.

At this level (dynamic disk provision), projects like [heketi](https://github.com/heketi/heketi/wiki/Kubernetes-Integration) might come in handy. It will provide you with shared disk on-demand (glusterfs currently I think).

> we either have the container we schedule do the staging and then schedule another container...
> I have not found any APIs that seemed geared toward doing the first of these options.

This could be done very much in the same way that we are using Galaxy inside Kubernetes to schedule jobs; through the service account. Each running container can in principle access the k8s cluster where they run and send requests to the k8s API Server (to request pods, jobs, etc). So you could have a staging container which moves the data and receives all the galaxy job metadata to schedule the subsequent container that will actually run the tool, stay alive while the job runs and constantly query the cluster about completion. When this is done, then handle either the staging out or submit a new container execution that handles it. Since this would be separate requests, you could land on separate nodes, so you would need to actively request the same node where the original "staging-scheduler" container landed (this should be easy with a node selector annotation). This I guess has the advantage of uncoupling staging from running (avoiding multiple staging when the run is repeated due to failure), although is a bit more convoluted. But agreed, there are no direct API objects to deal with this.

On the second option that you tried, does the order on the initContainers guarantee sequential execution? Otherwise, you could get some race conditions between staging and job execution I guess. 

> So it seemed like these features worked together and saw each other disk and such.

This should be the case as long as containers are within the same pod, which should be the case inside a single `spec` clause for a job.

Out of curiosity, how do you normally stage the data? through bioblend API calls to bring history items?

**Comment by pcm32** [comment]
Agreed though that second option would be easier to implement inside the current Kubernetes runner.

**Comment by pcm32** [comment]
@jmchilton anything new on this? We might have a use case here for it and might be interesting to have a chat about this. In the context I would be working I think that we could rely on an s3 for data files... would tools and runner work out of the box using the galaxy s3 integration, or more would be needed?

**Comment by jmchilton** [comment]
I've outlined at a high-level how I intend to do something like this in http://bit.ly/gxremoteexec2019. I've added this issue to the project board https://github.com/galaxyproject/galaxy/projects/11 and hope to have a finished and tested solution in 19.05 and to present it at the GCC this year as part of a broader discussion of dealing with remote data in Galaxy.
