### ISSUE TITLE
Warn users when tool version conflicts lead to dropped input connections

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#4041]
I imported a workflow provided by @moheydarian for testing and noticed that the collection cannot be attached to the fastq-input of the tool. ping @jmchilton 

![trimmomatic](https://cloud.githubusercontent.com/assets/2105447/25809300/887b0a78-33da-11e7-9333-fcdff826feb4.png)

**Comment by jmchilton** [comment]
<img width="722" alt="screen shot 2017-05-08 at 10 45 42 am" src="https://cloud.githubusercontent.com/assets/216771/25809622/903dcf4c-33db-11e7-8ab9-14d7ce5f54b1.png">

Are you attempting to connect a ``list`` to a ``paired`` input? If yes, you need to either change your collection type to ``list:paired`` or ``paired`` or change the input type selector for Trimmomatic I think.

**Comment by guerler** [comment]
Thanks for the quick response. The imported workflow specifies `list:paired`, its the one I sent to you per email. I think this could be another issue caused by different tool versions. ping @moheydarian.

**Comment by MoHeydarian** [comment]
The reason you can't connect the noodle from the input collection to Trimmomatic is because Trimmomatic has a single noodle serving as input for the next step. If you disconnect the second noodle you can then connect the input collection to Trimmomatic and will see a collection of noodles connecting the two. If the output of a tool is not in collection form you won't be able to force the input to accept a collection in the workflow editor. 

I believe this is the [workflow](https://github.com/MoHeydarian/Workshed/blob/master/Galaxy-Workflow-RNAseq_workflow_with_collections_for_testing_clouds.ga) being discussed.

**Comment by guerler** [comment]
Yes thats the one. Thanks. So is this behavior correct? Does the workflow work properly?

**Comment by MoHeydarian** [comment]
Sorry for the delay. Yes, the workflow works on 17.05 .

**Comment by guerler** [comment]
No worries, Thanks for testing it.

**Comment by martenson** [comment]
Should we move this to 17.09 milestone?

**Comment by mblue9** [comment]
Hi, I'm still getting my head around workflows and encountered a similar issue to this yesterday when changing over a workflow to accept a collection as input. The noodles wouldn't connect and it was really not obvious to me how to get it to work, but the info in this issue just fixed it! - changing the Input collection type to list:paired and disconnecting/reconnecting everything.
Thanks!!! Is this info somewhere in the documentation? Did I just miss it?

**Comment by mvdbeek** [comment]
I think we've narrowed this down to having to implement https://github.com/galaxyproject/galaxy/issues/7431 and  https://github.com/galaxyproject/galaxy/issues/7141 ... I'll close this one.
