### ISSUE TITLE
Switching between tool versions problematic at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#4097]
Use case: 

1. Older tool version was used, re-run button brings up prior run, "Versions" menu is at top of tool form, selecting newer version causes form to refresh with notice that latest version is now used (for a few seconds) - or - states that latest version before the very latest update is being used - then goes away with another page refresh and the original version's tool form is what is available. **no way to get to new version from older version**

2. Selecting the latest tool version from tool panel brings that form up. Selecting older version will change form to that version. But going back up, same result as in 1 above **for some tools**. For others, switching version is fine this way.

Tools reported/tested with this problem are many and linked to those recently updated in last few weeks. Example:

- Salmon, recently updated: Starting with rerun v 0.7.2, not possible to get to 0.8.2. If starting from v 0.8.2 from tool panel can switch between the two.
- StringTie, recently updated - same as ^^
- Cuffnorm, not recently updated - not impacted, switching versions is fine using rerun

cc @martenson @davebx 

@bgruening do you want this somewhere else? not sure if can be replicated other places besides main

**Comment by mvdbeek** [comment]
I have seen this as well, this is a bug we need to fix.

**Comment by mvdbeek** [comment]
I've been digging a bit into this, and it's not super consistent behavior. One thing that does happen consistently and that we need to improve is that if anything but the latest repository is being installed, part of the tool lineage gets messed up. The result is that switching versions does not work and/or you don't even see the "versions" button. This happens here: https://github.com/galaxyproject/galaxy/blob/09173cc6070bc914759f15854367d62ca6323c79/lib/tool_shed/tools/tool_version_manager.py#L79-L79, because apparently `tool_version_dicts` corresponds to the repository revision that you are installing. 

So I guess we should make sure that during installation the tool_version_dicts always corresponds to the latest version.

**Comment by mvdbeek** [comment]
I think most of this should be fixed by #4214. For some tools with broken shed lineages this is going to be fixed by #4214, but I don't think this affects what @jennaj described, so I'll close this for now.
