### ISSUE TITLE
Improve edit attributes genome/database selection menu justification

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#4176]
Not new. Could we improve the display?

Graphics from http://usegalaxy.org accessed on MAC OS 10.10.5 (Yosemite)

**Safari Version 10.1.1**

<img width="459" alt="screen shot 2017-06-09 at 4 06 14 pm" src="https://user-images.githubusercontent.com/8999735/26997353-d5f480ec-4d2d-11e7-8562-ec2c39a4db33.png">

**Chrome Version 58.0.3029.110**

<img width="411" alt="screen shot 2017-06-09 at 4 01 06 pm" src="https://user-images.githubusercontent.com/8999735/26997298-488bedee-4d2d-11e7-938d-7ad3d14f70cb.png">

cc @galaxyproject/guac

**Comment by martenson** [comment]
ping @guerler  - did we change anything regarding select2 recently?

**Comment by guerler** [comment]
This seems to be triggered by the overly long labels e.g. `Japanese eel 18 Mar-2014 (japanese_eel_genome_v1_25_oct_2011_japonica_c401b400k25m200_sspacepremiumk3a02n24_extra.final.scaffolds/angJap1) (angJap1)`. A workaround is to make this label shorter. This is not an issue in dev since this mako has been removed and replaced with a client-side view which properly configures the select2 field.
