### ISSUE TITLE
Galaxy Chat is non functional

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#4217]
I found two issues:

- After the chat server set up I am unable to send messages and getting `raise KeyError('Session is disconnected')` 

- If I disable the chat in galaxy.ini but leave the option ON in the user prefs I will get `GET http://localhost:7070/ net::ERR_CONNECTION_REFUSED`in JS console in every Galaxy page. Additionally the user pref UI does not render this option (since config disabled it) so user has no means to fix this.

**Comment by hexylena** [comment]
cc @bgruening the session is disconnected appears to be because we aren't sending a cookie, which is expected given the browse cross-origin restrictions.

I think if we solve this, the problem goes away, but it basically means figuring out a good deployment strategy and documenting it. I.e:

- must be behind apache or nginx, next to galaxy
- same domain, same protocol, same port
- must be below the galaxy cookie path, so this means the chat server needs a configurable proxyPrefix

**Comment by anuprulez** [comment]
@martenson I fixed the second issue in this [branch](https://github.com/bgruening/galaxy/tree/bugfix_communication_channel).

The first issue I could not reproduce. One case in which it does not work is when we don't set the "id_secret" config variable. Does it stop after working for sometime or it doesn't work from beginning itself?

**Comment by martenson** [comment]
@anuprulez It does not work from the start. I have non-default id_secret config. Also @erasche could reproduce.

**Comment by hexylena** [comment]
- yep, also have a non-deafult id.
- it's definitely a cookie / domain / deployment issue that needs to be rectified first.

**Comment by anuprulez** [comment]
@erasche @martenson Thank you!

I looked further into this issue. Here are the findings:

The communication channel does not work (ideally it should not happen) when I leave the id_secret with its default value ('dangerous_default') in the communication server. Then with this id_secret, session key is fetched like this - 

`X���Y)Xj/l0=O�]���G�y����z�쳓{/j#f�%oh`
or 
`B5~�!S��P�����E)�%���_���8DI׌-�!��`

Because of this, we get error in the console: 

`ProgrammingError: (sqlite3.ProgrammingError) You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str).`

I am yet to find a reason why this should happen.

But when I use non-default id_secret (for example - `80ed628affb02be1d12f9f16068fec2a`), session_key looks like - `3091fc82de22e594d0925adb316a4a75` which is parsed and user session is extracted in the communication server correctly without any console error. There is one catch here - after setting the id_secret, we need to restart the Galaxy, refresh the home page and then restart the communication server. Doing this, the communication channel works for me. 

Have you already tried it in the order?

1. Set the `id_secret` to non-default value (communication channel should be enabled at both the places - in config and user preferences)
2. Restart the Galaxy
3. Refresh the page
4. Restart the communication server
5. Open the chat popup

Also, I updated the code here: [branch](https://github.com/bgruening/galaxy/tree/bugfix_communication_channel)

**Comment by bgruening** [comment]
If this is not stripped from the codebase, we should remove it.

**Comment by dannon** [comment]
If you guys aren't using it anymore, I'll remove this.
