### ISSUE TITLE
datatypes registy should be written to job_working_directory

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#4299]
per @natefoo 

> this is the culprit: https://github.com/galaxyproject/galaxy/commit/5a26896745c16e25ce951ee3a85bdc2cd81087e1
the integrated datatypes config is now written once per handler startup rather than once per job
but it's written to the temp (scratch) directory, which is cleaned up by cron (any files older than 14 days)
thus if handlers are not restarted w/in 14 days, the datatypes file disappears and this is the result

ping @mvdbeek

**Comment by natefoo** [comment]
FWIW I think the change is good (we discussed this on IRC a while back). My current workaround is to restart handlers prior to the cleanup, but longer term solutions include:

- Touch the file on job submission (somewhat expensive)
- Write to a "permanent global var" directory defined by a new config variable
- ???

**Comment by natefoo** [comment]
In general, more job encapsulation would be better and would provide a solution. We can draw from Pulsar for this. So writing the merged datatypes out for each job may in fact be the correct thing to do, but it should be written to the job directory and cleaned up with it, rather than to `new_file_path`.

**Comment by nsoranzo** [comment]
Fixed by https://github.com/galaxyproject/galaxy/pull/4633
