### ISSUE TITLE
Extract workflow as a script?

### ISSUE THREAD

**Issue by ayaanhossain** [galaxyproject/galaxy#4312]
Is it possible to extract a published workflow as a script or Jupyter markdown file that can be executed on a standalone Linux machine (assuming, of course, the tools used in the workflow are present in the machine)?

Possible scenario: Have 1000 datasets, on which a *new* analysis is to be performed. I develop the analysis as a workflow in Galaxy using only 1 of the 1000 datasets. Then I would like to export the workflow as a script and run it on a separate server or give the script to another team for execution or extended analysis.

**Comment by hexylena** [comment]
> Is it possible to extract a published workflow as a script or Jupyter markdown file that can be executed on a standalone Linux machine

Thanks for the issue! Unfortunately no, it is not.

This feature could be implemented but I guess in the Galaxy community we encourage this to be done by just sharing a workflow in your instance? Or running that analysis and run with the full datasets there?

There is a lot of information that would need to be collected (e.g. runtime environment variables, dependencies) it's not necessarily easily to reproduce even if we could produce such a script, there is a lot that is done for setting up dependencies and any administrator configured parameters that are 'hidden'. Lastly I guess most users would want to run such a worfklow on their workflow scheduler, rather than just as one giant script? Maybe if someone else finds this issue and notes that it is interesting we can reopen then?

**Comment by martenson** [comment]
Actually @mvdbeek implemented something exactly like that that fetches workflow and details from a Galaxy and creates a Python script that takes all arguments and uses bioblend to run it. I believe he'll be happy to share.

**Comment by hexylena** [comment]
Super cool!

**Comment by mvdbeek** [comment]
I am. It should ultimately be a part of planemo, but here is the non-ready, non-packaged, limited functionality first version:
https://github.com/mvdbeek/workflow2executable
