### ISSUE TITLE
galaxy.model.HistoryDatasetCollectionAssociation not serializable when exporting histories

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#4336]
Reported by @aghozlane in [bioblend](https://github.com/galaxyproject/bioblend/issues/240#issuecomment-317351552), but this is actually a Galaxy bug.

**Comment by aghozlane** [comment]
Dear galaxy developers,

Here is the error that I have. The bug is present in the two versions of galaxy 17.01 and 17.05 that I tested locally.
What is strange is that there is datacollection in the pipeline but none is marked for export...

Error - <type 'exceptions.TypeError'>: <galaxy.model.HistoryDatasetCollectionAssociation object at 0x7f7fbaf31bd0> is not JSON serializable
URL: http://127.0.0.1:8080/history/export_archive?preview=True
File '/home/aghozlan/galaxy/lib/galaxy/web/framework/middleware/error.py', line 154 in __call__
  app_iter = self.application(environ, sr_checker)
File '/home/aghozlan/galaxy/.venv/local/lib/python2.7/site-packages/paste/recursive.py', line 85 in __call__
  return self.application(environ, start_response)
File '/home/aghozlan/galaxy/.venv/local/lib/python2.7/site-packages/paste/httpexceptions.py', line 640 in __call__
  return self.application(environ, start_response)
File '/home/aghozlan/galaxy/lib/galaxy/web/framework/base.py', line 135 in __call__
  return self.handle_request( environ, start_response )
File '/home/aghozlan/galaxy/lib/galaxy/web/framework/base.py', line 214 in handle_request
  body = method( trans, **kwargs )
File '/home/aghozlan/galaxy/lib/galaxy/webapps/galaxy/controllers/history.py', line 1226 in export_archive
  self.queue_history_export( trans, history, gzip=gzip, include_hidden=include_hidden, include_deleted=include_deleted )
File '/home/aghozlan/galaxy/lib/galaxy/web/base/controller.py', line 391 in queue_history_export
  history_exp_tool.execute( trans, incoming=params, history=history, set_output_hid=True )
File '/home/aghozlan/galaxy/lib/galaxy/tools/__init__.py', line 1376 in execute
  return self.tool_action.execute( self, trans, incoming=incoming, set_output_hid=set_output_hid, history=history, **kwargs )
File '/home/aghozlan/galaxy/lib/galaxy/tools/actions/history_imp_exp.py', line 124 in execute
  include_deleted=incoming[ 'include_deleted' ] )
File '/home/aghozlan/galaxy/lib/galaxy/tools/imp_exp/__init__.py', line 506 in setup_job
  jobs_attrs_out.write( dumps( jobs_attrs, cls=HistoryDatasetAssociationEncoder ) )
File '/usr/lib/python2.7/json/__init__.py', line 251 in dumps
  sort_keys=sort_keys, **kw).encode(obj)
File '/usr/lib/python2.7/json/encoder.py', line 207 in encode
  chunks = self.iterencode(o, _one_shot=True)
File '/usr/lib/python2.7/json/encoder.py', line 270 in iterencode
  return _iterencode(o, 0)
File '/home/aghozlan/galaxy/lib/galaxy/tools/imp_exp/__init__.py', line 385 in default
  return json.JSONEncoder.default( self, obj )
File '/usr/lib/python2.7/json/encoder.py', line 184 in default
  raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <galaxy.model.HistoryDatasetCollectionAssociation object at 0x7f7fbaf31bd0> is not JSON serializable


CGI Variables
-------------
  CONTENT_LENGTH: '0'
  HTTP_ACCEPT: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
  HTTP_ACCEPT_ENCODING: 'gzip, deflate'
  HTTP_ACCEPT_LANGUAGE: 'fr-FR,fr;q=0.5'
  HTTP_CONNECTION: 'keep-alive'
  HTTP_COOKIE: '_ga=GA1.1.434635773.1477397785; galaxysession=c6ca0ddb55be603ae85b12aa5e3e0c6bf98fe0ae316acaf72820f83b3c106fecc0283cbcb7478933'
  HTTP_DNT: '1'
  HTTP_HOST: '127.0.0.1:8080'
  HTTP_REFERER: 'http://127.0.0.1:8080/'
  HTTP_UPGRADE_INSECURE_REQUESTS: '1'
  HTTP_USER_AGENT: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0'
  PATH_INFO: '/history/export_archive'
  QUERY_STRING: 'preview=True'
  REMOTE_ADDR: '127.0.0.1'
  REQUEST_METHOD: 'GET'
  SERVER_NAME: '127.0.0.1'
  SERVER_PORT: '8080'
  SERVER_PROTOCOL: 'HTTP/1.1'


WSGI Variables
--------------
  application: <paste.recursive.RecursiveMiddleware object at 0x7f800e424ed0>
  controller_action_key: u'web.history.export_archive'
  is_api_request: False
  paste.cookies: (<SimpleCookie: _ga='GA1.1.434635773.1477397785' galaxysession='c6ca0ddb55be603ae85b12aa5e3e0c6bf98fe0ae316acaf72820f83b3c106fecc0283cbcb7478933'>, '_ga=GA1.1.434635773.1477397785; galaxysession=c6ca0ddb55be603ae85b12aa5e3e0c6bf98fe0ae316acaf72820f83b3c106fecc0283cbcb7478933')
  paste.expected_exceptions: [<class 'paste.httpexceptions.HTTPException'>]
  paste.httpexceptions: <paste.httpexceptions.HTTPExceptionHandler object at 0x7f8020b8add0>
  paste.httpserver.proxy.host: 'dummy'
  paste.httpserver.proxy.scheme: 'http'
  paste.httpserver.thread_pool: <paste.httpserver.ThreadPool object at 0x7f7ff90cf990>
  paste.parsed_querystring: ([('preview', 'True')], 'preview=True')
  paste.recursive.forward: <paste.recursive.Forwarder from />
  paste.recursive.include: <paste.recursive.Includer from />
  paste.recursive.include_app_iter: <paste.recursive.IncluderAppIter from />
  paste.recursive.script_name: ''
  paste.throw_errors: True
  request_id: '27b5771c71e411e7b2b39cebe824e75c'
  webob._parsed_query_vars: (GET([(u'preview', u'True')]), 'preview=True')
  wsgi process: 'Multithreaded'

**Comment by mvdbeek** [comment]
> What is strange is that there is datacollection in the pipeline but none is marked for export...

Exporting a history exports all items in a history. What do you mean with "pipeline"?

**Comment by aghozlane** [comment]
I mean workflow

**Comment by mvdbeek** [comment]
So your history contains a dataset collection?

**Comment by aghozlane** [comment]
yes several, but they are not marked for download.

**Comment by mvdbeek** [comment]
> yes several, but they are not marked for download.

You're using the history export functionality, which exports all datasets, there is nothing that you can select/unselect.
The actions that apply to selected items are all in the 'For all selected ...' button.

But that's independent of the bug, I will try to replicate this.

**Comment by mvdbeek** [comment]
Is there anything special about this history, are the some failed datasets within those collections?
In my simple tests I can't reproduce this.

**Comment by aghozlane** [comment]
Actually if you mark in your workflow some results, the rest will be in hidden category.
Next the export_history function export only main features and not the hidden elements.
Here is my workflow:
![gen_image](https://user-images.githubusercontent.com/1582715/28615207-94123b2a-71f8-11e7-8117-e8f244bb8057.png)
The extract_result function on the right is the one that make the export history function crazy. 
Without that step I am able to download the history.

**Comment by mvdbeek** [comment]
So what does extract_result do ? Does it create a collection ? Is this supposed to be hidden ?

**Comment by mvdbeek** [comment]
Ahh, is the output of `extract_result` perhaps a nested collection ?

**Comment by mvdbeek** [comment]
So I looked a bit into the code, as I understand it, collections should not be exported at all. The export tool will only query for `HistoryDatasetAssociations`. I think what happens is that somehow
a collection is ending up in the `jobs_attrs`, perhaps in a reduction step, where the input dataset is actually a collection.

**Comment by mvdbeek** [comment]
So is the `extract_result` tool taking in multiple files (or a collection) and produces a single output ?

**Comment by aghozlane** [comment]
Extract_result takes as input several results (including two datacollections) and produce two files (tables). Its results are not hidden. So yes it's a case where we have multiple files as input and produce single output.

**Comment by mvdbeek** [comment]
Okay, I understand the problem, but I'm afraid it's going to be quite some work. I think that to be able to do it properly (so to keep the provenance) we probably need to extend the history export for dealing with collections.

**Comment by hexylena** [comment]
Duplicate of https://github.com/galaxyproject/galaxy/issues/987

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/7367
