### ISSUE TITLE
Wrong Security Checks on Workflow Invocations in the REST API

### ISSUE THREAD

**Issue by greenwoodma** [galaxyproject/galaxy#4401]
#When using the REST API it is possible to invoke a workflow that you don't own but which has been shared with you. However, you can't then inspect that invocation as a security exception is thrown because you don't own the workflow.

I think (I'm by no means a Galaxy or python expert so take this with a pinch of salt) that the problem is the `check_security` method 
https://github.com/galaxyproject/galaxy/blob/a001145278fb0642325214123da0c5cec6fc6704/lib/galaxy/managers/workflows.py#L85
Specifically on line 104 it appears to check that the calling user is the owner of the workflow and fails if not, when it should really be checking that they are the owner of the invocation.

This makes it impossible to run a workflow you don't own, and retrieve the results via the REST API as you can't find out when the invocation has completed.

**Comment by mvdbeek** [comment]
Thanks for the report, I think your diagnosis is correct.

**Comment by mvdbeek** [comment]
I have written a test for this in https://github.com/mvdbeek/galaxy/commit/ed5f575fa2f2722cbf31b799116256847df9a4aa, but it appears to work fine if you import the workflow beforehand ... which I think is how this is meant to work. 

Now if I use the original `workflow_id` instead of `other_id`, the test indeed fails, and in that instance we could check if the workflow is either published or shared with the current user, but it seems better to first import the workflow ...

**Comment by greenwoodma** [comment]
I'm not sure I really follow that. If I use the REST API to get the list of workflows via `/api/workflows` and then use the `id` field of the workflow I'm interested in to invoke it via a POST to `/api/workflows/{workflow ID}/invocations` then the resulting invocation is not accessible if I'm not the owner of the workflow, even if it has been shared with me.

Are you suggesting that even though I have access to the workflow and can schedule an invocation that I would have to export the workflow and then import it again so that I own that copy just so I can access the invocation via the REST API? If that's what you are suggesting then why allow workflows to be shared at all, especially as I can run shared workflows via the web interface without issue. It seems to be only when working via the REST API that I can't access the relevant information to be able to tell when the invocation has completed (or not).

**Comment by mvdbeek** [comment]
Right, I guess we should do this. I am a little worried about getting updates to the workflow without notification, and I'm not entirely sure how this will behave when running shared workflows. That's why I think that importing first would probably be better. But we don't enforce this in the UI either, so I guess it's OK.

**Comment by greenwoodma** [comment]
Out of interest how would you go about importing the workflow in the UI? Would you simply download it and then upload it? If so that seems a bit odd given you can run a shared workflow without that rigmarole. Or is there a button/link I'm missing to essentially take ownership of a workflow that has been shared with me (and no I don't mean making a copy)

**Comment by mvdbeek** [comment]
You'd click on `copy` in the workflow list. ~~, which uses the API to import the workflow for the current user.~~
That's the only way know of to take ownership of the workflow in the UI. Except for up/downloading.

**Comment by greenwoodma** [comment]
ah okay. I'd done this in the UI when I wanted to make a change to a workflow, but didn't think it necessary if I just wanted to run a workflow shared with me. I'd also argue that from a reproducability angle it would be better to always run the shared workflow and not a local copy to ensure I was running the same workflow I had been given, so i'm not a fan of enforcing copying the workflow just so I can monitor the invocation via the API.

**Comment by mvdbeek** [comment]
@greenwoodma I think the issue should be fixed in https://github.com/galaxyproject/galaxy/pull/4465. The PR specifically tests accessing invocations for published workflows, but I think the security check should now work for shared workflows as well. It would be great if you can confirm this works for you now.

**Comment by greenwoodma** [comment]
@mvdbeek I've just tested this and yes the PR seems to now allow me to access the details of an invocation even if I don't own the original workflow. Thanks!

**Comment by mvdbeek** [comment]
OK, thanks for reporting the bug and confirming the fix works for you!
