### ISSUE TITLE
Workflow Export: 'inputs' names should match tool_state?

### ISSUE THREAD

**Issue by fbartusch** [galaxyproject/galaxy#4518]
I work with .ga files of workflows and wanted to extract the inputs of the workflow steps, but the provided names aren't very useful. I think the names should match the ones given in the step's tool_state.

I'll give an example is the section for the tool:
toolshed.g2.bx.psu.edu/repos/iuc/bcftools_consensus/bcftools_consensus/1.4.0
I use Galaxy 17.01, but I think this is also true for 17.05.

```
            "input_connections": {
                "input_file": {
                    "id": 12, 
                    "output_name": "output_file"
                }, 
                "sec_default|fasta_ref": {
                    "id": 2, 
                    "output_name": "output"
                }
            }, 
            "inputs": [
                {
                    "description": "runtime parameter for tool bcftools consensus", 
                    "name": "sec_default"
                }, 
                {
                    "description": "runtime parameter for tool bcftools consensus", 
                    "name": "sec_default"
                }, 
                {
                    "description": "runtime parameter for tool bcftools consensus", 
                    "name": "input_file"
                }
            ],
           "tool_state": "{\"__page__\": 0, \"sec_default\": \"{\\\"sample\\\": \\\"\\\", \\\"mask\\\": {\\\"__class__\\\": \\\"RuntimeValue\\\"}, \\\"fasta_ref\\\": {\\\"__class__\\\": \\\"RuntimeValue\\\"}, \\\"iupac_codes\\\": \\\"false\\\", \\\"select_haplotype\\\": null}\", \"__rerun_remap_job_id__\": null, \"chain\": \"\\\"false\\\"\", \"input_file\": \"{\\\"__class__\\\": \\\"RuntimeValue\\\"}\"}", 
```

In my case there are three possible inputs, I use two of them in my workflow: 'inpu_file' and 'sec_default|fasta_ref'.
I need the name of the unused input for my application. This would be 'sec_decault|mask', but the full name does not appear in the 'inputs' section.

Originally I want to parse runtime parameters of a workflow step from the tool_state. For this example my parsing returns also 'sec_default|mask' as runtime parameter, but it isn't actually used by the tool in the workflow. Therefore I don't want to consider this runtime parameter, but I need a more meaningful name for the inputs to check for that.

**Comment by jmchilton** [comment]
You should not use the data parameters as runtime inputs - it works in the UI but I really don't think it should. If you want to assign a value to that input at runtime via the API - I would attach an input data module (in the workflow editor these are under the "Inputs" section as shown below) block to that input and give it a name. The name can then be used when creating the API request. The exported workflow definition and the API request to use can both be much simpler if you modify your workflow to do that. You can also add a workflow specific description for the input.

Is that an option in this case? It may not be an option if you aren't specifying the value everytime because data inputs aren't optional.

**Comment by fbartusch** [comment]
Thanks for your answer. I understand what you mean, but I don't think that this is a solution to my problem. I think my description was not very clear, I try to describe it in other words:

I don't want to assign a value to that input (in my case the 'sec_default|mask' input) via the API. Given a workflow file, I want to get ALL runtime inputs a user has to specify to be able to execute the workflow via the API.
I parse these runtime inputs from the tool state string. Then I will also get the 'sec_default|mask' input as runtime input. But I don't want to consider this input, because it's unused.

I want to detect these unused inputs by checking which input has a corresponding input connection. This is not possible because the names of the inputs are not really fully qualified. In the example above I would expect that the workflow file looks like:

            "inputs": [
                {
                    "description": "runtime parameter for tool bcftools consensus", 
                    "name": "sec_default|fasta_ref"
                }, 
                {
                    "description": "runtime parameter for tool bcftools consensus", 
                    "name": "sec_default|mask"
                }, 

Then I could easily check for unused inputs, but the names of the inputs in that section aren't fully qualified.

**Comment by fbartusch** [comment]
@jmchilton gentle reminder

**Comment by jmchilton** [comment]
> I want to get ALL runtime inputs a user has to specify to be able to execute the workflow via the API.

I would only run workflows via the API that have all required data input parameters attached to input modules. This is a more structured way of specifying inputs.

If this is not possible and you'd like to emulate runtime inputs on tools instead of on data input modules, I don't know how to infer from the runtime data parameters from the exported workflow JSON - it may very well not be possible. I'd take a look at the workflow run form - it fetches a alternative form the workflow that perhaps make it clear.

<img width="1313" alt="screen shot 2017-12-18 at 9 48 58 am" src="https://user-images.githubusercontent.com/216771/34111809-c38a5b6a-e3d8-11e7-89d1-7bd871d379a1.png">

https://usegalaxy.org/api/workflows/893612e4e7a269b9/download?style=run

I'm not sure I'd consider that a stable API endpoint though so use with caution.

**Comment by hexylena** [comment]
Hopefully the concerns were addressed here in the final comment.
