### ISSUE TITLE
Question: Do we have a tool for sending a dataset to an AWS s3 bucket?

### ISSUE THREAD

**Issue by shadycuz** [galaxyproject/galaxy#4614]
I found this but I don't know if this is what I want or how do I turn it on?

https://github.com/galaxyproject/galaxy-lib/blob/master/galaxy/objectstore/s3.py

Thanks.

**Comment by hexylena** [comment]
Since no one has replied; no we do not have a tool for sending data to S3.

Galaxy has not started implementing infrastructure for securely storing user credentials to third party services, so it may be some time (think years) before such a tool could exist and be generally useful while also being secure.

What you have found is the object store backend of galaxy, galaxy can use an s3 bucket to store every dataset, but this requires administrator configuration of galaxy.

If you are using a private galaxy instance, you're free to implement a tool which can do this though :) Let us know if you have questions about this.
