### ISSUE TITLE
HDCA state support (allows hiding outputs immediately)

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#4735]
HDCAs don't really know any other state than `ok`, I think. To let the user know something is happening the collection elements are added as HDAs to the history and are hidden when the dataset enters the OK state. It would be better if these were immediately hidden, and collections would display a hierarchic state (at least 1 failed dataset == collection in failed state, at least 1 dataset in running state == running).
I think that's important for scaling collections.

**Comment by jmchilton** [comment]
Be careful. I'm trying to think of a way this scales (and have been since day one) - I don't want 10000 different job threads doing complex logic on recursive collection states in already complex database transactions.

One route - is to add a few attributes to the DatasetCollection class - ``num_datasets``, ``ok_dataset_count``, ``failed_dataset_count``. Every time a dataset finishes you could then fetch all the collections that contain that dataset (recursively) - and issue small database transactions that increment the counts using the database (not in sqlalchemy) - like we do with ``hid`` in histories. This is much more complex though because an HDA only belongs to one history - to get the counts of a recursive collection you will need to update multiple collections (or only store the state in the HDCA and not the collection). There are then conditions you could claim certain things about the state while still allowing a indeterminate state if something goes wrong in the coordination of all of this (if ok datasets == num_datasets - that is an okay collection, is failed_dataset_count > 0 - that is a failed collection, etc...).

A second approach would be to do this in a separate thread all together. The jobs update and message is sent to a dataset collection state manager that triggers like a state update queue. This way we could de-duplicate the messages for better performance and be sure that a full scan of the collection is initiated after the last job completes (if you do this in the job handler itself as part of the job completion process you can easily imagine say the last two jobs easily finishing at roughly the same time - both checking the collection to see if they are the last and failing and failing to update the state to "okay"). Here the GUI could also trigger a full check for the collection for non-terminal collection states every 30 seconds or something without crushing the server - this way if something went wrong but all the dataset states are terminal - eventually the collection would get a terminal state itself.

Maybe I'm full of it or pessimistic and there is something really obvious and scalable that can be done here. I'd only ask that whatever is implemented - that it not cause an O(n) increase in the amount of time it takes to dispatch or finish individual jobs (because that turns in O(n^2) for the collection as a whole). These are already super slow operations already - and I don't want the slowdown to be compounded by the collection input size in this way.

As I've mentioned other places - I think a lot of this could be mitigated by better visual queues to the user. The "ok" green for collections is a problem because they think it is okay when it is not. It doesn't need to be that green though and it doesn't need to look so much like a dataset. There are buttons that allow users to interrogate the collection state. If the user clicks on a collection - they should be able to tell what the state of the contents are quickly - I don't mind triggering an O(n) query of the database at that point for instance (it is during job creation and finish as well as on a loop with the full history panel that such a trigger seems most problematic).

**Comment by jmchilton** [comment]
I thought there was a more general issue we discussed this on but I can't find one. I'll xref https://github.com/galaxyproject/galaxy/issues/1244 since it has a few comments.

**Comment by jmchilton** [comment]
What about this for an intermediate term solution for this and #1790 - I'm reworking how the collection is created a bit so the jobs can be scheduled in multiple batches in
https://github.com/galaxyproject/galaxy/pull/4584/commits/a02c0a45208f03bbe058d47623636ff9868dcd20. What if I go a bit further and I pre-create the collection with a populated_state of 'new' before I start creating the jobs - so it is yellowish to the user - like a dynamically discovered tool output collection - then I set the populated state to ok at the end once all the jobs have been submitted. If there are any problems - I can set it to a failed state and the issue displayed to the user.

This would fix #1790, it would fix another issue no one has ever reported where there is no real input if there is some problem creating one or more jobs during workflow invocation there mapped collection isn't created and there is no UX feedback. This way we could take the collection and make it failed.

The collection would still be "green" before all the jobs are finished but if any of the jobs failed I think they would unhide themselves and so there would at least be some visual feedback that there was a problem.

**Comment by mvdbeek** [comment]
Thanks @jmchilton, you've obviously put more thought into this than me, and the intermediate solution sounds good to me. Naively I wouldn't have assumed that querying collection datasets for state would be an expensive operation, even for thousands of datasets, but I haven't tested that at all.

Updating the state in the job handler's finish method does sound interesting too

> (if you do this in the job handler itself as part of the job completion process you can easily imagine say the last two jobs easily finishing at roughly the same time - both checking the collection to see if they are the last and failing and failing to update the state to "okay").

Couldn't all finished jobs check which/if the output datasets belongs to a collection and update the OK/error/running count of that collection ?

**Comment by jmchilton** [comment]
> you've obviously put more thought into this than me

Hardly means I haven't been thinking incorrectly though. I thought a lot about #4119 and convinced myself it could never be fixed and then you came along and made everything sunshine and rainbows.

> Couldn't all finished jobs check which/if the output datasets belongs to a collection and update the OK/error/running count of that collection ?

That is why I said updating counts would be a potential path forward - I have no issue with the job trying to figure out what collections its outputs belong to. I just don't want the job to try to determine if all the outputs of that collection are complete. So if "ok" means no outputs have failed - great! If "ok" means my ok dataset count equals my size - great! If instead "ok" means - I've checked all the outputs and they are all "ok" and in terminal states - well that is a relatively expensive check and one I'd rather not do in the job handler's finish method (I don't want 25,000 threads each checking 25,000 rows). 

With the counts - there is a lot of complex state tracking to do here - because even the total count needs to be updated this way and we need to update things when an HDA state changes (e.g. a "FAILED_METADATA" becomes "OK").

So lets say you map a list of lists over a tool with a dynamic dataset collection output. Then you will need to update both output list depths counts with each list discovered, if a dataset discovery fails, you'll need to somehow track that because it won't be new total datasets or failed datasets. So state could be "# sub collections to populate == # sub collections that have been populated && total_datasets == okay_datasets" or "# jobs to complete == # jobs completed && total_datasets == okay_datasets".

It may well be doable - I'm just not confident in complex state tracking like this. I feel like invariably there will be inconsistent counts - but I could totally be wrong. Also I'm also not trying to discourage you - if anyone could do this it would be you I think. Just if you do decide to do it - definitely use database primitives and isolated DB transactions when you are updating rows that many threads will be updating at the same time.

**Comment by jmchilton** [comment]
I'm falling into a bit of a hole here... 

I'm trying to implement what I described above and I think there are a lot of good benefits to pre-creating the mapped over collections before the jobs - certainly it would fix the random failures to hide #1790 and could serve as a way to track partial step progress for #3883. For large collections it will be a better user experience - but I'm worried for smaller collections people are used to seeing the progress as gray turns to yellow turns to green. Like it is an ugly way to represent the state - but it is better than just showing the green dataset collection. Which is making me think to improve the performance and pre-create the collections - I need to tackle the state problem.

One thing that occurs to me is that basing the state of a collection on its jobs is potentially easier than doing it on the datasets. The number of datasets change as discussed above and it requires recursive-ish SQL to dig at that - but you can imagine a fixed number of flat jobs for each implicit collection - they don't have the same hierarchy. We could call that a CollectionJobSet or something and track that in the database. We could also keep track of the counts on that instead of the HDCA or the DC - this way you don't have to worry about multiple levels of DCs that need to be updated if you think about copying HDCAs also having that construct might be useful. Another advantage to this approach is that all the mapped outputs for an "Execute" click or a workflow step would share the same CollectionJobSet - so you could imagine caching the results of the state on the client side and using it for multiple collections.

**Comment by mvdbeek** [comment]
> One thing that occurs to me is that basing the state of a collection on its jobs is potentially easier than doing it on the datasets.

I agree, that makes sense. Do we need to take care of collections that could be created by more than one job ? For instance zipping 2 collections into one ?

**Comment by jmchilton** [comment]
> Do we need to take care of collections that could be created by more than one job ? For instance zipping 2 collections into one ?

There are two ways HDCAs can be created:

- They can be created from a single job - output dataset collections that aren't mapped over. (e.g. taking a single fastq file and splitting it into a pair).
- They can be created from mapping over a collection - all dataset outputs and dataset collections outputs would have matching implicit collections that are HDCAs. (E.g. mapping bwa over a list and getting a list of bam files back.)

The state of the first could be inferred just from the corresponding Job - the state of the second would benefit from this new "CollectionJobSet" concept. To make things more uniform we could either subclass HDCA into HDCA and ImplicitHDCA or we can create a dummy CollectionJobSet with just one job for the first case. If I wasn't saddled with all this legacy crap from @jmchilton I'd probably prefer the first - but the second seems more pragmatic.

TODO: verify there is a dummy job or something created for collection operations.

**Comment by jmchilton** [comment]
With the project JS mutex released - #4763 (requires a ``make client``) now supports gray, yellow, green, and red semantics that should be more comfortable and informative based on the on idea of collecting jobs together I described above. It also hides collection outputs by default at the outset - since the collections will now be yellow and gray for a much longer time to convey this information. I landed up calling the Python model object ``ImplicitCollectionJobs`` instead of ``CollectionJobSet`` - since a single job might produce an HDCA.

**Comment by dannon** [comment]
(sorry if the perceived 'project JS mutex' was inconvenient for anyone -- there really wasn't another good way to do all that we needed to do with #4435 and  #4827)

**Comment by jmchilton** [comment]
@dannon Absolutely no problem - I'm glad it is done - and I'm really finding the client a lot easier to develop in and think about now. If anything the comment was just to make an excuse on my half for why it took a month to get this prototype this far - it was me being self conscious.
