### ISSUE TITLE
rerun/tool info: oddity with data set collections

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#4860]
I run a tool (eg trim galore or hisat2) on a (paired) data set collection. When I open the tool form via the rerun button of a data set the input is not set correctly to the collection that was actually used as input, but the topmost fastq collection in my history is chosen. 

Also the info page ("View Details") does not show which data set was used as input, but only two rows: 

Single-end or paired-end reads? paired_collection 
Paired Collection No dataset collection.

So currently the only way to retrace the input seems to be that name of the data set collection that is set by the tool.

**Comment by mvdbeek** [comment]
I think the empty rows in "View Details" should be fixed by https://github.com/galaxyproject/galaxy/pull/4665/commits/19818cb380889e584741caf4a78462e0502f30c1, which is only in dev for the moment, the rerun behavior of the tool form I haven't seen yet. In general we should implement the rerun button for dataset collections ... .

**Comment by bernt-matthias** [comment]
I'm running on dev which I updated a day ago (https://github.com/galaxyproject/galaxy/commit/19818cb380889e584741caf4a78462e0502f30c1 is included).

**Comment by mvdbeek** [comment]
And the job has been run on that version as well ? Could you add a screenshot to be sure we're talking of the same problem ?

**Comment by bernt-matthias** [comment]
Exactly. But the input collections have been created before the update.

**Comment by mvdbeek** [comment]
That shouldn't be a problem, I think.

**Comment by blankenberg** [comment]
Seeing similar behavior here.
 - Create paired dataset collection of fastq files
 - Run e.g. Trimmomatic (Creates 2 output collections: paired and unpaired)
 - Run bwa-mem on Paired output of Trimmomatic

![image](https://user-images.githubusercontent.com/1231190/37713881-90d01d18-2cee-11e8-847f-40866682f275.png)

info on one of the bwa outputs in the collection -- 'No dataset collection':
![image](https://user-images.githubusercontent.com/1231190/37714066-f4760cf6-2cee-11e8-9453-aeb20a0ca13b.png)

rerun on same bwa output -- 'unpaired' selected:
![image](https://user-images.githubusercontent.com/1231190/37714099-101482a8-2cef-11e8-9f1d-a93bdf5ffa97.png)


Since it has no value for input paired collection, it is selecting the 'newest' paired collection. 

Ideally in this specific case, it would select the individual pair from within the dataset collection (rerunning a single item within the collection), and also we should have a separate 'rerun collection' button that reruns the whole collection job.

Alternatively, selecting the originally selected collection would make sense, since that was the original action, but this isn't quite as nice as proposed in previous sentence.

However, in the very least it should be displaying an obvious error to the user when rerun is selected, instead of silently choosing the newest valid collection.

**Comment by blankenberg** [comment]
This was on dev @ dbf6f58251719f721da13e2d605f616956391076

**Comment by mvdbeek** [comment]
Is it possible this happens when the input is in a conditional and/or the input is a paired collection? I think have seen the right and the wrong behavior here.

**Comment by blankenberg** [comment]
In this specific case it is a paired collection inside of a conditional. Haven't fully checked other combinations.

**Comment by bgruening** [comment]
@blankenberg @bernt-matthias is this one fixed with https://github.com/galaxyproject/galaxy/pull/9802
