### ISSUE TITLE
Mergebot

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#5055]
Implement mergebot for building client artifacts in PRs.

Reach a point with https://jenkins.galaxyproject.org/job/galaxy-mergebot/12/console but Jenkins needs yarn.

**Comment by jmchilton** [comment]
Made some progress using this docker invocation that I'll document here in case others need to build Galaxy's client without yarn installed:

```
docker run -v `pwd`:`pwd`:rw -w `pwd` -u $UID node /bin/bash -c 'make client'
```

**Comment by jmchilton** [comment]
More progress - a successful mergebot merge in my branch - https://github.com/jmchilton/galaxy/pull/63#event-1371020697.

**Comment by dannon** [comment]
So you have the bot actually doing the merges?  I imagined committers continuing to merge as usual, in case of conflict resolution, any manual stuff necessary, etc.  Then the bot would be a simple job to check after each commit to dev/master/whatever that would just `make client-production` and commit the diff in /static if there was one.  (I really don't want to have to talk to the bot to merge stuff).  This seems more robust to me, too.

Sorry if this is a https://www.youtube.com/watch?v=gqQ99s4Ywnw moment.

**Comment by jmchilton** [comment]
@dannon I think I disagree but I'm not so eager to die on this hill as the source map issue. Are you saying the person that merges the PR should be the one to run the client build as a best practice so that bot is there just in case that is missed - or are you saying the best practice should be for the reviewer to merge as is without static changes and let the bot do its thing 10 minutes later?

**Comment by dannon** [comment]
The way I saw it working was:

- PRs never contain /static changes
- Test infrastructure that requires a built client handles that as a part of the test setup
- Committers merge PRs as usual, based on test suite results from built client, and local testing with a manually built client if they want.
- Builder checks on commits to the branch, rebuilds client when necessary, keeping all the client building completely separate from other commits *and* the merge commits of the actual substantive changes.

I want the name on the merge to be the committer that authorized and handled it, and I really don't want to have to talk to a bot to do the merging.

(this would continue to work the exact same way when we're at the point when we don't even *include* built artifacts in the repository, minus that last step -- and we can easily strip all these atomic build commits out)

**Comment by jmchilton** [comment]
The part we agree on is that the Selenium tests need to build the client if we don't include commits to static. I've done that and at first glance it looks to be working here - https://jenkins.galaxyproject.org/job/docker-selenium/479/console.

Is having the person merging the PR building the client and including it as part of the merge a better process than the process we have today? Is that an incremental step we can take without disagreement?

**Comment by dannon** [comment]
I've been trying for years to get people to pull locally, rebuild, and commit that all as the merge, without success (this is how I personally handle every conflicted client PR *today*).  Not sure what you're suggesting as the incremental step here.

**Comment by jmchilton** [comment]
So last week Martin and I needed to coordinate when he was going to merge a series of my PRs because they all had repack commits. That is a lot of rebasing and coordination that could have been eliminated if he did the pack committing - it seems like that would be a step forward to me from the current workflow of the last couple weeks.

My problem with your proposal is that it leaves dev literally broken for periods of time. Maybe just like 10 minutes - but if Jenkins goes down, the hooks don't register, etc... the client may be out of sync with the API for larger periods of time - maybe a whole weekend for instance. It doesn't seem more robust - it seems less robust. Putting the onus of the pack commit on the merger instead of the PR issuer would mean we still get clean commit histories without conflicts and without these periods of dev brokenness.

I don't mind still implementing your described variant of the bot though as a failsafe - I just don't think it should be the best practice to have dev broken.

**Comment by dannon** [comment]
@jmchilton Maybe I don't understand the example -- why did martin *not* do the pack committing?

My opinion is that dev is for developing, it should be expected that it's constantly in a state of brokenness, and nobody but developers should be running it.  I'm more worried about people not being able to work productively because the bot isn't listening to `@galaxybot merge this` than I am that the client is possibly a build behind -- which we can fix manually (any committer) on the off chance jenkins is misbehaving.

This tack of arguing completely skips what I mentioned above regarding us removing build artifacts from the repo *entirely*.  The expectation that dev (at least) doesn't come with built artifacts is going to happen, hopefully soon, and I think we should build policy around that.

**Comment by jmchilton** [comment]
> My opinion is that dev is for developing, it should be expected that it's constantly in a state of brokenness, and nobody but developers should be running it.

We have put a tremendous amount of work into the 7 green check marks - I disagree that dev should be a constant state of brokenness. I think the goal should be to make it constantly deployable.

If we are introducing the expectation that the client artifacts might not work with dev at times - why not just drop them all together from dev now? I'd prefer no artifacts to artifacts that might just randomly not work in random ways. Artifacts that might not work means developers do need yarn if they expect to work with Galaxy's dev branch and if that is a requirement we are adding lets just drop the artifacts from dev.

Updated: I changed my comment to embed a quote from reflect the current state of your past comment I was replying to.

**Comment by gregvonkuster** [comment]
I have several "production" Galaxy instances that track the "dev" branch because they require components that are not yet included in a release branch.  This is not always the case, but there are instances where an enhancement PR (e.g., support for a new datatype) is submitted just after a release, so it will not be available in a production release for 3+ months.

Of course, another approach for handling this is to apply the PR to the local Galaxy instance.  But more often than not, I've found that this results in more overhead than just tracking the dev brach in some cases.  This only works, however, if admins can assume the dev branch is not in a broken state.

I'm with @jmchilton on this issue.  I've always felt that commits to the dev branch should pass a standard set of tests before they are merged.  I constantly argued for this long ago when I was part of the core team and commits were not PRs.  Even then, core developers should generally have run the functional test framework on local changes before they were committed.  This didn't always happen, and in those cases, it usually resulted in problems.

But this process has become much more streamlined since those days because every commit is now a PR, and the functional test framework has been significantly enhanced since then.  I think it is imperative to make every attempt to keep the dev branch in a functionally correct state.

**Comment by jxtx** [comment]
I have to disagree with dev being in a constant state of brokenness. It may be subtly broken. It may have bugs that have not yet been found. But it shouldn't be **deliberately** broken. The tests should pass.

**Comment by dannon** [comment]
I feel like this argument is *significantly* exaggerating the 'state of brokenness', in this particular context.  My expectation is that build artifacts are available ~2 minutes after a merge.  If they aren't, if jenkins is dead, they're damn easy to add.

Somehow this has gone hyperbolic, and now "we've put a lot of effort into the 7 green checkmarks and now they mean nothing and the tests are irrelevant".

@jmchilton You never answered the question about why you guys didn't just do the manual merges last week.  That's a concern to me, if we're going to go down that path  Is it that people just aren't comfortable enough with the client, or with git?  We could have a little class or something?  I dunno.

**Comment by dannon** [comment]
@gregvonkuster I should have followed up with this question, for you, an actual deployer! :)

What's your plan for when the repository no longer includes build artifacts?  When you pull an update from upstream, is it unreasonable to ask that deployers do a `make client-production` for your local deployment, as a part of the update scripts you use?

**Comment by hexylena** [comment]
I guess we've now fixed this in a different way and it seems to work ok?

**Comment by jmchilton** [comment]
I feel like mergebot keeping master updated and forward porting older fixes automatically would still be available. I think a lot of the pieces were there in the work I did, I'm re-opening if that is okay.

**Comment by hexylena** [comment]
Oh totally fine, that's a good future direction for this issue! only closed because sounded like described problems were finished. Excellent that we can reuse the work you did then :)
