### ISSUE TITLE
BED dataset extraction from UCSC Table browser results in odd comment line assignment

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#5127]
**Tested at Main** https://usegalaxy.org running Galaxy version 17.09, commit a82d325d18375797ce8ab53366320f3c9a772ab7 

Does not impact all extracted BED files but there is no apparent difference between those with the problem and those without. Changing the metadata directly - with autodetect or direct assignment -
 does not resolve the problem.

Test tool (Extract DNA) run on the data ignores the "comment" assignment and pulls out sequences for all the lines in the given input.

**Test history:** https://usegalaxy.org/u/jen/h/test-history-extract-indexed-genome

**Possibly related to:** https://github.com/galaxyproject/galaxy/issues/2175

Examples:

**BED dataset **without** the problem, dataset 15:**

<img width="250" alt="screen shot 2017-12-04 at 3 43 19 pm" src="https://user-images.githubusercontent.com/8999735/33583043-2e554774-d90d-11e7-9af2-a404f8abab81.png">

Shown in vi with whitespace chars revealed:

<img width="502" alt="screen shot 2017-12-04 at 3 41 35 pm" src="https://user-images.githubusercontent.com/8999735/33583136-ac8a646c-d90d-11e7-93f8-e55c56df7c79.png">

**BED dataset **with** the problem, dataset 17 input:**

<img width="248" alt="screen shot 2017-12-04 at 3 42 59 pm" src="https://user-images.githubusercontent.com/8999735/33583156-c462deca-d90d-11e7-887f-f77e74bdc373.png">

Shown in vi with whitespace chars revealed:

<img width="505" alt="screen shot 2017-12-04 at 3 42 24 pm" src="https://user-images.githubusercontent.com/8999735/33583177-d2c0fe8e-d90d-11e7-9008-2ff0dec2f145.png">

**Extract Genomic DNA on dataset 17 in output dataset 34:**

<img width="241" alt="screen shot 2017-12-04 at 4 04 13 pm" src="https://user-images.githubusercontent.com/8999735/33583188-e8112ae8-d90d-11e7-8333-bbdfffab74cb.png">

**Comment by nsoranzo** [comment]
The "problem" with the second BED file is that it uses a scaffold id from Ensembl ( http://www.ensembl.org/Xenopus_tropicalis/Location/Overview?r=GL172663.1:1-4425020 ) in the `chrom` (i.e. first) column, while `Bed.set_meta()` [checks](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/datatypes/interval.py#L415) that it starts with one of ['chr', 'chl', 'groupun', 'reftig_', 'scaffold', 'super_', 'vcho'](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/datatypes/data.py#L42).
Maybe we can drop lines 415 and 416, since this is not the `sniff()` method and the dataset has already `bed` datatype.

**Comment by jennaj** [comment]
Stray open ticket resolved some time ago. Retested it anyway, not a problem. Closing.
