### ISSUE TITLE
History Panel Style Access to Workflow Invocations

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#5142]
We talk about this a lot but it doesn't seem to have an issue as far as I can tell. Running workflows need to be present somewhere the user can readily see them in the analysis view. We need to be able to provide feedback on workflow scheduling status and runtime errors that are encountered, we need to be able to navigate to outputs, see inputs, track recorded parameters, etc.... There are cool things implemented in the backend such as pause to review steps that can't really be used without this feature as well.

I don't know if they should be a separate tab in the history panel, if they should be alongside datasets like collections are, or if they should be their own thing somewhere else - but they need to be somewhere.

**Comment by blankenberg** [comment]
This is greatly needed. 

I can 'run' a workflow and every UI indication shows that it worked: green success message in UI, and a new history is created. But several hours later I just have my new target history that is empty. 

Is it working really hard? Did it fail and give up? What is going on? If it failed, it should at least let me know to stop waiting and hoping. 

Failures due to scheduling used to get displayed to the user, but now that it is asynchronous they do not.

xref https://github.com/galaxyproject/galaxy/issues/5265#issuecomment-365964018

**Comment by jmchilton** [comment]
As a short term fix we could also monitor the invocation from the workflow execution landing page where we have a lot more freedom - at least then it is a regression of behavior relative to the synchronous case.

**Comment by blankenberg** [comment]
I think something is way better than nothing and this should be a pretty quick change?

Maybe show a paginated list of the last 5-10 workflows and their status + cancel, etc (if running) buttons would be a great start.

**Comment by martenson** [comment]
xref https://github.com/galaxyproject/galaxy/pull/8699

**Comment by mvdbeek** [comment]
We've got something like this with https://github.com/galaxyproject/galaxy/issues/5179 and the invocation details component. We should maybe make those navigable directly from the history, but that seems like a different project.
