### ISSUE TITLE
make Galaxy build client on startup

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#5347]
autosetup nodeenv and friends, perform client check on startup and `make client(-production?-maps?)` so dev is again clone-and-go

xref: https://github.com/galaxyproject/galaxy/pull/5128

~~We probably want this for 18.01~~ This only applies to dev, releases have built client for now as pointed out below.

ping @natefoo @dannon @mvdbeek @nsoranzo

**Comment by dannon** [comment]
Just to be clear, we're including built artifacts for releases, always, since that's the primary distribution mechanism we have (edit: well, always until the distribution approach changes to packages or the like).  We're just not including them for `dev`, so this shouldn't be an 18.01 milestone I don't think.

I think @nsoranzo was going to work on building out the infra here, though, per conversation yesterday.

**Comment by nsoranzo** [comment]
Yes, I can work on this, but (as said elsewhere) I'll be busy for around a week.

**Comment by dannon** [comment]
@nsoranzo If it'll help, I'm happy to do it too, just let me know.

**Comment by mvdbeek** [comment]
Also related is planemo with `--galaxy_root`, that should trigger a client build if necessary, https://github.com/galaxyproject/planemo/issues/750

**Comment by bgruening** [comment]
And the Docker image also assumes currently that the dev branch ships/builds the client on startup.
