### ISSUE TITLE
Installing tools+versions needed for a workflow

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#559]
When I download the workflow I want to use, I am having hard time figuring out which tools and their version are the _exact_ ones that the workflow needs. Alternatively, each tool and version could have searchable hash codes. I would then obtain all hashes my workflow needs and installed them one by one from toolshed. 

from @biomonika on [trello](https://trello.com/c/jS3f7xW7/2307-automatically-install-tools-that-workflow-needs)

@peterjc notes:

> When an Admin installs a workflow this seems a natural thing to offer, reusing the existing dependency interface.
> 
> When a non-Admin imports a workflow, at least providing a summary of missing workflows would be good (that could then be passed on to an Admin).

@erasche note: this had 5 +1s on trello.

**Comment by mvdbeek** [comment]
The non-admin part should be easy enough, I could do that.

**Comment by hexylena** [comment]
@mvdbeek wunderbar!

**Comment by martenson** [comment]
xref: https://github.com/galaxyproject/galaxy/pull/3626

**Comment by mvdbeek** [comment]
I think we've come a long way since then ... the workflow *.ga file now contains the exact repository details, we can install [workflows including tools through the API](https://github.com/galaxyproject/galaxy/pull/3064) thanks to @manabuishii and @davebx has implemented the UI in https://github.com/galaxyproject/galaxy/pull/3626
