### ISSUE TITLE
GenomeSpace Can no longer launch Galaxy with files from GSUI

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#5595]
You used to be able to drag and drop (multiple) files inside of GenomeSpace onto the Galaxy icon to allow the files to be sent to Galaxy along with the browser opening a new Galaxy window. While you can still launch Galaxy from within GenomeSpace, you can no longer send the files. GenomeSpace is still sending the correct information, so this is an issue on the Galaxy side. 

Issue probably appeared starting at https://github.com/galaxyproject/galaxy/pull/1814.

![image](https://user-images.githubusercontent.com/1231190/36602852-1247e0dc-1887-11e8-9dbe-e4f1f1666a59.png)
![image](https://user-images.githubusercontent.com/1231190/36602876-2383c168-1887-11e8-9bf9-55a2eab08574.png)
![image](https://user-images.githubusercontent.com/1231190/36602915-3b0a2700-1887-11e8-84c7-eac2de7ad89d.png)

**Comment by nsoranzo** [comment]
Ping @nuwang

**Comment by nuwang** [comment]
To fix this, the private tool within GenomeSpace has to be defined as follows:
```
https://<galaxy_url>/tool_runner?tool_id=genomespace_push
```

instead of the previous: `https://<galaxy_url>/tool_runner?tool_id=genomespace_importer`

The reason for having a different tool wrapper is because only data_source tools can be executed via a GET request through the tool_runner, and therefore, genomespace_push has been defined as a data_source tool, while genomespace_importer is no longer a data_source tool so that it can be executed within a workflow. That's the only real difference between the two wrappers currently.

I guess this needs to be documented somewhere, perhaps in galaxy hub? I'll also file an issue with GenomeSpace so that the public tool definition for Galaxy can be fixed.

**Comment by nuwang** [comment]
@blankenberg @nsoranzo If there's a better solution for this, please let me know, I'd be happy to add in a fix along with the other multi-file selection enhancements that are being done. This duplicate wrapper xml thing isn't great, but it was the only workaround I could find at the time.

**Comment by liefeld** [comment]
Folks, I am happy to make this change in the GneomeSpace registration for Galaxy.  it seems that genomepace_push is not yet in the public galaxy, so let me know when it is and I'll make the update ASAP -- Ted -- jliefeld at cloud.ucsd. ee dee you

**Comment by martenson** [comment]
With genomespace going away in a month (http://www.genomespace.org/news/the-genomespace-project-is-ending) I am closing this issue.
