### ISSUE TITLE
HOW to change the language of the website

### ISSUE THREAD

**Issue by frank-zsy** [galaxyproject/galaxy#5624]
Since I don't see any options about i18n or language setting in config file, I assume that the language of the website should fit the browser request.

But my request header accept-language is "zh-CN,zh", still I got the English version of the website, what should I do to get the Chinese version?

Thx.

**Comment by shenweiyan** [comment]
Galaxy 的中文 i18n 文件在 <GALAXY_ROOT>/client/galaxy/scripts/nls/zh/locale.js。一般来说，只要你的浏览器支持中文就可以。

如果不行请尝试以下操作：
```
# make sure node.js and npm installed.
$ cd <GALAXY_ROOT>
$ make client
$ cd <GALAXY_ROOT>/client
$ node_modules/grunt-cli/bin/grunt 
```

**Comment by frank-zsy** [comment]
@istevenshen 哦哦，“历史已空”等确实是中文的，但看locale.js，汉化的内容非常少，我希望整个网站都是中文的，是不是现在是做不到的？

**Comment by dannon** [comment]
@Frankzhaopku Correct, there's a lot of Chinese localization that could use improvement and more coverage -- let me know if anyone would like pointers on how to approach this and I can help!

Since the issue of having it show up (understanding there isn't a lot of coverage) is resolved, I'm going to close this out.
