### ISSUE TITLE
Post-submission screen is not necessary

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/galaxy#5792]
When starting a job on a collection a tool creates this (see images below) in the center pane. Wouldn't it be better to just say "Job on collection X have started"

![screen shot 2018-03-27 at 2 02 06 pm](https://user-images.githubusercontent.com/4291636/37985761-a57e3d2a-31c7-11e8-96da-124002c6e551.png)

**Comment by hexylena** [comment]
I think there was a suggestion somewhere (@bgruening?) to use a small graphic to show the mapping (`n` inputs → tool → `m` outputs) rather than the huge list of files.

**Comment by bgruening** [comment]
Yes, I was suggesting (actually on different places) to demonstrate with small little sketches, what a collection is, how it is mapped/reduced etc ... This can be comic like strips to explain the map-reduce concept, but also paired-collections etc ...
ping also @mblue9

**Comment by mblue9** [comment]
>Yes, I was suggesting (actually on different places) to demonstrate with small little sketches, what a collection is, how it is mapped/reduced etc ... This can be comic like strips to explain the map-reduce concept, but also paired-collections etc ...

Sounds like a cool idea to me. I also would prefer something like that and/or a simple "Jobs on collection X have started" instead of the current listing of all the files (when I get a big long list I sometimes can't help thinking "uh oh...that looks like a lot of files...how many will I need to look at 😟")
