### ISSUE TITLE
add backoff abstraction function to Galaxy core libs

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#5951]
We now had multiple use-cases for a jitter function and I think its worth to implement a general one or depend on a library to enable this functionality in Galaxy.

ping @erasche

**Comment by hexylena** [comment]
Personally I'd prefer https://github.com/litl/backoff rather than just jitter since this gives us a nice retry abstraction which we can use whenever networked requests come into play. It's py3 ready, I've used it in a couple projects and been quite happy with it.

**Comment by mvdbeek** [comment]
We've got `RetryActionExecutor` which we use in pulsar and in https://github.com/galaxyproject/galaxy/blob/b47efd4adedb781056423bda4112a5b46a72489b/lib/galaxy/jobs/runners/util/cli/shell/rsh.py#L66 -- if that is enough we might use this, otherwise we could replace this with whatever library we like.

**Comment by hexylena** [comment]
I guess it will be added whenever someone next needs it in Galaxy's codebase
