### ISSUE TITLE
Add a  'Analyse data' url customisation feature

### ISSUE THREAD

**Issue by BioinformaticsPlatformWIV-ISP** [galaxyproject/galaxy#6050]
Hello,

At the moment we can customise various tabs links from the main Galaxy breadcrumb including : wiki,support, galaxy logo trough dedicated variable in galaxy.yaml . Sadly this option is not available for the 'Analyse data' link  that always redirect to '\\'.   Would it be possible to add this functionality to galaxy UI and link it to a new variable : 'analyse_data_url' in galaxy.yaml ?

Thank you.

**Comment by martenson** [comment]
@BioinformaticsPlatformWIV-ISP
You can change it in your instance by modifying the code [here](https://github.com/galaxyproject/galaxy/blob/dev/client/galaxy/scripts/layout/menu.js#L35) and running `make client-production` in the root folder.

Making it configurable is not very likely on our side I think, since changing it would imho interrupt user experience of the 'home' button. What is your use case?

**Comment by BioinformaticsPlatformWIV-ISP** [comment]
Thank you for your quick reply.  

That's exactly why we have to redirect the 'Analyse data' link :  to ensure the continuity of the user experience with this 'home' button.  The user would expect to be redirected to the 'home' page  when they click on the button and not to the root of the website. 

By default both are the same, but we have change it  (trough nginx) in ours Galaxy public instance available at https://galaxy.sciensano.be/ .  The users have to accept usage policy before being able to access Galaxy itself.  The static page that allow this behaviour became the new root of this Galaxy 'external' instance. Now, once logged, when user are clicking on 'Analyse data' they are redirected to the policy page ( '/') instead of the Galaxy main page ('/root').

**Comment by martenson** [comment]
@BioinformaticsPlatformWIV-ISP Most of the services on the web (and all Galaxies I know) either have implicit agreement "by using this service you agree to terms" or when registering account you explicitly check a box. Both of which provide better experience than a dedicated page.

If you really want to stick to your use I would use http redirect (with an agreement-cookie check) instead of nginx rules because the `/root` might also disappear at some point, since it is used only internally.

**Comment by BioinformaticsPlatformWIV-ISP** [comment]
To make it short : implicit one is not an option because most of the time users don't read it and that has impact on the provided support.  Check box at account creation is better for users but would induce more development and management (for instance in case of 'Terms' changes) than the current solution,  for a free and public service that doesn't have the (hierarchy) priority.

**Comment by bgruening** [comment]
> Check box at account creation is better for users but would induce more development and management (for instance in case of 'Terms' changes) than the current solution, for a free and public service that doesn't have the (hierarchy) priority.

We could make this extensible by using a webhook. I guess usegalaxy.eu is also in the need of something similar. ping @erasche

**Comment by martenson** [comment]
@BioinformaticsPlatformWIV-ISP is this GDPR related?

**Comment by BioinformaticsPlatformWIV-ISP** [comment]
@martenson No, its a coincidence. It has been set by the top management (of the Institute) as one of the mandatory conditions for the release of a public Galaxy hosted internally.  That being said, this functionality could be use to fulfil a GDPR compliance in the future.

**Comment by hexylena** [comment]
I think there is no developer time for implementing such a feature, hopefully editing the file and building the client locally can be sufficient for your setup. Sorry this could not be more easily customized.
