### ISSUE TITLE
Initial workflow form validation preemptively validates columns

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#6068]
Reported by @bgruening. This is an old behavior which can be considered being a bug. When initalizing the run workflow form all input elements are validated and errors are highlighted. In the case of column parameters linked to input fields this can lead to overvalidation using the initial dataset selection. The column parameters should not be validated until users select the correct dataset and then attempt to actually execute the workflow.

**Comment by bwlang** [comment]
This is appears to be a pretty serious error in the case that the wrong file is guessed...
in this example instead of a bed file with 6 columns a text file with 1 col was picked.

that produced a validation warning *AND* a "correction" 
![image](https://user-images.githubusercontent.com/61636/45975588-99f95a00-c012-11e8-9f69-b7474fcfc845.png)

we should either get rid of this validation or make it revalidate on user input changes.


After "correction" I get column1column1column1 instead of column1column2column3 that I need:

phage_lambda | 0 | 1 | phage_lambda:0 | 0 | - | phage_lambdaphage_lambdaphage_lambda
-- | -- | -- | -- | -- | -- | --

phage_lambda | 0 | 1 | phage_lambda:0 | 0 | - | phage_lambda01
-- | -- | -- | -- | -- | -- | --

The only way to make this workflow run correctly is make sure that only one file of the a bed-ish type is present so that the wrong file cannot be autoselected.
