### ISSUE TITLE
implicit conversion for fasta.gz does not seem to work properly

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#6088]
example history: https://usegalaxy.org/u/aun1/h/unnamed-history-13

xref: https://github.com/galaxyproject/galaxy/issues/6074

**Comment by jmchilton** [comment]
I can re-create this locally. fasta implicit conversions works in 18.01 and not in 18.05. When the options are listed in the tool the tool doesn't even show the conversion, it just assumes the compressed type directly matches with the uncompressed type. I'm not sure why this is, but on some level it I understand the bug - we use Python subclass comparison and the compressed type is a literal subclass but I thought it always had been. Maybe there was some magic pre-18.01 that prevented compressed types from matching with uncompressed types in subclass checks that got axed. I doubt it is related to #6074 though.

**Comment by jmchilton** [comment]
That thing I said was False, it worked before because FastaGz wasn't a direct subclass of Fasta like I thought (https://github.com/galaxyproject/galaxy/commit/fce2dd3ae801cd13a542388746b84f9cca2a4c48#diff-65d422c6d51f7d27ca4e18738f596c86L320), same with compressed Fastq formats they had a base class that didn't exactly match the subclass. That makes the approach in fce2dd3ae801cd13a542388746b84f9cca2a4c48 pretty unfortunate. This isn't great...

**Comment by nekrut** [comment]
At the moment these issues prevent any meaningful analyses with fasta.gz datatypes

**Comment by martenson** [comment]
@nekrut I do no think this is a fair statement, especially for tools that consume uncompressed datatypes. Outside of rulebuilder the workaround is to let galaxy auto-decompress on upload (e.g. leave autodetect on). 

That said we will fix and polish the rulebuilder so it supports these use cases, and make the implicit conversion work well again. The majority of the problems are already solved by the tandem of @jmchilton and @nsoranzo in the linked pr: https://github.com/galaxyproject/galaxy/pull/6093

**Comment by martenson** [comment]
fixed by https://github.com/galaxyproject/galaxy/pull/6115
