### ISSUE TITLE
Workflows API returns incorrect job state for version 18.05

### ISSUE THREAD

**Issue by MingChen0919** [galaxyproject/galaxy#6479]
when I use the API `api/workflows/[workflow_id]/invocations/[invocation_id]` to get the job state for each step of a successfully completed workflow. The job states are all 'scheduled' instead of 'ok'. 

For example,
a call to this `https://usegalaxy.org/api/workflows/df8013d4fb4ca933/invocations/a72290f9d6aff2f1` returns:

```
{
"inputs": {
"0": {
"src": "hda",
"id": "bbd44e69cb8906b50f65049f5ce2262d",
"uuid": "ea12c47f-91b8-4def-a206-83b6b5c7d086"
}
},
"update_time": "2018-06-26T22:08:14.805137",
"uuid": "40f440e4-798d-11e8-b246-005056ba2773",
"outputs": {},
"history_id": "d3c4be670ec43e54",
"state": "scheduled",
"output_collections": {},
"workflow_id": "d3dbe08fff89ad80",
"steps": [
{
"workflow_step_uuid": "dc5195e6-bf5e-4d1e-8868-21efae3ddc9c",
"update_time": "2018-06-26T22:08:04.237403",
"job_id": "bbd44e69cb8906b5be42d1c7436ce6f8",
"order_index": 1,
"workflow_step_label": null,
"state": "scheduled",
"action": null,
"model_class": "WorkflowInvocationStep",
"workflow_step_id": "cdbf0f81c30fa69b",
"id": "abe4c6cd9fc447a3"
},
{
"workflow_step_uuid": "671bca4e-0b76-4a6f-a0a2-70219df56576",
"update_time": "2018-06-26T22:08:03.645905",
"job_id": null,
"order_index": 0,
"workflow_step_label": null,
"state": "scheduled",
"action": null,
"model_class": "WorkflowInvocationStep",
"workflow_step_id": "31429656ff9189ef",
"id": "e3e4e7623a49e9eb"
}
],
"model_class": "WorkflowInvocation",
"id": "a72290f9d6aff2f1"
}
```

I can confirm that the job completed successfully by calling the history API: `https://usegalaxy.org/api/histories/d3c4be670ec43e54/contents`, which returns:

```
[
{
"history_content_type": "dataset",
"update_time": "2018-06-26T22:08:03.963589",
"name": "1.txt",
"extension": "txt",
"type_id": "dataset-bbd44e69cb8906b50f65049f5ce2262d",
"deleted": false,
"history_id": "d3c4be670ec43e54",
"tags": [],
"id": "bbd44e69cb8906b50f65049f5ce2262d",
"visible": true,
"state": "ok",
"create_time": "2018-06-26T21:44:14.611607",
"hid": 1,
"url": "/api/histories/d3c4be670ec43e54/contents/bbd44e69cb8906b50f65049f5ce2262d",
"dataset_id": "bbd44e69cb8906b5bd7e79e66ada58a6",
"type": "file",
"purged": false
},
{
"history_content_type": "dataset",
"update_time": "2018-06-26T21:50:25.681720",
"name": "1.txt",
"extension": "txt",
"type_id": "dataset-bbd44e69cb8906b593c9762cfb5cb14d",
"deleted": false,
"history_id": "d3c4be670ec43e54",
"tags": [],
"id": "bbd44e69cb8906b593c9762cfb5cb14d",
"visible": true,
"state": "ok",
"create_time": "2018-06-26T21:50:12.472257",
"hid": 2,
"url": "/api/histories/d3c4be670ec43e54/contents/bbd44e69cb8906b593c9762cfb5cb14d",
"dataset_id": "bbd44e69cb8906b51c9da9b61540d12b",
"type": "file",
"purged": false
},
{
"history_content_type": "dataset",
"update_time": "2018-06-26T22:08:14.525790",
"name": "Convert on data 1",
"extension": "tabular",
"type_id": "dataset-bbd44e69cb8906b59d5be46289751df8",
"deleted": false,
"history_id": "d3c4be670ec43e54",
"tags": [],
"id": "bbd44e69cb8906b59d5be46289751df8",
"visible": true,
"state": "ok",
"create_time": "2018-06-26T22:08:03.632310",
"hid": 3,
"url": "/api/histories/d3c4be670ec43e54/contents/bbd44e69cb8906b59d5be46289751df8",
"dataset_id": "bbd44e69cb8906b550c58ca1394c47e4",
"type": "file",
"purged": false
}
]
```

The content 'state' are all 'ok'.

**Comment by jmchilton** [comment]
So this was intentional - it was done as part of https://github.com/galaxyproject/galaxy/pull/4584/files (which was later rebased into https://github.com/galaxyproject/galaxy/pull/5013). Workflow steps didn't have state previously but they do now, they can be partially scheduled, ready to be scheduled, scheduled, etc... - this is because now there is one invocation step object for many potential jobs. Previously collection mapping steps may have resulted in many workflow step invocations for the same step of a single workflow invocation - making defining workflow step outputs impossible. The API makes more sense now, but I'll admit I didn't know anyone was using this endpoint this way though and I've gotten several questions about this now.

There are a couple of work arounds - you can use that job_id and fetch ``/api/jobs/<job_id>`` to get the final job state. This will be equivalent in the simple, single job per step case to the old behavior. It however makes no sense in light of collection mapping and such. The solution in that case is probably to fetch a more full description of the invocation step - `api/workflows/<workflow_id>/invocations/<invocation_id>/steps/<invocation_step_id>` and look at the states of the outputs and their jobs. Those outputs will only be defined properly if the workflow invocation step state is `scheduled`.

We should probably add a `api/workflows/<workflow_id>/invocations/<invocation_id>/jobs_summary` API endpoint or something that would provide a more optimized, more concise summary of workflow job states. Ultimately are just wanting to know the state of all the jobs in the workflow - or do you really want the per-step information?

**Comment by MingChen0919** [comment]
Thank you John! 

We are working on a module (tripal galaxy module) that enables running workflows from a tripal database(https://github.com/tripal/tripal_galaxy). We need to know the per-step information so that we can determine how we want to render each steps back to the tripal database users.

**`job_id` is NULL**

The `/api/jobs/<job_id>` does return detailed information. However, when I run `api/workflows/<workflow_id>/invocations/<invocation_id>/steps/<invocation_step_id>`, the `job_id` from each step is `NULL`. How can I get the `job_id`

**job state is not informative**

In galaxy 17.09, when a job is finished, it has state value `ok`. However, in galaxy 18.05, the job state is still `scheduled` even after the job is successfully finished. This state is not very informative.  How can we differentiate finished jobs from those that are still running?

**Comment by jmchilton** [comment]
I'm making a little progress on this with https://github.com/galaxyproject/galaxy/pull/6559. I think the steps corresponding to normal tool executions do have job_id's. Maybe you need to wait for the invocation to become of state 'scheduled'? There is a problem if the workflow uses map/reduce stuff though - in that case there isn't a single job_id and this won't be populated via the API. I've added a reference to the implicit_collection_jobs_id to the API response in that PR that can be used to recover this information but I need to fill out information and a test case describing how to use it.

I also have this commit:

https://github.com/jmchilton/galaxy/commit/9b4e7bbff1cc9c9f8e25024c975198a4c4e3d8d1

Which actually provides a bit more of a unified interface to the jobs associated with a step - more in the spirit of what was there before 18.01. I'm not sure if it would be appropriate to add it retroactively to 18.01 though. I'm also contemplating restoring the legacy API as a new "view" - it was just so broken though.

I'll keep you updated on progress.

> job state is not informative

Again the ``state`` on the invocation step object is not the job state, it is the state of the step's evaluation now. The job API will give you the same states as before - the states for the jobs.

**Comment by MingChen0919** [comment]
Thank you for your explanation and for working on this, John! Now I think I get it. I did some tests with two workflows: one use a regular input dataset, the other uses a input dataset collection. For the first one, I did get job ids for each job, but for the second workflow, all steps don't have job ids.

**Comment by jmchilton** [comment]
That PR now adds a ``legacy_job_state`` query parameter that should allow you to simulate the old concept the job state - I don't recommend using it but for backward compatibility it should be there.

**Comment by MingChen0919** [comment]
Thanks a lot, John! I'll let you know how it goes.

**Comment by mvdbeek** [comment]
We've merged https://github.com/galaxyproject/galaxy/pull/6559, feel free to re-open if this doesn't work for you.
