### ISSUE TITLE
ObjectNotFound when extra_files_path doesn't exist (with data manager)

### ISSUE THREAD

**Issue by abretaud** [galaxyproject/galaxy#6585]
Hi,
I'm playing with [data_manager_manual](https://github.com/galaxyproject/tools-iuc/tree/master/data_managers/data_manager_manual), and I get this error on one of my two Galaxy instances (the only one using objectstore):

```
Traceback (most recent call last):
  File "lib/galaxy/jobs/runners/__init__.py", line 690, in finish_job
    self._finish_or_resubmit_job(job_state, stdout, stderr, exit_code)
  File "lib/galaxy/jobs/runners/__init__.py", line 433, in _finish_or_resubmit_job
    job_state.job_wrapper.finish(stdout, stderr, exit_code, check_output_detected_state=check_output_detected_state)
  File "lib/galaxy/jobs/__init__.py", line 1415, in finish
    self.tool.exec_after_process(self.queue.app, inp_data, out_data, param_dict, job=job)
  File "lib/galaxy/tools/__init__.py", line 2293, in exec_after_process
    data_manager.process_result(out_data)
  File "lib/galaxy/tools/data_manager/manager.py", line 329, in process_result
    if os.path.exists(ref_file.extra_files_path):
  File "lib/galaxy/model/__init__.py", line 2128, in extra_files_path
    return self.dataset.extra_files_path
  File "lib/galaxy/model/__init__.py", line 1931, in get_extra_files_path
    return self.object_store.get_filename(self, dir_only=True, extra_dir=self._extra_files_path or "dataset_%d_files" % self.id)
  File "lib/galaxy/objectstore/__init__.py", line 506, in get_filename
    return self._call_method('get_filename', obj, ObjectNotFound, True, **kwargs)
  File "lib/galaxy/objectstore/__init__.py", line 527, in _call_method
    % (method, str(obj), str(kwargs)))
ObjectNotFound: objectstore, _call_method failed: get_filename on , kwargs: {'dir_only': True, 'extra_dir': 'dataset_89476_files'}
```

It seems like a ObjectNotFound is thrown when `lib/galaxy/tools/data_manager/manager.py` is just getting the directory path with `ref_file.extra_files_path`
The directory doesn't exist, but it shouldn't be a problem as there is a `os.path.exists` check after getting the path.

**Comment by bgruening** [comment]
See here: https://github.com/galaxyproject/galaxy/issues/1765

**Comment by abretaud** [comment]
Thanks @bgruening,
Not sure it's exactly the same problem, in #1765 you get an exception while trying to get the path of a dataset file that is supposed to exist. Here the extra_files_path doesn't exist, but this can happen in the normal life of a galaxy server (right?).

Looking at the code, I wonder if the function at https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/objectstore/__init__.py#L504 could look something like (not tested at all):

```python
    def get_filename(self, obj, **kwargs):
        """For the first backend that has this `obj`, get its filename."""
        if 'extra_dir' in kwargs and kwargs['extra_dir']:
            # Getting an extra_dir, no exception if it does not exist, just return None
            return self._call_method('get_filename', obj, None, False, **kwargs)
        else:
            return self._call_method('get_filename', obj, ObjectNotFound, True, **kwargs)
```

Or maybe catching the ObjectNotFound exception in https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tools/data_manager/manager.py#L329

Or maybe something else more clever :)

**Comment by mvdbeek** [comment]
Yeah, as you diagnosed the problem is with the `NestedObjectStore`, which behaves different from the simple and most-used (I'd guess ...) `DiskObjectStore`. The `DiskObjectStore`'s `get_filename` method just returns the path, whether it exists or not, and I think that's the assumption in https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tools/data_manager/manager.py#L329 and https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/model/__init__.py#L2183.

This is simple, because even if the path doesn't exist, the object store can predict where it would be created. The NestedObjectStore can't do that, and other more complex object stores might not be able to do that either. I think a good way to avoid subtle bugs when deploying galaxy is to introduce the same limitation in the DiskObjectStore, and then to provide a property in the Dataset object itself to check if the `extra_files_path` exists. That'd also save one `stat` call when doing `os.path.exists(dataset.extra_file_path)` -- plus technically `extra_files_path` it isn't even guaranteed to be available by `os.path.exists`.
