### ISSUE TITLE
MEME suite

### ISSUE THREAD

**Issue by mictadlo** [galaxyproject/galaxy#664]
Hello,
It seems there is [MEME wrapper](https://github.com/galaxyproject/galaxy/blob/dev/tools/meme/meme.xml), but I am not able to figure out how to activate it, because currently it does not show up in the toolbox.

Thank  you in advance.

Mic

**Comment by jmchilton** [comment]
If you copy `config/tool_conf.xml.sample` to `config/tool_conf.xml` and add an entry for `meme/meme.xml` it will show up in the tool panel. Since this tool is not coming from the tool shed you will need to ensure the dependencies (the `meme` executable) are on the `PATH`.

More information about tool panel configuration files at https://wiki.galaxyproject.org/Admin/Tools/AddToolTutorial.

Hope this helps, feel free to reopen if you have additional problems.
