### ISSUE TITLE
List of style update issues

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#6706]
Follow-ups for #6422.

from @jxtx:

- System fonts
- Eliminate "lavender"
- Improve default colors
- Fewer borders
- More flex (resizeable) components
- Better / more consistent use of whitespace (far from complete)

from @mvdbeek:

Alright, so these things I have found:

- [x] in multi-select mode the checkboxes are slightly cut off:
![screen shot 2018-09-11 at 10 23 15](https://user-images.githubusercontent.com/6804901/45347591-c6da5580-b5ac-11e8-9b3b-e931df20eef2.png)

- [x] The done button for history and HDA annotations is too big:
![screen shot 2018-09-11 at 10 24 28](https://user-images.githubusercontent.com/6804901/45347649-ecfff580-b5ac-11e8-9cfe-dfa7da7af332.png)

- [x] The placement of the integer box here seems off (and the tool header space could be used better)
![screen shot 2018-09-11 at 10 26 21](https://user-images.githubusercontent.com/6804901/45347824-4536f780-b5ad-11e8-836b-d81195c165b6.png)

- [x] Tool form preview in the workflow editor still uses the old style
![screen shot 2018-09-11 at 10 31 27](https://user-images.githubusercontent.com/6804901/45348074-f047b100-b5ad-11e8-9f16-a9100fa919f6.png)

- [x] View workflow also still uses the old style
![screen shot 2018-09-11 at 10 38 25](https://user-images.githubusercontent.com/6804901/45348418-dfe40600-b5ae-11e8-9d36-f2896ac9432c.png)

- [x] Share workflow uses old style:
![screen shot 2018-09-11 at 10 39 22](https://user-images.githubusercontent.com/6804901/45348464-03a74c00-b5af-11e8-906c-10a6412edfbc.png)

- [x] Visualizations partly use old style
![screen shot 2018-09-11 at 10 40 16](https://user-images.githubusercontent.com/6804901/45348495-22a5de00-b5af-11e8-8e99-ce90e840d52f.png)

- [x] Importing workflow uses old style:
![screen shot 2018-09-11 at 10 41 52](https://user-images.githubusercontent.com/6804901/45348571-57b23080-b5af-11e8-9e34-5a3156d47fa9.png)

Various forms in the admin interface use the old style

-  [x] Data tables
![screen shot 2018-09-11 at 10 42 31](https://user-images.githubusercontent.com/6804901/45348614-744e6880-b5af-11e8-8931-3c8bfd24ad7f.png)
- [x] Job interface
![screen shot 2018-09-11 at 10 43 08](https://user-images.githubusercontent.com/6804901/45348722-b4155000-b5af-11e8-91ac-be7e28832308.png)
- [x] Tool shed selection 
![screen shot 2018-09-11 at 10 43 28](https://user-images.githubusercontent.com/6804901/45348726-b677aa00-b5af-11e8-9a67-93510903418f.png)
- [x] Resetting metadata
![screen shot 2018-09-11 at 10 43 33](https://user-images.githubusercontent.com/6804901/45348736-ba0b3100-b5af-11e8-88d8-d803494f61db.png)

- [x] The Execute button mixes with the help text
![screen shot 2018-09-25 at 15 30 28](https://user-images.githubusercontent.com/6804901/46017620-3afe1880-c0d8-11e8-86da-77d36a723cc2.png)

**Comment by martenson** [comment]
edit: **solved** with https://github.com/galaxyproject/galaxy/pull/6870

centered form field

![galaxy](https://user-images.githubusercontent.com/1814954/46311903-8eb5a980-c591-11e8-9468-25c0b58a274d.png)


edit: I see this had been reported and 'checked off', but I still see it on latest dev

**Comment by hexylena** [comment]
This is less of an "issue" and more of an opinion: I love all of the changes to make things cleaner, but in the toolbox, masthead, history I have the feeling that there is just too much wasted space. EU's toolpanel will seem even more overcrowded and unreadable than it does already due to the larger font and extra padding. The masthead I can probably get used to. Maybe this is just me being new to the redesign, but, my 2¢.

**Comment by martenson** [comment]
@erasche I think padding is something we still want to change a lot. Vertical alignments are often off, and some space does seem wasted, as you pointed out. We could consider including a 'compact' style switch.

**Comment by hexylena** [comment]
@martenson hey that's great to hear! I'd love a compact style switch (or a style switch between different 'themes'.) It's a totally silly request but users love that sort of thing.

**Comment by jxtx** [comment]
Thank you for the feedback!

I've been asking people for a few years, and especially at this last GCC, when they tell me Galaxy looks "out of date" / "old", what would make it more modern?

The only consistent answer has been bigger fonts and more whitespace.

But maybe we aren't putting it in the right places...

Helena Rasche <notifications@github.com> writes:

> This is less of an "issue" and more of an opinion: I love all of the changes to make things cleaner, but in the toolbox, masthead, history I have the feeling that there is just too much wasted space. EU's toolpanel will seem even more overcrowded and unreadable than it does already due to the larger font and extra padding. The masthead I can probably get used to. Maybe this is just me being new to the redesign, but, my 2¢.
>
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/galaxyproject/galaxy/issues/6706#issuecomment-426947009

-- 
James Taylor
Ralph S. O'Connor Professor of Biology and Computer Science
Johns Hopkins University

**Comment by hexylena** [comment]
It definitely makes it more modern! Especially in context of the trends from all of the google interfaces. I can see where that feedback comes from. And if this was a product like mail / calendar / some other google product, I'd say yeah it makes sense. And whitespace in header, yeah, this makes sense. Those click targets are way easier to hit and for often used actions, definitely.

For the toolbox specifically, in this case, I have the impression that our audience is more technical and better equipped to deal with more information density, if it helps them do their job a bit more easily/efficiently.

My impressions of the latest trends in UI designs from large (albeit non-technical projects) is that they're all removing as much information from the screen as possible, decreasing the possible actions that can be executed. I don't have the feeling that this is something galaxy is desiring? But I guess there is some balance to be had between making the UI less confusing for new users and retaining the UI abilities for (non-api-using) power users. 

Thanks for being open to feedback!

**Comment by jxtx** [comment]
Sounds good. There's a lot more we'd like to do with the toolbox anyway. And I really haven't done anything with the styling of the history items, which need to be balanced with the toolbox.

I agree we don't want to reduce the possible actions. Galaxy is complicated. "There is no such thing (yet) as an automated gearshift in short read mapping. It is all like stick-shift driving in San Francisco."

It would be interesting to identify other web applications that do this well and see if there is anything we can ~steal~ use as inspiration.

**Comment by guerler** [comment]
Yeah there is definitely still work to be done. Thanks for all the feedback. After fixing some of the obvious glitches mentioned above, I plan to resolve the history panel styling.

**Comment by hexylena** [comment]
Hmm. I'd started a comment but looks like it's gone because I got too distracted.

The short version is the only things that come to my mind that reach similar levels of complexity is the AWS management console. And I don't think anyone will point this out as a paragon of UX design.

I struggle to think of any other service that needs to deal with what is essentially live construction of a workflow, with different 'threads' of data that you're working on, and doing any of some 2k different operations with that data at any time. AWS certainly doesn't handle this, they say "here's the API".

But that takes the discussion more in terms of new UIs/UI overhauls, and that's not quite the limited scope of things we can tweak within the CSS to make it more usable.

**Edit**

Oh, it was just in another browser session:

[google's api explorer](https://developers.google.com/apis-explorer/?hl=en_US#p/oauth2/v2/oauth2.tokeninfo) which let's you execute functions, see results, and see history of execution? But the interface is very clunky and definitely not in the same vein

**Comment by martenson** [comment]
I checked off the ' The Execute button mixes with the help text' since all of the bedtools seem to render fine on dev for me. @mvdbeek did you report this? any special state?

**Comment by mvdbeek** [comment]
Yes, bedtools shuffle, other than serving via planemo no. So I guess it's resolved.

**Comment by hexylena** [comment]
I just wanted to say it's growing on me :)

Thoughts on removing whitespace around the header?

![grafik](https://user-images.githubusercontent.com/458683/47204991-4c071600-d374-11e8-87f1-a4789a2eb582.png)

vs

![grafik](https://user-images.githubusercontent.com/458683/47205051-6a6d1180-d374-11e8-8aa8-e52dfcf53b8e.png)

**Comment by hexylena** [comment]
![grafik](https://user-images.githubusercontent.com/458683/48702077-dc40b100-ebe7-11e8-97f6-5ffa3a5e2f81.png)

The [options for a text param](https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-inputs-param) is improperly styled / unreadable

**Comment by scholtalbers** [comment]
At least for the `.donemessagelarge` the text `color` should be black (or similar) for readability, looks fuzzy otherwise (on dev):

![screenshot 2018-11-27 at 10 29 33](https://user-images.githubusercontent.com/102411/49071942-6237aa00-f22f-11e8-8859-239fb17894da.png)

![screenshot 2018-11-27 at 10 28 33](https://user-images.githubusercontent.com/102411/49071938-5fd55000-f22f-11e8-8401-21c8910ce059.png)

Similar the contrast on the errrored history datasets is somewhat low:
![screenshot 2018-11-27 at 10 32 05](https://user-images.githubusercontent.com/102411/49072079-b8a4e880-f22f-11e8-9e4f-8736e264e6fb.png)

**Comment by mvdbeek** [comment]
I think this is done, if there is stuff that isn't we're probably not going to target 19.01. So I'm closing this, feel free to open a new issue with missing things.
Thanks a lot to everyone that worked on updating the style and testing them!
