### ISSUE TITLE
Center panel is blank when launching a tour from URL

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#6708]
Launched via url (https://usegalaxy.eu/tours/core.history):

![grafik](https://user-images.githubusercontent.com/458683/45474878-20708a80-b73b-11e8-9bf1-3117be4342d9.png)

Where normally it would show the tour page you were currently on. This seems unexpected but maybe it is intentional?

**Comment by mvdbeek** [comment]
might be a crash -- anything in the JS console ?

**Comment by hexylena** [comment]
Nope, nothing. (You can test with the link provided in the issue. Seen in chrome/FF for me.)

**Comment by dannon** [comment]
It's intentional.  If a tour needs a particular start location, it can be specified in the tour params.  Otherwise we start with a blank (no `Galaxy.display()` call) Galaxy analysis interface.

That said, if folks think it's distracting, we could swap to the welcome or potentially a "Your tour is starting now" page.

**Comment by hexylena** [comment]
Not so much distracting as worried they'll be overwhelmed by all the "noise" going on in the center panel when they're finally shown it. But if it's intentional, this answer it for me. Thanks!
