### ISSUE TITLE
Tags on workflows are not consistently saved

### ISSUE THREAD

**Issue by scholtalbers** [galaxyproject/galaxy#6888]
tested on usegalaxy

Tagging workflows is kinda broken, sometimes the tags that one sets in the workflow list page do show up in the editor, sometimes they don't, and vice versa.
This may be related to the workflow versioning, but in the current state its quite annoying to try to properly tag workflows..

**Comment by mvdbeek** [comment]
I can't reproduce this on usegalaxy.org, are you sure this isn't #6713 ? Alternatively, do you have a procedure that doesn't work that I can follow ?

**Comment by mvdbeek** [comment]
Maybe there's something special about the tags you're using?

**Comment by hexylena** [comment]
Also which usegalaxy? It is a usegalaxy.eu problem?

**Comment by scholtalbers** [comment]
I'm on usegalaxy.org and using firefox. 

Attached are two screenshots which I actually generated to show the duplicated workflow entries in the menu and then saw that:

<img width="908" alt="screen shot 2018-10-17 at 15 23 27" src="https://user-images.githubusercontent.com/102411/47089395-0f76d580-d221-11e8-82b4-2a1b8f7183d6.png">

**after** editing(removing a step) and saving the workflow, my tags were gone again!

<img width="774" alt="screen shot 2018-10-17 at 15 24 41" src="https://user-images.githubusercontent.com/102411/47089402-143b8980-d221-11e8-9a0c-3c93ac07f400.png">

**Comment by eschen42** [comment]
This affects me on both UseGalaxy.eu and UseGalaxy.org

When I use my browser to edit a tagged workflow and save my work, my tag disappears. The tag does appear in the workflow attributes in the editor, but after saving the workflow, no tag (at least not usually). I'm running chromium-browser Version 71.0.3578.80, for what it's worth.

**Comment by mvdbeek** [comment]
Ah, you're editing the tags in the attributes page, that is probably the issue. I was just setting them on the overview page, which might explain why I didn't have an issue before.

**Comment by cgirardot** [comment]
@mvdbeek this bug is still out there (just tried on .eu and our local 19.05 install). You don t even need to edit the tags in the workflow editor. You can easily reproduce as Jelle said (on .eu): 
1. on the WF list page, add a tag to a WF 
2. Open the WF editor with this WF and simply remove one step, save
3. Back to the WF list, the tags are gone 

This bug is really annoying. As we discussed at the GCC, we'd love to have folder-like structure to organise our WFs (like for libraries). At the moment, the only we can organize our WFs per projects is using these tags but we are loosing them at each edit... Any chance to move the priority for this issue ?

**Comment by mvdbeek** [comment]
Oops, that fell through the cracks. I'll have a fix in a minute.

**Comment by cgirardot** [comment]
awesome, thx
