### ISSUE TITLE
new collection operation: change datatype & dbkey

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#6965]
proposed by @mvdbeek 

If you click edit on a normal dataset (instead of a collection) you have a bunch of important options:

<img width="1343" alt="Screen Shot 2021-01-14 at 3 00 06 PM" src="https://user-images.githubusercontent.com/216771/104642824-6a563c00-5679-11eb-920f-2fd352bb4f56.png">

It should be possible to batch apply similar operations to all the elements of a collection. The two key ones that I've heard identified over and over are modifying the "Database/Build" option on the first tab of the edit dataset screen and the "Convert" options in tab 2 and 3. The option in tab 2 would build a new collection with the conversion tool applied to each element of the collection and the other would change the datatype of each element of the collection.

**Comment by assuntad23** [comment]
@jmchilton @mvdbeek 
Just to confirm:

The collection should allow you to edit:
1. the Database/Build 
    a. changes all datasets in the collection to the selected value)
2. the datatype 
    a. there are two ways to do this with a dataset 
        i. one is in the Convert tab and that creates a new dataset by running the convert tool
        ii. the other is in the Datatypes tab and that just changes the datatype
    b. Is it necessary to include both ways to change the datatype or is one preferable over the other to simplify things?

**Comment by mvdbeek** [comment]
Yes to all of these, but I think when hit the "edit" button a new collection should be built. The old collection should be immutable and stay around (maybe hidden?).
We can stick the new collection to the top of the history or we hide/replace the old collection (like the implicit datatype conversion does currently). I think I'd prefer putting it to the top of the history, but I am a weird power-user, and maybe users expect "edit" to do things in place, in which case we can add the new collection at the same position in the history.

I think both ways of changing datatypes should be possible. If you know the tool id of the converter you can actually run it on a collection today, so maybe you could start with that, since the backend is already there ?

**Comment by assuntad23** [comment]
per a conversation with @jmchilton : as a first pass WIP PR, the convert tab does not need to filter based on data type of the elements. The logic for that is tied somewhere to the conversion tool and on the back end. A second pass may move some logic to the front end so it's easier to access.

**Comment by mvdbeek** [comment]
I ... don't think that's an improvement ? The conversion has to be limited to compatible datatypes. That is different from changing the datatype which just overrides everything, but maybe I'm misunderstanding the summary here.

**Comment by mvdbeek** [comment]
An alternative idea for a first step would be writing an expression tool that takes a single input dataset, copies just the HDA, and sets a new datatype on the output HDA. 

https://github.com/jmchilton/galaxy/blob/9e8530c074e9c0578aea4740ef2ccae16bbe7af2/test/functional/tools/expression_pick_larger_file.xml is an example of how you can copy an input HDA to an output HDA.
If it works on single dataset it is also going to work on collections of all structures. What do you think about that @assuntad23 @jmchilton ?

This came up as a request on gitter again, and this tool wouldn't even necessarily have to be in core Galaxy, we can distribute that in the toolshed as a first pass.

**Comment by assuntad23** [comment]
@mvdbeek with regards to your first comment ^^ : it is not the intention that the PR would be mergeable in that state; just that @jmchilton and I discussed that as a benchmark so I can get it in front of people and get some help/feedback, before continuing to work on it.

**Comment by jmchilton** [comment]
@mvdbeek 

Slowly catching up. I see that forcing the extension change is different than the converters because it can be any type and we don't want to use converter tools. So I see a lot of utility in doing this in an expression tool - it will do the collection mapping and distribute the work, etc...

Assunta and I walked through what a tool like that might look like. I think we came up with:

```
<tool name="__FORCE_TO_DATATYPE__" id="__FORCE_TO_DATATYPE__"
      version="0.1.0" tool_type="expression">
    <expression type="ecma5.1"><![CDATA[
        {
            var input1 = $job.input1;
            return {'output': input1.src};
        }
    ]]></expression>
    <inputs>
        <param type="data" label="Source dataset." name="input1" />
        <param type="text" label="Target data type." name="target_type" />
    </inputs>
    <outputs>
        <output type="data" name="target_dataset" from="output" format_from="target_type" />
    </outputs>
    <help>
    </help>
    <tests>
        <test>
            <param name="input1" value="1.fasta" ftype="txt" />
            <param name="target_type" value="fasta" />
            <output name="target_dataset" file="1.fasta" ftype="fasta" />
        </test>
    </tests>
</tool>
```

This should all work except for passing that text argument describing the target datatype into the expected output type field. My proposed solution above is a new syntax on the output to map it to an input ``format_from="target_type"`` . Does that make sense to you? There isn't an existing way to do this with expression tools right? I guess we can't copy a config file to galaxy.json from inside the expression block. So this is one approach or as I type this out I realize we could alternatively come up with a way to write to galaxy.json directly from the configfile block.

Any advice, how does this approach sound?

**Comment by mvdbeek** [comment]
Yeah, I think that looks good, that is close to what I had in mind (except I didn't think about how to get the target_type ...)
