### ISSUE TITLE
data collections do not work with single repeats

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#697]
The following snippet (from the cut1 tools) is working.

```
<param name="input1" type="data" label="Concatenate Dataset"/>                                                                                                                               
<repeat name="queries" title="Dataset">
    <param name="input2" type="data" label="Select" />
</repeat>
```

The following does not work and from a usability point of view there is no difference. 

```
<repeat name="queries" min="1" title="Dataset">
    <param name="input2" type="data" label="Select" />
</repeat>
```

**Comment by jmchilton** [comment]
This was discussed very early on in terms of dataset collection design goals - but I argued it was wasted effort since so many tools are organized in various ways such as separating out a single or two data and then using a repeat for the rest. I think the effort would be better put into making the multi input data parameters robust enough to replace single data repeats in all cases: https://trello.com/c/lp5YmA1O.

Can I call this a wontfix in lieu of https://trello.com/c/lp5YmA1O.

**Comment by bgruening** [comment]
The enhancements are the right way to do it. We just need to ensure to solve the following use case.

Given N data collections (repeat element) all inputs should be reduced to one file.

**Comment by hexylena** [comment]
I think the community has mostly switched to using `multiple="True"` here, so we can maybe close this?

**Comment by jmchilton** [comment]
I have no intention of "fixing" this - I like the multiple data approach better. I'm going to close but I'll ping @mvdbeek to get a second opinion since if it is not me doing this work, it would be him. If he doesn't re-open the issue I think we should just call it closed because no one is going to be motivated to do the work.
