### ISSUE TITLE
composite data upload via URL is broken

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#7046]
Go to compostie data upload, choose imzml and insert those two files:

```
https://zenodo.org/record/1560646/files/mouse_kidney_cut.imzML
https://zenodo.org/record/1560646/files/mouse_kidney_cut.ibd
```

I get the following error both on 18.05 and 18.09.
```
{…}​data: FormData {  }​error: function error()​error_default: "Please make sure the file is available."​error_login: "Uploads require you to log in."​error_retry: "Waiting for server to resume..."​error_server: "Upload request failed."​progress: function progress()​success: function success()​url: "/api/tools"​<prototype>: Object { … } analysis.bundled.js:1:500124
```

**Comment by mvdbeek** [comment]
Interesting, on usegalaxy.org we also get this:
![screen shot 2018-11-27 at 08 35 59](https://user-images.githubusercontent.com/6804901/49065897-b175de80-f21f-11e8-991c-81943263f18d.png)
The upload is going to `_upload`, which I think happens if you set `nginx_upload_store` in the galaxy.yml file and you don't actually have that route in the nginx config (because upload is supposed to be handled by the chunked uploader).

**Comment by mvdbeek** [comment]
This is working fine on 19.01, it looks like at the time something about the upload route was misconfigured.
![screen shot 2019-01-21 at 09 52 41](https://user-images.githubusercontent.com/6804901/51463030-76e17b80-1d62-11e9-8bbd-6613d021c382.png)
