### ISSUE TITLE
login/registration form js console errors

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#7393]
after attempting to log in, create account, or reset password with an invalid form (no email address) I receive an error message but also the following javascript console errors:

`xhr.js:178 POST http://127.0.0.1:8080/user/reset_password 400 (Bad Request)`
`xhr.js:178 POST http://127.0.0.1:8080/user/login 400 (Bad Request)`
`xhr.js:178 POST http://127.0.0.1:8080/user/create 400 (Bad Request)`

I think those should not be 'Bad Request's, ideally they wouldn't be thrown at all. In super-ideal world the requests would never actually be fired since empty field cannot be valid here.

**Comment by dannon** [comment]
I'll take a look, thanks!

**Comment by dannon** [comment]
Ok, I just took a quick look and those response codes an the messages are probably appropriate, but we could definitely add more client side validation at which point we'd prevent submission pending a valid form.  There's not a 'bug' here, but this would be an easy enhancement for someone to add.

**Comment by martenson** [comment]
fwiw My point is that a webapp should not log client side errors when user makes a typo in their username/password or some other completely expected situation. This is not an error for the app. I am having a hard time finding other software that behaves similarly.

**Comment by dannon** [comment]
Scratch all that, I just tried Chrome and I think I see what you're seeing now.  Let me see why this is surfacing in Chrome but not Firefox.  In any event, this isn't something we're intentionally surfacing as an error.

**Comment by martenson** [comment]
![galaxy](https://user-images.githubusercontent.com/1814954/53122313-4be67500-3524-11e9-9ffe-d78b91d7855e.png)

**Comment by dannon** [comment]
@martenson That view is the network log which is going to show these 400s no matter what we do.  

I do see this, though, in the console tab of Chrome:  
![image](https://user-images.githubusercontent.com/155398/53122458-a8499480-3524-11e9-80d2-f26a345534d3.png)

I'm wondering if this isn't just a Chrome thing, since I don't see the same in Firefox, but I'll dig into it.

**Comment by martenson** [comment]
I see them in both places. My point is that we shouldn't be returning 'bad request' to good requests. The fact the password is wrong, does not make the request bad.

**Comment by dannon** [comment]
I dunno, we could take a poll, but I think bad request is pretty appropriate.  https://tools.ietf.org/html/rfc7231#section-6.5.1 has more details, but it seems to fit.

Could be argued that they should be 401s, but it's going to be a 400 (and thus showing up like this) any way you frame it I think.

Edit: In any event, I think I have a fix that'll prevent the error showing up in Chrome like this in the console -- testing it now.

**Comment by dannon** [comment]
@martenson So what I tried (`validateHandler` in axios) didn't work, which I kinda thought might happen since this is actually a chrome bug ('feature'?):  https://bugs.chromium.org/p/chromium/issues/detail?id=124534

You can disentangle those network logs from your console here if you want ('hide network' -- they'll still all show up in the Network tab like other browsers):  
![image](https://user-images.githubusercontent.com/155398/53169402-1c2e8000-35ab-11e9-91df-210ed87a7719.png)

Easy next step would be just adding some simple client side validation which would prevent this, but I also don't think it's unreasonable that an error indicating a bad and/or unauthorized request shows up for chrome users in the console if they try to submit a blank form.

**Comment by martenson** [comment]
Thanks for finding that thread, this is really silly behavior from Chrome. It seems they do this for a subset of 4xx responses and there is nothing we can do.

**Comment by dannon** [comment]
We may want to follow up on general client side validation of login stuff, but we're going to just go ahead and close this out for now since the log is actually Chrome weirdness and not a Galaxy bug.
