### ISSUE TITLE
Failed collection elements should not be visible

### ISSUE THREAD

**Issue by pvanheus** [galaxyproject/galaxy#7492]
Hi there

Our group is working on a tool to identify contamination in our sequencing inputs. When contamination is detected it fails the job. When this is used together with a collection, the "Filter failed" collection operation allows for a final collection to be made only including the uncontaminated samples.

Immediately after the data is processed it looks mostly correct:

![image](https://user-images.githubusercontent.com/4154788/54035081-282c5b80-41c1-11e9-9f93-efe7611cbfcb.png)

I say "mostly" because the collection with failed elements here is part of a workflow output, something that would normally be hidden.

As soon as I refresh the windows, or in any way navigate away from the history and back again, the failed datasets "escape" the history and show up as datasets:

![image](https://user-images.githubusercontent.com/4154788/54035154-5e69db00-41c1-11e9-8f4e-1044a013f584.png)

I think the correct behaviour should be to not let the datasets "escape".

Secondly I think there should be an option to keep failed datasets hidden in workflow outputs. Thanks.

**Comment by mvdbeek** [comment]
I agree that we don't need to show the failed datasets if they're part of a collection, but I am not sure about the second part, I can see that becoming very confusing.
Another workaround that you can use is to write an empty file and filter using the filter empty file tool instead of erroring.
This way you can still discriminate legitimate tool errors from intended "failures".

**Comment by pvanheus** [comment]
Thanks @mvdbeek I'll implement that "empty file" method for now...
