### ISSUE TITLE
Tour : Element ID called a second time.

### ISSUE THREAD

**Issue by rdallet** [galaxyproject/galaxy#7582]
Hi,

I am currently working on a tour to launch a workflow demo but I have difficulties with some elements called more than one time that are not properly targeted.

Example : 
- I upload a single file and then a collection from "Paste/Fetch data". But when I target the button "Paste/Fetch data" for the collection upload (second time), the element is not recognized. So the button is not targeted and my post click action not happened.
- Same problem for data collection input button. For my first tool, it's OK, but not for my second tool.

Have you got any ideas on how to solve this ?

**Comment by dannon** [comment]
Can you share a minimal example that reproduces this?  I'd be happy to take a look.

**Comment by rdallet** [comment]
You can test the beginning of [my tour](https://github.com/workflow4metabolomics/galaxy-interactive-tours/blob/0c9f9b9a6499839371e9b10b76670cfa7d10b1d9/LCMS_preprocessing.yaml)

**Comment by rdallet** [comment]
Hello @dannon ,

Have you had time to take a look at my tour?

**Comment by dannon** [comment]
@RomainDallet I think what's happening here is that the element selector is matching the hidden "Paste/Fetch data" button on the first tab, not the intended visible one which is on the active tab.  This is a fault on the Galaxy side, since we shouldn't have multiple "#btn-new" elements (or any other uniquely id'd elements) on page at any given time, whether rendered or not.  We'll fix that.

In the meanwhile, you can scope your query a little more and force it to work, like this:  `$(".tab-pane.active #btn-new")`.

Sorry for the trouble, and the delay in being able to circle back to this one!

**Comment by rdallet** [comment]
Ok, thanks for your answer! I will test that.

**Comment by dannon** [comment]
This is resovled with the swap of our tour libraries.
