### ISSUE TITLE
Default values for workflow parameters

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#7775]
The new "simple inputs for workflow logic" parameters could be augmented to support adding default values, minimum and maximum values and some sort of validation. Default values are probably the most useful (and I think @jmchilton mentioned this may already be in the cwl branch ?)

**Comment by tshtatland** [comment]
Default values for workflow parameters would be great for many of our users. 
It is also consistent with Galaxy tools having parameters with default values, and UNIX command line tools having parameters with default values. 
We currently use workflow parameters: ${param name}, which are related to this. The workaround for these is to provide suggested defaults in the workflow docs/annotation/etc or even in the parameter name (ouch!). Of course, this is neither robust nor fast enough, since it requires user action.

**Comment by mvdbeek** [comment]
Got these since 20.01: https://github.com/galaxyproject/galaxy/pull/9086
