### ISSUE TITLE
revisit UX of tagging component

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#8148]
![image](https://user-images.githubusercontent.com/458683/59338839-69be2c80-8d03-11e9-8f6f-27590ff0b9fb.png)

It also looks different on adding initial tags after opening menu (+tag icon) vs a pseudo-text field you can't distinguish on subsequent tag adds. @martenson is that intentional?

![image](https://user-images.githubusercontent.com/458683/59338905-8490a100-8d03-11e9-8ddf-132468539c7d.png)

**Comment by hexylena** [comment]
@martenson Done

**Comment by Nerdinacan** [comment]
I'll take a second swing at this. I don't like the dependency injection scheme I implemented back when I thought it was the only way to solve the problem, but I can revisit the graphics as well. 

Part of the problem is there's really a whole bunch of tags editors and they're all implemented slightly differently even if they look similar on screen.

**Comment by martenson** [comment]
@Nerdinacan last time I checked I liked this: https://github.com/shentao/vue-multiselect

**Comment by davelopez** [comment]
The UI/UX around tagging has been improved in the latest versions so this is likely outdated. Please open new issues if there is still something to address or improve.
