### ISSUE TITLE
Again after Galaxy update: Jobs from return in random order in the history 

### ISSUE THREAD

**Issue by rgilsbach** [galaxyproject/galaxy#8402]
Starting workflows with multiple inputs in parallel the jobs return in random order in the history.
This makes parallel initiation of workflows useless..
This issue reapeared in usegalaxy.eu after the latest Galaxy update.
Best

Ralf

**Comment by mvdbeek** [comment]
I don't think there was ever a guarantee that workflow jobs would be scheduled in a given order. The canonical way to deal with running workflows for multiple input files is to place them in a collection and let Galaxy schedule a single workflow. Would that be a suitable workaround for you ?

**Comment by rgilsbach** [comment]
This not a suitable workaround. For daily life with bedfiles etc. not practicable. I use workflows with multiple inputs all the time. Collections have improved but are not working for everything and are too complicated for single tasks.
Starting workflows with multiple inputs should be usable, too...
If I understand it correctly, this issue appeared firs after parallelizing the job/workflow handler. Björn deactivated this feature in Galaxy.eu it was slower but ordered...

**Comment by rgilsbach** [comment]
This problem existed already in previous versions and was closed..
Issue #3474

**Comment by mvdbeek** [comment]
> For daily life with bedfiles etc. not practicable. I use workflows with multiple inputs all the time. Collections have improved but are not working for everything and are too complicated for single tasks.

Give it another try, there have been huge improvements over the last years. I always put everything in collections, even single datasets. I haven't seen anything that can't be done with collections in a couple of years now, and if you find something we can surely work on that.

All that said, if you really don't want to use collections you can also tag your input datasets and then filter them in the history view to see individual runs of the workflow.

> Starting workflows with multiple inputs should be usable, too...

The issue is that they are separate invocations of the workflow, there's nothing that intrinsically gives them an order. It's just dangerous to rely on the order with which they will be executed for the identification of samples, which would be solved by using either tags or collections.

There is of course something that we can do for the display of items in the history, which would be ordering items in the history panel by the workflow steps and invocations that produced them, that is something we'll be working on (that's also mentioned in https://github.com/galaxyproject/galaxy/issues/3474#issuecomment-274809880).

**Comment by rgilsbach** [comment]
Totally agree that there are many important improvements!!! 
Still my daily problem is not to get lost in my histories. Tags really help a lot - much better as compared to renaming inside workflows... 

Ordering the items in the history panel would be awesome - that was what I asked for - sorry if it was not precise enough.
(In which order the jobs are processed doesn`t matter - the faster the better)

**Comment by bgruening** [comment]
@mvdbeek this is a real problem to users today. Power users actually - users that do use collections. But there is still a need to do analysis without collections. Collections are not the answer to everything and we - for practical reasons - can not wait for the new history view - I do hope we will see something this year, it will be awesome I'm sure.

I guess what we missed or dropped in our configuration was `history_local_serial_workflow_scheduling: true`. We will put this back until we do have a new history view.

@rgilsbach can you please check in 15min if this is working for you again?
Sorry for any inconvenience.

**Comment by nsoranzo** [comment]
@bgruening @rgilsbach Can this be closed?

**Comment by rgilsbach** [comment]
It`s not fixed but we hope for the next Galaxy version. I guess closing makes sense.

 

Thanks

 

Ralf

 

Von: Nicola Soranzo <notifications@github.com> 
Gesendet: Monday, November 18, 2019 3:32 PM
An: galaxyproject/galaxy <galaxy@noreply.github.com>
Cc: rgilsbach <ralf.gilsbach@pharmakol.uni-freiburg.de>; Mention <mention@noreply.github.com>
Betreff: Re: [galaxyproject/galaxy] Again after Galaxy update: Jobs from return in random order in the history (#8402)

 

@bgruening <https://github.com/bgruening>  @rgilsbach <https://github.com/rgilsbach>  Can this be closed?
