### ISSUE TITLE
Failed job when using collections in a workflow makes the following output collection unusable

### ISSUE THREAD

**Issue by Delphine-L** [galaxyproject/galaxy#8540]
When I run a workflow on a collection, and one of the steps had failed jobs, the next output collections have paused job. 
These collections then cannot be used in collection manipulation tools such as filter failed jobs or flatten collections... It means I need to filter out the failed jobs at the point of failure and rerun all the following steps. 
Would it be possible to be able to filter out paused jobs too?

**Comment by mvdbeek** [comment]
If you re-run the failed job you also have the option to replace the original item (assuming a re-run would fix the problem) and continue from there. It's simple enough to implement this for the filter failed tool, I'll open a PR later.

**Comment by cgirardot** [comment]
@mvdbeek I am also in the case where 3 out 5 jobs failed in my collection. Input is a paired-end dataset collection and I can't see/find the option you are mentioning after clicking on `re-run`. 

Here is what I see

<img width="1725" alt="Screenshot 2019-09-11 at 16 44 03" src="https://user-images.githubusercontent.com/10990795/64707525-6ded1800-d4b3-11e9-8b7f-78742b2afb47.png">

if I hit `Execute`, I get : 

<img width="686" alt="Screenshot 2019-09-11 at 16 44 09" src="https://user-images.githubusercontent.com/10990795/64707575-7c3b3400-d4b3-11e9-8060-6a586b5e9c0d.png">

Any idea why ? Note this is on our local server, running 19.05

**Comment by mvdbeek** [comment]
Resume dependencies from this job has the same effect, it's just named differently when there are jobs paused that depend on this dataset. Make sure you don't change the input dataset selection, "cannot create multiple jobs when remapping existing jobs" means that you are mapping over the tool (which creates multiple jobs) instead of just running the same job hat failed.

**Comment by cgirardot** [comment]
I did not change anything in the form but the "Resume dependencies". Also I am pretty sure I saw the option you mentioned (replace the original item) in other context. 
By default, the input form looks like : 
<img width="1937" alt="Screenshot 2019-09-11 at 17 13 09" src="https://user-images.githubusercontent.com/10990795/64710014-89f2b880-d4b7-11e9-8712-5cee3262f136.png">

which looks wrong (the 469 collection is not the one used as input of this job), so I changed the collection to the right one but got the same error. 

Should I change the input type to select the datasets directly like this ? 
<img width="1932" alt="Screenshot 2019-09-11 at 17 17 10" src="https://user-images.githubusercontent.com/10990795/64710306-fff71f80-d4b7-11e9-9a73-94065e68a1c3.png">

In this case I can indeed re(run) the job but it is not replaced in the list (job is now at the top and the collection 18/19 are still in the same state):

<img width="469" alt="Screenshot 2019-09-11 at 17 18 19" src="https://user-images.githubusercontent.com/10990795/64710397-2a48dd00-d4b8-11e9-847f-b728fe3038a6.png">

is this expected behavior ?

**Comment by mvdbeek** [comment]
> Also I am pretty sure I saw the option you mentioned (replace the original item) in other context.

Correct, but you have a job that is dependent on this job, so resuming the job includes replacing the original element.

> Should I change the input type to select the datasets directly like this ?

No, the form should show you the correct input, if that's not the case something weird has happened. Still what you did should work as well.

It's not expected behavior, we'll have to look into this.

**Comment by cgirardot** [comment]
ok thanks. Also it is not the first time I encounter this bug. I have the *feeling* this is only the case for paired-end collections. Note that this bug is quite a killer when using workflows as the easiest to get away is to re-run all and cross fingers that no other errors occur.

**Comment by mvdbeek** [comment]
https://github.com/galaxyproject/galaxy/pull/9802 should allow re-running indivdual fialed jobs where the input are pairs
