### ISSUE TITLE
Subworkflow output starred as parent workflow output does not work

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#9226]
This might be related to #7959 but it appears that subworflow outputs are not included in the containing workflow outputs when 'starred' in the parent.
`GET /api/workflows/{workflow_id}/invocations/{invocation_id}` should include the output in its `outputs` property.

**Comment by jmchilton** [comment]
I wrote a test case and it passes, so I think has been fixed. https://github.com/galaxyproject/galaxy/pull/10478 adds the test case to ensure no regressions. Although I couldn't pinpoint a specific commit that I think would have fixed it, I know we've taken several passes at workflow state stuff around outputs and I can imagine it being a lot better than it was with whatever stable release was being used when the issue was open.

**Comment by innovate-invent** [comment]
I think this was on the first release with subworkflows

**Comment by jmchilton** [comment]
Well lets close this then, if it hits again let me know and we can go from there. Thanks for the report.
