### ISSUE TITLE
Running 'select first' lines with internet explorer overwrites sent job parameters

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#9250]
We experienced this in a training, users ran `Show beginning1` and `bgruening/text_processing/tp_head_tool/1.1.0`, and in all cases wrote `5` in the number of lines they wanted, and upon running found 10 lines, both in the information and the result file.

It seems to be internet explorer related 🙃🙃🙃

**Comment by wm75** [comment]
Confirmed. Had an independent error report from a usegalaxy.eu user yesterday. With Internet explorer tool parameters don't seem to reach Galaxy, but tools seem to always be running with default settings.

Though "Just don't use IE" is certainly good advice, the thing is that if you do, you do not get any warning that your results are not generated with the settings you entered, and this is really bad :cry:

**Comment by dannon** [comment]
@guerler Is this something you can take a look at?

**Comment by wm75** [comment]
Checked this at home on a Windows machine. Turns out it affects Microsoft Edge, too.

What I found so far is that param settings made in the UI never make it into the server request. The outgoing json has only the default settings (or the original settings if you reach the tool interface via the rerun button).

**Comment by wm75** [comment]
A bit more info...

It's not happening for every tool:
- bgruening/text_processing/tp_head_tool/1.1.0 is affected just like reported by @hexylena 
- https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/iuc/lofreq_filter/lofreq_filter/2.1.3.1 is affected, too

but:
- https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/devteam/add_value/addValue/1.0.0
seems to work properly

Tools seem to behave the same way on Galaxy Australia:
- https://usegalaxy.org.au/root?tool_id=Show beginning1 is compromised on au
- https://usegalaxy.org.au/root?tool_id=addValue is ok

Galaxy Main does not have a problem because its main page doesn't even load with Edge :smile:
This behavior really seems to make much more sense than silently producing results with wrong settings.

**Comment by wm75** [comment]
> Tools seem to behave the same way on Galaxy Australia: 
ping @Slugger70

**Comment by dannon** [comment]
Thanks for noticing usegalaxy.org doesn't load in edge at all.  I think I know what it is and I'm working on a fix.  If I get to it before Sam does, I'll try to look at the other bit, too.

**Comment by dannon** [comment]
The last commit in #9289 should fix the input issue, but I don't love it.  I'm working through other possible ideas.
