### ISSUE TITLE
Galaxy 20.05 local: Juypter Notebook IE produces incorrect docker run command

### ISSUE THREAD

**Issue by schmittst** [galaxyproject/galaxy#9578]
There seems to be an issue with the the Jupyter Notebook IE which cannot be started and gives the error: "Loading the interactive environment failed, please contact the Galaxy administrator for assistance". I had a look at the Galaxy.log and it seems that the docker run command for the Jupyter docker is assembled wrongly: the option -v contains too many quotation marks: ''"'"' (see first log entry)
This causes a strange -v option with one quatation mark to much at the beginning (see second log entry):
1) galaxy.visualization.plugins.interactive_environments INFO 2020-03-31 18:29:11,935 [p:4891,w:1,m:0] [uWSGIWorker1Core2] Starting docker container for IE jupyter with command [docker run -e DEBUG=false -e DEFAULT_CONTAINER_RUNTIME=120 --name=gie_49469b4b9c0d4641b8465c485abb4494 -e HISTORY_ID=4b78e217380c6d58 -e API_KEY=xxxxxx-e REMOTE_HOST=x.x.x.x -e 'CORS_ORIGIN=(null)://xxxxxxx.xxxxxxx.xx' -e USER_EMAIL=xxxxxxx@xxxxxxx -e PROXY_PREFIX=/gie_proxy/jupyter -e GALAXY_WEB_PORT=443 -e GALAXY_URL=https://galaxy.xxx.xxxx/ -e NOTEBOOK_PASSWORD=none -e DATASET_HID=None -e ADDITIONAL_IDS=None -d -P -v **''"'"'/srv/galaxy/database/objects/6/3/2/dataset_6324573e-4b62-4fd0-8321-5063b2f2d54a.dat:/import/[1] testplot.csv.csv'"'"''** jupyter-notebook]

2) docker: Error response from daemon: create '/srv/galaxy/database/objects/6/3/2/dataset_6324573e-4b62-4fd0-8321-5063b2f2d54a.dat: **"'/srv/galaxy/database/objects/6/3/2/dataset_6324573e-4b62-4fd0-8321-5063b2f2d54a.dat"** includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.

Can you guide me where to fix this in the code? I could not find the spot where this can be corrected... Thanks!

**Comment by bjoernvoss** [comment]
I have the same issue.

**Comment by schmittst** [comment]
I could never solve this nor could i find the code that causes the problem. Seems to be that this is also not on the agenda of the developers.
The only solution for me was to set "use_volumes = False" in the ini of the Jupyter Notebook IE.

**Comment by hexylena** [comment]
GIEs have been somewhat replaced by GxITs (interactive tools). This was not well communicated, internally or externally. GIEs have not been officially deprecated but the main proponents are not working on them anymore due to the presence of GxITs.

If it fits for your deployment, I recommend you try the jupyter interactive tool. While there is no documentation from the developer (it was not included in any release notes/or deployment documentation), @natefoo wrote a tutorial for the [galaxy admin training](https://training.galaxyproject.org/training-material/topics/admin/tutorials/interactive-tools/tutorial.html) which might be useful. It has *significant* additional requirements vs GIEs, you must be able to make wildcard DNS records, and have the ability to issue wildcard SSL certificates (if you use SSL).

In the short term, you can maybe avoid the "import datasets" feature, and then use `gx_get` inside the container, that will probably let it start properly. Hope that helps, I'm sorry you're encountering this issue.

**Comment by gbbio** [comment]
Can someone confirm that it is possible to use interactive tools on a local galaxy installation with the use of dnsmasq and without SSL? I had some issues with dnsmasq and before I put more time in this I would like to know if it is even possible already. Thanks in advanced.

**Comment by hexylena** [comment]
It's not possible in a local production setup without the extra DNS entries currently, but this is being worked on #8596 

It is fine without SSL though.

**Comment by gbbio** [comment]
Thanks for the reply, did not found that there was already a pr for this. I am looking forward to the results.

**Comment by hexylena** [comment]
Us too :) It's an extremely difficult restriction for many many smaller groups.
