### ISSUE TITLE
Sort collection for paired collections

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#9669]
Is there a way to extend this tool https://github.com/galaxyproject/galaxy/blob/e7c106b01d67c34841a029b71ee227e7b2aea231/lib/galaxy/tools/sort_collection_list.xml to process paired collections?

**Comment by jmchilton** [comment]
Good point @bernt-matthias - I'm going to assign @assuntad23 this issue I think it will be a good introduction to collection backend stuff and tools.

Just to clarify the input data collection here should have ``collection_type="list,list:paired"`` instead of ``collection_type="list"`` and the list part of the collection should be sorted - not the paired part (pairs have a fixed order).
