### ISSUE TITLE
Don't mark discovered added datasets as complete until all are added

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#983]
This is a problem only while:
- dataset collections are still being introduced and are not ubiquitous
- #740 isn't complete (so I can't switch all of my tools to producing/consuming DCs)

Dynamically discovered datasets are marked as complete even when they're not all discovered yet. This is counterintuitive and I feel to be incorrect behaviour. The job is not complete if all of the outputs haven't been discovered yet. Users have been _conditioned_ to accept "green = job complete" so dynamic discovery breaks this expectation. Users are not informed in **any** way that they're supposed to wait on outputs to show up.

I think I've mentioned this on IRC once, but I'm now filing a proper bug report (on behalf of my PI), as he emailed me a couple times this morning being very confused that not all of his datasets had shown up. When he went to run the tool again (thinking it failed in some weird way) discovered that they were all there.

**Comment by hexylena** [comment]
Oh, I misread this one. Sorry for the noise, thought it was about collections and was solved by the new progress bar.

**Comment by mblue9** [comment]
Would this be the same issue as what I encountered below? Collection appears green but the jobs are all stuck in a paused state. Because the collection was green I thought they had worked and had started trying to run other tools on the output. Would be good if the collection turned green only when the jobs were finished.

![screen shot 2018-07-09 at 4 10 03 pm](https://user-images.githubusercontent.com/5591821/42433466-d469065c-8392-11e8-81bd-b5f8ca973da4.png)

**Comment by mvdbeek** [comment]
Should be fixed by https://github.com/galaxyproject/galaxy/pull/7633
