### ISSUE TITLE
How to enable SLURM accounting storage on CloudLaunch?

### ISSUE THREAD

**Issue by yl3** [galaxyproject/galaxy#9927]
Hi,

Not sure if this is the right place to ask. I am running a SLURM cluster created by Galaxy CloudLaunch GVL v4.4.0 on AWS. I am able to successfully submit SLURM batch jobs, but I would like to enable storage monitoring to enable commands like `sacct`. Currently running `sacct` simple returns:

> SLURM accounting storage is disabled

How do I enable this SLURM storage accounting on a SLURM head node created by CloudLaunch?

**Comment by nuwang** [comment]
Hi @yl3,

This must be configured manually by editing slurm.conf. The slurm.conf file is managed by CloudMan, so you need to follow the following steps to override it.

1. First, run the following as root:
    ```
    mkdir -p /opt/cloudman/config/conftemplates/
    cp /mnt/cm/cm/conftemplates/slurm.conf /opt/cloudman/config/conftemplates/slurm.conf
    ```
    Copying it to this new location will allow you to customize it. CloudMan will then use your overridden conf template.

2. Edit the slurm.conf and configure accounting settings by following: https://slurm.schedmd.com/accounting.html

3. Reboot the machine. CloudMan will pick up the overridden slurm template at: `/opt/cloudman/config/conftemplates/slurm.conf` and your new settings should come into effect. (Restarting the services from within cloudman may also work, but I have not worked with this version in a while, so I'm just suggesting the safest route)

**Comment by yl3** [comment]
Hi @nuwang,

Thanks a lot for the quick response. That worked!

I wanted to ask you a related question since I recognized your name from [your recent blog post on GVL 5.0](https://galaxyproject.org/blog/2020-04-gvl5-beta2/). I really like the fact that GVL 4 provides me a SLURM cluster out of the box as well as the CloudMan Console that allows me to manage the cluster. Will this same features be available in GVL 5? I couldn't find out how to launch the SLURM server in the GVL 5.0 beta version.

**Comment by nuwang** [comment]
Hi @yl3,

At present, we have no plans to support SLURM anymore, because the new GVL is following a container/Kubernetes first strategy and is a ground-up rewrite of the GVL following a multi-tenant model. In principle, there's nothing preventing someone from writing a SLURM helm chart for Kubernetes and plugging it into the new GVL, and you could then just configure Galaxy to talk to that SLURM cluster. However, that's probably not all that useful in a Kubernetes context since containers are a better fit, which is likely why I can't seem to find a helm chart for SLURM through a quick search.

**Comment by yl3** [comment]
@nuwang I see. Thank you for your quick and detailed replies. Much appreciated!
