### ISSUE TITLE
The path for config files doesn't be resolved with respect to <config_dir>

### ISSUE THREAD

**Issue by gmauro** [galaxyproject/galaxy#9973]
I have this configuration
```
# The directory that will be prepended to relative paths in options
# specifying other Galaxy config files (e.g. datatypes_config_file).
# Defaults to the directory in which galaxy.yml is located.
config_dir: /opt/galaxy/config
	
# Optional configuration file similar to `job_config_file` to specify
# which Galaxy processes should schedule workflows.
# The value of this option will be resolved with respect to
# <config_dir>.
workflow_schedulers_config_file: workflow_schedulers_conf.xml

# Location of the configuration file containing extra user
# preferences.
# The value of this option will be resolved with respect to
# <config_dir>.
user_preferences_extra_conf_path: user_preferences_extra_conf.yml
```
and so I expect Galaxy looks for the files into this path: 
`/opt/galaxy/config/` 
but instead, I get this message in the log

```
Jul 08 22:20:29 test.internal.usegalaxy.eu.novalocal python[1367818]: galaxy.workflow.scheduling_manager INFO 2020-07-08 22:20:29,244 
Cannot find workflow schedulers plugin config file '/opt/galaxy/server/workflow_schedulers_conf.xml', using default scheduler.
...
Jul 08 22:50:15 test.internal.usegalaxy.eu.novalocal uwsgi[1383859]: WARNING:galaxy.config:Config 
file (/opt/galaxy/server/user_preferences_extra_conf.yml) could not be found or is malformed.

```

**Comment by bgruening** [comment]
@ic4f can you maybe look at this. Thanks!

**Comment by ic4f** [comment]
@bgruening @gmauro I'm looking into this.

**Comment by ic4f** [comment]
@gmauro this is a bug all right. I'll fix it, but it may take a few days: it's an oversight in how we handle config files and will require a few changes. Here's the offender: https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/config/__init__.py#L308 (we set the path based on your value on line 298, but we never place it in the right parent directory (we do so for the default value), moving it under root instead. Much of the config processing was streamlined this Fall; config file processing is one of the few remaining "special cases".

Since both of your values (`workflow_schedulers_config_file` and `user_preferences_extra_conf_path`) are the same as schema defaults, the quick solution would be to simply comment them out. Then, the default values will be assigned and placed in the correct directory (`/opt/galaxy/config/`). So this will work immediately. Meanwhile, I'll work on fixing this.

**Comment by gmauro** [comment]
@ic4f thanks for the prompt update and the solution
